// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/presentationmodelpricing"
)

// PresentationModelPricingCreate is the builder for creating a PresentationModelPricing entity.
type PresentationModelPricingCreate struct {
	config
	mutation *PresentationModelPricingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetModelName sets the "model_name" field.
func (_c *PresentationModelPricingCreate) SetModelName(v string) *PresentationModelPricingCreate {
	_c.mutation.SetModelName(v)
	return _c
}

// SetBillingMode sets the "billing_mode" field.
func (_c *PresentationModelPricingCreate) SetBillingMode(v string) *PresentationModelPricingCreate {
	_c.mutation.SetBillingMode(v)
	return _c
}

// SetNillableBillingMode sets the "billing_mode" field if the given value is not nil.
func (_c *PresentationModelPricingCreate) SetNillableBillingMode(v *string) *PresentationModelPricingCreate {
	if v != nil {
		_c.SetBillingMode(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *PresentationModelPricingCreate) SetCurrency(v string) *PresentationModelPricingCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *PresentationModelPricingCreate) SetNillableCurrency(v *string) *PresentationModelPricingCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetInputPrice sets the "input_price" field.
func (_c *PresentationModelPricingCreate) SetInputPrice(v float64) *PresentationModelPricingCreate {
	_c.mutation.SetInputPrice(v)
	return _c
}

// SetNillableInputPrice sets the "input_price" field if the given value is not nil.
func (_c *PresentationModelPricingCreate) SetNillableInputPrice(v *float64) *PresentationModelPricingCreate {
	if v != nil {
		_c.SetInputPrice(*v)
	}
	return _c
}

// SetOutputPrice sets the "output_price" field.
func (_c *PresentationModelPricingCreate) SetOutputPrice(v float64) *PresentationModelPricingCreate {
	_c.mutation.SetOutputPrice(v)
	return _c
}

// SetNillableOutputPrice sets the "output_price" field if the given value is not nil.
func (_c *PresentationModelPricingCreate) SetNillableOutputPrice(v *float64) *PresentationModelPricingCreate {
	if v != nil {
		_c.SetOutputPrice(*v)
	}
	return _c
}

// SetCacheWritePrice sets the "cache_write_price" field.
func (_c *PresentationModelPricingCreate) SetCacheWritePrice(v float64) *PresentationModelPricingCreate {
	_c.mutation.SetCacheWritePrice(v)
	return _c
}

// SetNillableCacheWritePrice sets the "cache_write_price" field if the given value is not nil.
func (_c *PresentationModelPricingCreate) SetNillableCacheWritePrice(v *float64) *PresentationModelPricingCreate {
	if v != nil {
		_c.SetCacheWritePrice(*v)
	}
	return _c
}

// SetCacheWrite1hPrice sets the "cache_write_1h_price" field.
func (_c *PresentationModelPricingCreate) SetCacheWrite1hPrice(v float64) *PresentationModelPricingCreate {
	_c.mutation.SetCacheWrite1hPrice(v)
	return _c
}

// SetNillableCacheWrite1hPrice sets the "cache_write_1h_price" field if the given value is not nil.
func (_c *PresentationModelPricingCreate) SetNillableCacheWrite1hPrice(v *float64) *PresentationModelPricingCreate {
	if v != nil {
		_c.SetCacheWrite1hPrice(*v)
	}
	return _c
}

// SetCacheReadPrice sets the "cache_read_price" field.
func (_c *PresentationModelPricingCreate) SetCacheReadPrice(v float64) *PresentationModelPricingCreate {
	_c.mutation.SetCacheReadPrice(v)
	return _c
}

// SetNillableCacheReadPrice sets the "cache_read_price" field if the given value is not nil.
func (_c *PresentationModelPricingCreate) SetNillableCacheReadPrice(v *float64) *PresentationModelPricingCreate {
	if v != nil {
		_c.SetCacheReadPrice(*v)
	}
	return _c
}

// SetPerRequestPrice sets the "per_request_price" field.
func (_c *PresentationModelPricingCreate) SetPerRequestPrice(v float64) *PresentationModelPricingCreate {
	_c.mutation.SetPerRequestPrice(v)
	return _c
}

// SetNillablePerRequestPrice sets the "per_request_price" field if the given value is not nil.
func (_c *PresentationModelPricingCreate) SetNillablePerRequestPrice(v *float64) *PresentationModelPricingCreate {
	if v != nil {
		_c.SetPerRequestPrice(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *PresentationModelPricingCreate) SetEnabled(v bool) *PresentationModelPricingCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *PresentationModelPricingCreate) SetNillableEnabled(v *bool) *PresentationModelPricingCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *PresentationModelPricingCreate) SetRemark(v string) *PresentationModelPricingCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *PresentationModelPricingCreate) SetNillableRemark(v *string) *PresentationModelPricingCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *PresentationModelPricingCreate) SetUpdatedBy(v int64) *PresentationModelPricingCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *PresentationModelPricingCreate) SetNillableUpdatedBy(v *int64) *PresentationModelPricingCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PresentationModelPricingCreate) SetCreatedAt(v time.Time) *PresentationModelPricingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PresentationModelPricingCreate) SetNillableCreatedAt(v *time.Time) *PresentationModelPricingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PresentationModelPricingCreate) SetUpdatedAt(v time.Time) *PresentationModelPricingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PresentationModelPricingCreate) SetNillableUpdatedAt(v *time.Time) *PresentationModelPricingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the PresentationModelPricingMutation object of the builder.
func (_c *PresentationModelPricingCreate) Mutation() *PresentationModelPricingMutation {
	return _c.mutation
}

// Save creates the PresentationModelPricing in the database.
func (_c *PresentationModelPricingCreate) Save(ctx context.Context) (*PresentationModelPricing, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PresentationModelPricingCreate) SaveX(ctx context.Context) *PresentationModelPricing {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PresentationModelPricingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PresentationModelPricingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PresentationModelPricingCreate) defaults() {
	if _, ok := _c.mutation.BillingMode(); !ok {
		v := presentationmodelpricing.DefaultBillingMode
		_c.mutation.SetBillingMode(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := presentationmodelpricing.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := presentationmodelpricing.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := presentationmodelpricing.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := presentationmodelpricing.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PresentationModelPricingCreate) check() error {
	if _, ok := _c.mutation.ModelName(); !ok {
		return &ValidationError{Name: "model_name", err: errors.New(`ent: missing required field "PresentationModelPricing.model_name"`)}
	}
	if v, ok := _c.mutation.ModelName(); ok {
		if err := presentationmodelpricing.ModelNameValidator(v); err != nil {
			return &ValidationError{Name: "model_name", err: fmt.Errorf(`ent: validator failed for field "PresentationModelPricing.model_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BillingMode(); !ok {
		return &ValidationError{Name: "billing_mode", err: errors.New(`ent: missing required field "PresentationModelPricing.billing_mode"`)}
	}
	if v, ok := _c.mutation.BillingMode(); ok {
		if err := presentationmodelpricing.BillingModeValidator(v); err != nil {
			return &ValidationError{Name: "billing_mode", err: fmt.Errorf(`ent: validator failed for field "PresentationModelPricing.billing_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "PresentationModelPricing.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := presentationmodelpricing.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "PresentationModelPricing.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "PresentationModelPricing.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PresentationModelPricing.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PresentationModelPricing.updated_at"`)}
	}
	return nil
}

func (_c *PresentationModelPricingCreate) sqlSave(ctx context.Context) (*PresentationModelPricing, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PresentationModelPricingCreate) createSpec() (*PresentationModelPricing, *sqlgraph.CreateSpec) {
	var (
		_node = &PresentationModelPricing{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(presentationmodelpricing.Table, sqlgraph.NewFieldSpec(presentationmodelpricing.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ModelName(); ok {
		_spec.SetField(presentationmodelpricing.FieldModelName, field.TypeString, value)
		_node.ModelName = value
	}
	if value, ok := _c.mutation.BillingMode(); ok {
		_spec.SetField(presentationmodelpricing.FieldBillingMode, field.TypeString, value)
		_node.BillingMode = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(presentationmodelpricing.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.InputPrice(); ok {
		_spec.SetField(presentationmodelpricing.FieldInputPrice, field.TypeFloat64, value)
		_node.InputPrice = &value
	}
	if value, ok := _c.mutation.OutputPrice(); ok {
		_spec.SetField(presentationmodelpricing.FieldOutputPrice, field.TypeFloat64, value)
		_node.OutputPrice = &value
	}
	if value, ok := _c.mutation.CacheWritePrice(); ok {
		_spec.SetField(presentationmodelpricing.FieldCacheWritePrice, field.TypeFloat64, value)
		_node.CacheWritePrice = &value
	}
	if value, ok := _c.mutation.CacheWrite1hPrice(); ok {
		_spec.SetField(presentationmodelpricing.FieldCacheWrite1hPrice, field.TypeFloat64, value)
		_node.CacheWrite1hPrice = &value
	}
	if value, ok := _c.mutation.CacheReadPrice(); ok {
		_spec.SetField(presentationmodelpricing.FieldCacheReadPrice, field.TypeFloat64, value)
		_node.CacheReadPrice = &value
	}
	if value, ok := _c.mutation.PerRequestPrice(); ok {
		_spec.SetField(presentationmodelpricing.FieldPerRequestPrice, field.TypeFloat64, value)
		_node.PerRequestPrice = &value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(presentationmodelpricing.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(presentationmodelpricing.FieldRemark, field.TypeString, value)
		_node.Remark = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(presentationmodelpricing.FieldUpdatedBy, field.TypeInt64, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(presentationmodelpricing.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(presentationmodelpricing.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PresentationModelPricing.Create().
//		SetModelName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PresentationModelPricingUpsert) {
//			SetModelName(v+v).
//		}).
//		Exec(ctx)
func (_c *PresentationModelPricingCreate) OnConflict(opts ...sql.ConflictOption) *PresentationModelPricingUpsertOne {
	_c.conflict = opts
	return &PresentationModelPricingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PresentationModelPricing.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PresentationModelPricingCreate) OnConflictColumns(columns ...string) *PresentationModelPricingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PresentationModelPricingUpsertOne{
		create: _c,
	}
}

type (
	// PresentationModelPricingUpsertOne is the builder for "upsert"-ing
	//  one PresentationModelPricing node.
	PresentationModelPricingUpsertOne struct {
		create *PresentationModelPricingCreate
	}

	// PresentationModelPricingUpsert is the "OnConflict" setter.
	PresentationModelPricingUpsert struct {
		*sql.UpdateSet
	}
)

// SetModelName sets the "model_name" field.
func (u *PresentationModelPricingUpsert) SetModelName(v string) *PresentationModelPricingUpsert {
	u.Set(presentationmodelpricing.FieldModelName, v)
	return u
}

// UpdateModelName sets the "model_name" field to the value that was provided on create.
func (u *PresentationModelPricingUpsert) UpdateModelName() *PresentationModelPricingUpsert {
	u.SetExcluded(presentationmodelpricing.FieldModelName)
	return u
}

// SetBillingMode sets the "billing_mode" field.
func (u *PresentationModelPricingUpsert) SetBillingMode(v string) *PresentationModelPricingUpsert {
	u.Set(presentationmodelpricing.FieldBillingMode, v)
	return u
}

// UpdateBillingMode sets the "billing_mode" field to the value that was provided on create.
func (u *PresentationModelPricingUpsert) UpdateBillingMode() *PresentationModelPricingUpsert {
	u.SetExcluded(presentationmodelpricing.FieldBillingMode)
	return u
}

// SetCurrency sets the "currency" field.
func (u *PresentationModelPricingUpsert) SetCurrency(v string) *PresentationModelPricingUpsert {
	u.Set(presentationmodelpricing.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PresentationModelPricingUpsert) UpdateCurrency() *PresentationModelPricingUpsert {
	u.SetExcluded(presentationmodelpricing.FieldCurrency)
	return u
}

// SetInputPrice sets the "input_price" field.
func (u *PresentationModelPricingUpsert) SetInputPrice(v float64) *PresentationModelPricingUpsert {
	u.Set(presentationmodelpricing.FieldInputPrice, v)
	return u
}

// UpdateInputPrice sets the "input_price" field to the value that was provided on create.
func (u *PresentationModelPricingUpsert) UpdateInputPrice() *PresentationModelPricingUpsert {
	u.SetExcluded(presentationmodelpricing.FieldInputPrice)
	return u
}

// AddInputPrice adds v to the "input_price" field.
func (u *PresentationModelPricingUpsert) AddInputPrice(v float64) *PresentationModelPricingUpsert {
	u.Add(presentationmodelpricing.FieldInputPrice, v)
	return u
}

// ClearInputPrice clears the value of the "input_price" field.
func (u *PresentationModelPricingUpsert) ClearInputPrice() *PresentationModelPricingUpsert {
	u.SetNull(presentationmodelpricing.FieldInputPrice)
	return u
}

// SetOutputPrice sets the "output_price" field.
func (u *PresentationModelPricingUpsert) SetOutputPrice(v float64) *PresentationModelPricingUpsert {
	u.Set(presentationmodelpricing.FieldOutputPrice, v)
	return u
}

// UpdateOutputPrice sets the "output_price" field to the value that was provided on create.
func (u *PresentationModelPricingUpsert) UpdateOutputPrice() *PresentationModelPricingUpsert {
	u.SetExcluded(presentationmodelpricing.FieldOutputPrice)
	return u
}

// AddOutputPrice adds v to the "output_price" field.
func (u *PresentationModelPricingUpsert) AddOutputPrice(v float64) *PresentationModelPricingUpsert {
	u.Add(presentationmodelpricing.FieldOutputPrice, v)
	return u
}

// ClearOutputPrice clears the value of the "output_price" field.
func (u *PresentationModelPricingUpsert) ClearOutputPrice() *PresentationModelPricingUpsert {
	u.SetNull(presentationmodelpricing.FieldOutputPrice)
	return u
}

// SetCacheWritePrice sets the "cache_write_price" field.
func (u *PresentationModelPricingUpsert) SetCacheWritePrice(v float64) *PresentationModelPricingUpsert {
	u.Set(presentationmodelpricing.FieldCacheWritePrice, v)
	return u
}

// UpdateCacheWritePrice sets the "cache_write_price" field to the value that was provided on create.
func (u *PresentationModelPricingUpsert) UpdateCacheWritePrice() *PresentationModelPricingUpsert {
	u.SetExcluded(presentationmodelpricing.FieldCacheWritePrice)
	return u
}

// AddCacheWritePrice adds v to the "cache_write_price" field.
func (u *PresentationModelPricingUpsert) AddCacheWritePrice(v float64) *PresentationModelPricingUpsert {
	u.Add(presentationmodelpricing.FieldCacheWritePrice, v)
	return u
}

// ClearCacheWritePrice clears the value of the "cache_write_price" field.
func (u *PresentationModelPricingUpsert) ClearCacheWritePrice() *PresentationModelPricingUpsert {
	u.SetNull(presentationmodelpricing.FieldCacheWritePrice)
	return u
}

// SetCacheWrite1hPrice sets the "cache_write_1h_price" field.
func (u *PresentationModelPricingUpsert) SetCacheWrite1hPrice(v float64) *PresentationModelPricingUpsert {
	u.Set(presentationmodelpricing.FieldCacheWrite1hPrice, v)
	return u
}

// UpdateCacheWrite1hPrice sets the "cache_write_1h_price" field to the value that was provided on create.
func (u *PresentationModelPricingUpsert) UpdateCacheWrite1hPrice() *PresentationModelPricingUpsert {
	u.SetExcluded(presentationmodelpricing.FieldCacheWrite1hPrice)
	return u
}

// AddCacheWrite1hPrice adds v to the "cache_write_1h_price" field.
func (u *PresentationModelPricingUpsert) AddCacheWrite1hPrice(v float64) *PresentationModelPricingUpsert {
	u.Add(presentationmodelpricing.FieldCacheWrite1hPrice, v)
	return u
}

// ClearCacheWrite1hPrice clears the value of the "cache_write_1h_price" field.
func (u *PresentationModelPricingUpsert) ClearCacheWrite1hPrice() *PresentationModelPricingUpsert {
	u.SetNull(presentationmodelpricing.FieldCacheWrite1hPrice)
	return u
}

// SetCacheReadPrice sets the "cache_read_price" field.
func (u *PresentationModelPricingUpsert) SetCacheReadPrice(v float64) *PresentationModelPricingUpsert {
	u.Set(presentationmodelpricing.FieldCacheReadPrice, v)
	return u
}

// UpdateCacheReadPrice sets the "cache_read_price" field to the value that was provided on create.
func (u *PresentationModelPricingUpsert) UpdateCacheReadPrice() *PresentationModelPricingUpsert {
	u.SetExcluded(presentationmodelpricing.FieldCacheReadPrice)
	return u
}

// AddCacheReadPrice adds v to the "cache_read_price" field.
func (u *PresentationModelPricingUpsert) AddCacheReadPrice(v float64) *PresentationModelPricingUpsert {
	u.Add(presentationmodelpricing.FieldCacheReadPrice, v)
	return u
}

// ClearCacheReadPrice clears the value of the "cache_read_price" field.
func (u *PresentationModelPricingUpsert) ClearCacheReadPrice() *PresentationModelPricingUpsert {
	u.SetNull(presentationmodelpricing.FieldCacheReadPrice)
	return u
}

// SetPerRequestPrice sets the "per_request_price" field.
func (u *PresentationModelPricingUpsert) SetPerRequestPrice(v float64) *PresentationModelPricingUpsert {
	u.Set(presentationmodelpricing.FieldPerRequestPrice, v)
	return u
}

// UpdatePerRequestPrice sets the "per_request_price" field to the value that was provided on create.
func (u *PresentationModelPricingUpsert) UpdatePerRequestPrice() *PresentationModelPricingUpsert {
	u.SetExcluded(presentationmodelpricing.FieldPerRequestPrice)
	return u
}

// AddPerRequestPrice adds v to the "per_request_price" field.
func (u *PresentationModelPricingUpsert) AddPerRequestPrice(v float64) *PresentationModelPricingUpsert {
	u.Add(presentationmodelpricing.FieldPerRequestPrice, v)
	return u
}

// ClearPerRequestPrice clears the value of the "per_request_price" field.
func (u *PresentationModelPricingUpsert) ClearPerRequestPrice() *PresentationModelPricingUpsert {
	u.SetNull(presentationmodelpricing.FieldPerRequestPrice)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *PresentationModelPricingUpsert) SetEnabled(v bool) *PresentationModelPricingUpsert {
	u.Set(presentationmodelpricing.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PresentationModelPricingUpsert) UpdateEnabled() *PresentationModelPricingUpsert {
	u.SetExcluded(presentationmodelpricing.FieldEnabled)
	return u
}

// SetRemark sets the "remark" field.
func (u *PresentationModelPricingUpsert) SetRemark(v string) *PresentationModelPricingUpsert {
	u.Set(presentationmodelpricing.FieldRemark, v)
	return u
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *PresentationModelPricingUpsert) UpdateRemark() *PresentationModelPricingUpsert {
	u.SetExcluded(presentationmodelpricing.FieldRemark)
	return u
}

// ClearRemark clears the value of the "remark" field.
func (u *PresentationModelPricingUpsert) ClearRemark() *PresentationModelPricingUpsert {
	u.SetNull(presentationmodelpricing.FieldRemark)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *PresentationModelPricingUpsert) SetUpdatedBy(v int64) *PresentationModelPricingUpsert {
	u.Set(presentationmodelpricing.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *PresentationModelPricingUpsert) UpdateUpdatedBy() *PresentationModelPricingUpsert {
	u.SetExcluded(presentationmodelpricing.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *PresentationModelPricingUpsert) AddUpdatedBy(v int64) *PresentationModelPricingUpsert {
	u.Add(presentationmodelpricing.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *PresentationModelPricingUpsert) ClearUpdatedBy() *PresentationModelPricingUpsert {
	u.SetNull(presentationmodelpricing.FieldUpdatedBy)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PresentationModelPricingUpsert) SetUpdatedAt(v time.Time) *PresentationModelPricingUpsert {
	u.Set(presentationmodelpricing.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PresentationModelPricingUpsert) UpdateUpdatedAt() *PresentationModelPricingUpsert {
	u.SetExcluded(presentationmodelpricing.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PresentationModelPricing.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PresentationModelPricingUpsertOne) UpdateNewValues() *PresentationModelPricingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(presentationmodelpricing.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PresentationModelPricing.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PresentationModelPricingUpsertOne) Ignore() *PresentationModelPricingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PresentationModelPricingUpsertOne) DoNothing() *PresentationModelPricingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PresentationModelPricingCreate.OnConflict
// documentation for more info.
func (u *PresentationModelPricingUpsertOne) Update(set func(*PresentationModelPricingUpsert)) *PresentationModelPricingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PresentationModelPricingUpsert{UpdateSet: update})
	}))
	return u
}

// SetModelName sets the "model_name" field.
func (u *PresentationModelPricingUpsertOne) SetModelName(v string) *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.SetModelName(v)
	})
}

// UpdateModelName sets the "model_name" field to the value that was provided on create.
func (u *PresentationModelPricingUpsertOne) UpdateModelName() *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.UpdateModelName()
	})
}

// SetBillingMode sets the "billing_mode" field.
func (u *PresentationModelPricingUpsertOne) SetBillingMode(v string) *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.SetBillingMode(v)
	})
}

// UpdateBillingMode sets the "billing_mode" field to the value that was provided on create.
func (u *PresentationModelPricingUpsertOne) UpdateBillingMode() *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.UpdateBillingMode()
	})
}

// SetCurrency sets the "currency" field.
func (u *PresentationModelPricingUpsertOne) SetCurrency(v string) *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PresentationModelPricingUpsertOne) UpdateCurrency() *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.UpdateCurrency()
	})
}

// SetInputPrice sets the "input_price" field.
func (u *PresentationModelPricingUpsertOne) SetInputPrice(v float64) *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.SetInputPrice(v)
	})
}

// AddInputPrice adds v to the "input_price" field.
func (u *PresentationModelPricingUpsertOne) AddInputPrice(v float64) *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.AddInputPrice(v)
	})
}

// UpdateInputPrice sets the "input_price" field to the value that was provided on create.
func (u *PresentationModelPricingUpsertOne) UpdateInputPrice() *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.UpdateInputPrice()
	})
}

// ClearInputPrice clears the value of the "input_price" field.
func (u *PresentationModelPricingUpsertOne) ClearInputPrice() *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.ClearInputPrice()
	})
}

// SetOutputPrice sets the "output_price" field.
func (u *PresentationModelPricingUpsertOne) SetOutputPrice(v float64) *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.SetOutputPrice(v)
	})
}

// AddOutputPrice adds v to the "output_price" field.
func (u *PresentationModelPricingUpsertOne) AddOutputPrice(v float64) *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.AddOutputPrice(v)
	})
}

// UpdateOutputPrice sets the "output_price" field to the value that was provided on create.
func (u *PresentationModelPricingUpsertOne) UpdateOutputPrice() *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.UpdateOutputPrice()
	})
}

// ClearOutputPrice clears the value of the "output_price" field.
func (u *PresentationModelPricingUpsertOne) ClearOutputPrice() *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.ClearOutputPrice()
	})
}

// SetCacheWritePrice sets the "cache_write_price" field.
func (u *PresentationModelPricingUpsertOne) SetCacheWritePrice(v float64) *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.SetCacheWritePrice(v)
	})
}

// AddCacheWritePrice adds v to the "cache_write_price" field.
func (u *PresentationModelPricingUpsertOne) AddCacheWritePrice(v float64) *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.AddCacheWritePrice(v)
	})
}

// UpdateCacheWritePrice sets the "cache_write_price" field to the value that was provided on create.
func (u *PresentationModelPricingUpsertOne) UpdateCacheWritePrice() *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.UpdateCacheWritePrice()
	})
}

// ClearCacheWritePrice clears the value of the "cache_write_price" field.
func (u *PresentationModelPricingUpsertOne) ClearCacheWritePrice() *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.ClearCacheWritePrice()
	})
}

// SetCacheWrite1hPrice sets the "cache_write_1h_price" field.
func (u *PresentationModelPricingUpsertOne) SetCacheWrite1hPrice(v float64) *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.SetCacheWrite1hPrice(v)
	})
}

// AddCacheWrite1hPrice adds v to the "cache_write_1h_price" field.
func (u *PresentationModelPricingUpsertOne) AddCacheWrite1hPrice(v float64) *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.AddCacheWrite1hPrice(v)
	})
}

// UpdateCacheWrite1hPrice sets the "cache_write_1h_price" field to the value that was provided on create.
func (u *PresentationModelPricingUpsertOne) UpdateCacheWrite1hPrice() *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.UpdateCacheWrite1hPrice()
	})
}

// ClearCacheWrite1hPrice clears the value of the "cache_write_1h_price" field.
func (u *PresentationModelPricingUpsertOne) ClearCacheWrite1hPrice() *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.ClearCacheWrite1hPrice()
	})
}

// SetCacheReadPrice sets the "cache_read_price" field.
func (u *PresentationModelPricingUpsertOne) SetCacheReadPrice(v float64) *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.SetCacheReadPrice(v)
	})
}

// AddCacheReadPrice adds v to the "cache_read_price" field.
func (u *PresentationModelPricingUpsertOne) AddCacheReadPrice(v float64) *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.AddCacheReadPrice(v)
	})
}

// UpdateCacheReadPrice sets the "cache_read_price" field to the value that was provided on create.
func (u *PresentationModelPricingUpsertOne) UpdateCacheReadPrice() *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.UpdateCacheReadPrice()
	})
}

// ClearCacheReadPrice clears the value of the "cache_read_price" field.
func (u *PresentationModelPricingUpsertOne) ClearCacheReadPrice() *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.ClearCacheReadPrice()
	})
}

// SetPerRequestPrice sets the "per_request_price" field.
func (u *PresentationModelPricingUpsertOne) SetPerRequestPrice(v float64) *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.SetPerRequestPrice(v)
	})
}

// AddPerRequestPrice adds v to the "per_request_price" field.
func (u *PresentationModelPricingUpsertOne) AddPerRequestPrice(v float64) *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.AddPerRequestPrice(v)
	})
}

// UpdatePerRequestPrice sets the "per_request_price" field to the value that was provided on create.
func (u *PresentationModelPricingUpsertOne) UpdatePerRequestPrice() *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.UpdatePerRequestPrice()
	})
}

// ClearPerRequestPrice clears the value of the "per_request_price" field.
func (u *PresentationModelPricingUpsertOne) ClearPerRequestPrice() *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.ClearPerRequestPrice()
	})
}

// SetEnabled sets the "enabled" field.
func (u *PresentationModelPricingUpsertOne) SetEnabled(v bool) *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PresentationModelPricingUpsertOne) UpdateEnabled() *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.UpdateEnabled()
	})
}

// SetRemark sets the "remark" field.
func (u *PresentationModelPricingUpsertOne) SetRemark(v string) *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *PresentationModelPricingUpsertOne) UpdateRemark() *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *PresentationModelPricingUpsertOne) ClearRemark() *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.ClearRemark()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *PresentationModelPricingUpsertOne) SetUpdatedBy(v int64) *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *PresentationModelPricingUpsertOne) AddUpdatedBy(v int64) *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *PresentationModelPricingUpsertOne) UpdateUpdatedBy() *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *PresentationModelPricingUpsertOne) ClearUpdatedBy() *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PresentationModelPricingUpsertOne) SetUpdatedAt(v time.Time) *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PresentationModelPricingUpsertOne) UpdateUpdatedAt() *PresentationModelPricingUpsertOne {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PresentationModelPricingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PresentationModelPricingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PresentationModelPricingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PresentationModelPricingUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PresentationModelPricingUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PresentationModelPricingCreateBulk is the builder for creating many PresentationModelPricing entities in bulk.
type PresentationModelPricingCreateBulk struct {
	config
	err      error
	builders []*PresentationModelPricingCreate
	conflict []sql.ConflictOption
}

// Save creates the PresentationModelPricing entities in the database.
func (_c *PresentationModelPricingCreateBulk) Save(ctx context.Context) ([]*PresentationModelPricing, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PresentationModelPricing, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PresentationModelPricingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PresentationModelPricingCreateBulk) SaveX(ctx context.Context) []*PresentationModelPricing {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PresentationModelPricingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PresentationModelPricingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PresentationModelPricing.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PresentationModelPricingUpsert) {
//			SetModelName(v+v).
//		}).
//		Exec(ctx)
func (_c *PresentationModelPricingCreateBulk) OnConflict(opts ...sql.ConflictOption) *PresentationModelPricingUpsertBulk {
	_c.conflict = opts
	return &PresentationModelPricingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PresentationModelPricing.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PresentationModelPricingCreateBulk) OnConflictColumns(columns ...string) *PresentationModelPricingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PresentationModelPricingUpsertBulk{
		create: _c,
	}
}

// PresentationModelPricingUpsertBulk is the builder for "upsert"-ing
// a bulk of PresentationModelPricing nodes.
type PresentationModelPricingUpsertBulk struct {
	create *PresentationModelPricingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PresentationModelPricing.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PresentationModelPricingUpsertBulk) UpdateNewValues() *PresentationModelPricingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(presentationmodelpricing.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PresentationModelPricing.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PresentationModelPricingUpsertBulk) Ignore() *PresentationModelPricingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PresentationModelPricingUpsertBulk) DoNothing() *PresentationModelPricingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PresentationModelPricingCreateBulk.OnConflict
// documentation for more info.
func (u *PresentationModelPricingUpsertBulk) Update(set func(*PresentationModelPricingUpsert)) *PresentationModelPricingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PresentationModelPricingUpsert{UpdateSet: update})
	}))
	return u
}

// SetModelName sets the "model_name" field.
func (u *PresentationModelPricingUpsertBulk) SetModelName(v string) *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.SetModelName(v)
	})
}

// UpdateModelName sets the "model_name" field to the value that was provided on create.
func (u *PresentationModelPricingUpsertBulk) UpdateModelName() *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.UpdateModelName()
	})
}

// SetBillingMode sets the "billing_mode" field.
func (u *PresentationModelPricingUpsertBulk) SetBillingMode(v string) *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.SetBillingMode(v)
	})
}

// UpdateBillingMode sets the "billing_mode" field to the value that was provided on create.
func (u *PresentationModelPricingUpsertBulk) UpdateBillingMode() *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.UpdateBillingMode()
	})
}

// SetCurrency sets the "currency" field.
func (u *PresentationModelPricingUpsertBulk) SetCurrency(v string) *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PresentationModelPricingUpsertBulk) UpdateCurrency() *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.UpdateCurrency()
	})
}

// SetInputPrice sets the "input_price" field.
func (u *PresentationModelPricingUpsertBulk) SetInputPrice(v float64) *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.SetInputPrice(v)
	})
}

// AddInputPrice adds v to the "input_price" field.
func (u *PresentationModelPricingUpsertBulk) AddInputPrice(v float64) *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.AddInputPrice(v)
	})
}

// UpdateInputPrice sets the "input_price" field to the value that was provided on create.
func (u *PresentationModelPricingUpsertBulk) UpdateInputPrice() *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.UpdateInputPrice()
	})
}

// ClearInputPrice clears the value of the "input_price" field.
func (u *PresentationModelPricingUpsertBulk) ClearInputPrice() *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.ClearInputPrice()
	})
}

// SetOutputPrice sets the "output_price" field.
func (u *PresentationModelPricingUpsertBulk) SetOutputPrice(v float64) *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.SetOutputPrice(v)
	})
}

// AddOutputPrice adds v to the "output_price" field.
func (u *PresentationModelPricingUpsertBulk) AddOutputPrice(v float64) *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.AddOutputPrice(v)
	})
}

// UpdateOutputPrice sets the "output_price" field to the value that was provided on create.
func (u *PresentationModelPricingUpsertBulk) UpdateOutputPrice() *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.UpdateOutputPrice()
	})
}

// ClearOutputPrice clears the value of the "output_price" field.
func (u *PresentationModelPricingUpsertBulk) ClearOutputPrice() *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.ClearOutputPrice()
	})
}

// SetCacheWritePrice sets the "cache_write_price" field.
func (u *PresentationModelPricingUpsertBulk) SetCacheWritePrice(v float64) *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.SetCacheWritePrice(v)
	})
}

// AddCacheWritePrice adds v to the "cache_write_price" field.
func (u *PresentationModelPricingUpsertBulk) AddCacheWritePrice(v float64) *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.AddCacheWritePrice(v)
	})
}

// UpdateCacheWritePrice sets the "cache_write_price" field to the value that was provided on create.
func (u *PresentationModelPricingUpsertBulk) UpdateCacheWritePrice() *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.UpdateCacheWritePrice()
	})
}

// ClearCacheWritePrice clears the value of the "cache_write_price" field.
func (u *PresentationModelPricingUpsertBulk) ClearCacheWritePrice() *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.ClearCacheWritePrice()
	})
}

// SetCacheWrite1hPrice sets the "cache_write_1h_price" field.
func (u *PresentationModelPricingUpsertBulk) SetCacheWrite1hPrice(v float64) *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.SetCacheWrite1hPrice(v)
	})
}

// AddCacheWrite1hPrice adds v to the "cache_write_1h_price" field.
func (u *PresentationModelPricingUpsertBulk) AddCacheWrite1hPrice(v float64) *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.AddCacheWrite1hPrice(v)
	})
}

// UpdateCacheWrite1hPrice sets the "cache_write_1h_price" field to the value that was provided on create.
func (u *PresentationModelPricingUpsertBulk) UpdateCacheWrite1hPrice() *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.UpdateCacheWrite1hPrice()
	})
}

// ClearCacheWrite1hPrice clears the value of the "cache_write_1h_price" field.
func (u *PresentationModelPricingUpsertBulk) ClearCacheWrite1hPrice() *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.ClearCacheWrite1hPrice()
	})
}

// SetCacheReadPrice sets the "cache_read_price" field.
func (u *PresentationModelPricingUpsertBulk) SetCacheReadPrice(v float64) *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.SetCacheReadPrice(v)
	})
}

// AddCacheReadPrice adds v to the "cache_read_price" field.
func (u *PresentationModelPricingUpsertBulk) AddCacheReadPrice(v float64) *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.AddCacheReadPrice(v)
	})
}

// UpdateCacheReadPrice sets the "cache_read_price" field to the value that was provided on create.
func (u *PresentationModelPricingUpsertBulk) UpdateCacheReadPrice() *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.UpdateCacheReadPrice()
	})
}

// ClearCacheReadPrice clears the value of the "cache_read_price" field.
func (u *PresentationModelPricingUpsertBulk) ClearCacheReadPrice() *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.ClearCacheReadPrice()
	})
}

// SetPerRequestPrice sets the "per_request_price" field.
func (u *PresentationModelPricingUpsertBulk) SetPerRequestPrice(v float64) *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.SetPerRequestPrice(v)
	})
}

// AddPerRequestPrice adds v to the "per_request_price" field.
func (u *PresentationModelPricingUpsertBulk) AddPerRequestPrice(v float64) *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.AddPerRequestPrice(v)
	})
}

// UpdatePerRequestPrice sets the "per_request_price" field to the value that was provided on create.
func (u *PresentationModelPricingUpsertBulk) UpdatePerRequestPrice() *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.UpdatePerRequestPrice()
	})
}

// ClearPerRequestPrice clears the value of the "per_request_price" field.
func (u *PresentationModelPricingUpsertBulk) ClearPerRequestPrice() *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.ClearPerRequestPrice()
	})
}

// SetEnabled sets the "enabled" field.
func (u *PresentationModelPricingUpsertBulk) SetEnabled(v bool) *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PresentationModelPricingUpsertBulk) UpdateEnabled() *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.UpdateEnabled()
	})
}

// SetRemark sets the "remark" field.
func (u *PresentationModelPricingUpsertBulk) SetRemark(v string) *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *PresentationModelPricingUpsertBulk) UpdateRemark() *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *PresentationModelPricingUpsertBulk) ClearRemark() *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.ClearRemark()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *PresentationModelPricingUpsertBulk) SetUpdatedBy(v int64) *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *PresentationModelPricingUpsertBulk) AddUpdatedBy(v int64) *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *PresentationModelPricingUpsertBulk) UpdateUpdatedBy() *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *PresentationModelPricingUpsertBulk) ClearUpdatedBy() *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PresentationModelPricingUpsertBulk) SetUpdatedAt(v time.Time) *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PresentationModelPricingUpsertBulk) UpdateUpdatedAt() *PresentationModelPricingUpsertBulk {
	return u.Update(func(s *PresentationModelPricingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PresentationModelPricingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PresentationModelPricingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PresentationModelPricingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PresentationModelPricingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
