// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/researchapplication"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// ResearchApplication is the model entity for the ResearchApplication schema.
type ResearchApplication struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ReviewerID holds the value of the "reviewer_id" field.
	ReviewerID *int64 `json:"reviewer_id,omitempty"`
	// ReviewNotes holds the value of the "review_notes" field.
	ReviewNotes *string `json:"review_notes,omitempty"`
	// RewardAmount holds the value of the "reward_amount" field.
	RewardAmount *float64 `json:"reward_amount,omitempty"`
	// IssuedRedeemCodeID holds the value of the "issued_redeem_code_id" field.
	IssuedRedeemCodeID *int64 `json:"issued_redeem_code_id,omitempty"`
	// ReviewedAt holds the value of the "reviewed_at" field.
	ReviewedAt *time.Time `json:"reviewed_at,omitempty"`
	// Attachments holds the value of the "attachments" field.
	Attachments  []domain.ResearchAttachmentMeta `json:"attachments,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ResearchApplication) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case researchapplication.FieldAttachments:
			values[i] = new([]byte)
		case researchapplication.FieldRewardAmount:
			values[i] = new(sql.NullFloat64)
		case researchapplication.FieldID, researchapplication.FieldUserID, researchapplication.FieldReviewerID, researchapplication.FieldIssuedRedeemCodeID:
			values[i] = new(sql.NullInt64)
		case researchapplication.FieldDescription, researchapplication.FieldStatus, researchapplication.FieldReviewNotes:
			values[i] = new(sql.NullString)
		case researchapplication.FieldCreatedAt, researchapplication.FieldUpdatedAt, researchapplication.FieldReviewedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ResearchApplication fields.
func (_m *ResearchApplication) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case researchapplication.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case researchapplication.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case researchapplication.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case researchapplication.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case researchapplication.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case researchapplication.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case researchapplication.FieldReviewerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reviewer_id", values[i])
			} else if value.Valid {
				_m.ReviewerID = new(int64)
				*_m.ReviewerID = value.Int64
			}
		case researchapplication.FieldReviewNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field review_notes", values[i])
			} else if value.Valid {
				_m.ReviewNotes = new(string)
				*_m.ReviewNotes = value.String
			}
		case researchapplication.FieldRewardAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field reward_amount", values[i])
			} else if value.Valid {
				_m.RewardAmount = new(float64)
				*_m.RewardAmount = value.Float64
			}
		case researchapplication.FieldIssuedRedeemCodeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field issued_redeem_code_id", values[i])
			} else if value.Valid {
				_m.IssuedRedeemCodeID = new(int64)
				*_m.IssuedRedeemCodeID = value.Int64
			}
		case researchapplication.FieldReviewedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_at", values[i])
			} else if value.Valid {
				_m.ReviewedAt = new(time.Time)
				*_m.ReviewedAt = value.Time
			}
		case researchapplication.FieldAttachments:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field attachments", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Attachments); err != nil {
					return fmt.Errorf("unmarshal field attachments: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ResearchApplication.
// This includes values selected through modifiers, order, etc.
func (_m *ResearchApplication) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ResearchApplication.
// Note that you need to call ResearchApplication.Unwrap() before calling this method if this ResearchApplication
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ResearchApplication) Update() *ResearchApplicationUpdateOne {
	return NewResearchApplicationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ResearchApplication entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ResearchApplication) Unwrap() *ResearchApplication {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ResearchApplication is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ResearchApplication) String() string {
	var builder strings.Builder
	builder.WriteString("ResearchApplication(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.ReviewerID; v != nil {
		builder.WriteString("reviewer_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ReviewNotes; v != nil {
		builder.WriteString("review_notes=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RewardAmount; v != nil {
		builder.WriteString("reward_amount=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.IssuedRedeemCodeID; v != nil {
		builder.WriteString("issued_redeem_code_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ReviewedAt; v != nil {
		builder.WriteString("reviewed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("attachments=")
	builder.WriteString(fmt.Sprintf("%v", _m.Attachments))
	builder.WriteByte(')')
	return builder.String()
}

// ResearchApplications is a parsable slice of ResearchApplication.
type ResearchApplications []*ResearchApplication
