// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/researchapplication"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// ResearchApplicationUpdate is the builder for updating ResearchApplication entities.
type ResearchApplicationUpdate struct {
	config
	hooks    []Hook
	mutation *ResearchApplicationMutation
}

// Where appends a list predicates to the ResearchApplicationUpdate builder.
func (_u *ResearchApplicationUpdate) Where(ps ...predicate.ResearchApplication) *ResearchApplicationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResearchApplicationUpdate) SetUpdatedAt(v time.Time) *ResearchApplicationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ResearchApplicationUpdate) SetUserID(v int64) *ResearchApplicationUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ResearchApplicationUpdate) SetNillableUserID(v *int64) *ResearchApplicationUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ResearchApplicationUpdate) AddUserID(v int64) *ResearchApplicationUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *ResearchApplicationUpdate) SetDescription(v string) *ResearchApplicationUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ResearchApplicationUpdate) SetNillableDescription(v *string) *ResearchApplicationUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ResearchApplicationUpdate) SetStatus(v string) *ResearchApplicationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ResearchApplicationUpdate) SetNillableStatus(v *string) *ResearchApplicationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetReviewerID sets the "reviewer_id" field.
func (_u *ResearchApplicationUpdate) SetReviewerID(v int64) *ResearchApplicationUpdate {
	_u.mutation.ResetReviewerID()
	_u.mutation.SetReviewerID(v)
	return _u
}

// SetNillableReviewerID sets the "reviewer_id" field if the given value is not nil.
func (_u *ResearchApplicationUpdate) SetNillableReviewerID(v *int64) *ResearchApplicationUpdate {
	if v != nil {
		_u.SetReviewerID(*v)
	}
	return _u
}

// AddReviewerID adds value to the "reviewer_id" field.
func (_u *ResearchApplicationUpdate) AddReviewerID(v int64) *ResearchApplicationUpdate {
	_u.mutation.AddReviewerID(v)
	return _u
}

// ClearReviewerID clears the value of the "reviewer_id" field.
func (_u *ResearchApplicationUpdate) ClearReviewerID() *ResearchApplicationUpdate {
	_u.mutation.ClearReviewerID()
	return _u
}

// SetReviewNotes sets the "review_notes" field.
func (_u *ResearchApplicationUpdate) SetReviewNotes(v string) *ResearchApplicationUpdate {
	_u.mutation.SetReviewNotes(v)
	return _u
}

// SetNillableReviewNotes sets the "review_notes" field if the given value is not nil.
func (_u *ResearchApplicationUpdate) SetNillableReviewNotes(v *string) *ResearchApplicationUpdate {
	if v != nil {
		_u.SetReviewNotes(*v)
	}
	return _u
}

// ClearReviewNotes clears the value of the "review_notes" field.
func (_u *ResearchApplicationUpdate) ClearReviewNotes() *ResearchApplicationUpdate {
	_u.mutation.ClearReviewNotes()
	return _u
}

// SetRewardAmount sets the "reward_amount" field.
func (_u *ResearchApplicationUpdate) SetRewardAmount(v float64) *ResearchApplicationUpdate {
	_u.mutation.ResetRewardAmount()
	_u.mutation.SetRewardAmount(v)
	return _u
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_u *ResearchApplicationUpdate) SetNillableRewardAmount(v *float64) *ResearchApplicationUpdate {
	if v != nil {
		_u.SetRewardAmount(*v)
	}
	return _u
}

// AddRewardAmount adds value to the "reward_amount" field.
func (_u *ResearchApplicationUpdate) AddRewardAmount(v float64) *ResearchApplicationUpdate {
	_u.mutation.AddRewardAmount(v)
	return _u
}

// ClearRewardAmount clears the value of the "reward_amount" field.
func (_u *ResearchApplicationUpdate) ClearRewardAmount() *ResearchApplicationUpdate {
	_u.mutation.ClearRewardAmount()
	return _u
}

// SetIssuedRedeemCodeID sets the "issued_redeem_code_id" field.
func (_u *ResearchApplicationUpdate) SetIssuedRedeemCodeID(v int64) *ResearchApplicationUpdate {
	_u.mutation.ResetIssuedRedeemCodeID()
	_u.mutation.SetIssuedRedeemCodeID(v)
	return _u
}

// SetNillableIssuedRedeemCodeID sets the "issued_redeem_code_id" field if the given value is not nil.
func (_u *ResearchApplicationUpdate) SetNillableIssuedRedeemCodeID(v *int64) *ResearchApplicationUpdate {
	if v != nil {
		_u.SetIssuedRedeemCodeID(*v)
	}
	return _u
}

// AddIssuedRedeemCodeID adds value to the "issued_redeem_code_id" field.
func (_u *ResearchApplicationUpdate) AddIssuedRedeemCodeID(v int64) *ResearchApplicationUpdate {
	_u.mutation.AddIssuedRedeemCodeID(v)
	return _u
}

// ClearIssuedRedeemCodeID clears the value of the "issued_redeem_code_id" field.
func (_u *ResearchApplicationUpdate) ClearIssuedRedeemCodeID() *ResearchApplicationUpdate {
	_u.mutation.ClearIssuedRedeemCodeID()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *ResearchApplicationUpdate) SetReviewedAt(v time.Time) *ResearchApplicationUpdate {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *ResearchApplicationUpdate) SetNillableReviewedAt(v *time.Time) *ResearchApplicationUpdate {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *ResearchApplicationUpdate) ClearReviewedAt() *ResearchApplicationUpdate {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetAttachments sets the "attachments" field.
func (_u *ResearchApplicationUpdate) SetAttachments(v []domain.ResearchAttachmentMeta) *ResearchApplicationUpdate {
	_u.mutation.SetAttachments(v)
	return _u
}

// AppendAttachments appends value to the "attachments" field.
func (_u *ResearchApplicationUpdate) AppendAttachments(v []domain.ResearchAttachmentMeta) *ResearchApplicationUpdate {
	_u.mutation.AppendAttachments(v)
	return _u
}

// ClearAttachments clears the value of the "attachments" field.
func (_u *ResearchApplicationUpdate) ClearAttachments() *ResearchApplicationUpdate {
	_u.mutation.ClearAttachments()
	return _u
}

// Mutation returns the ResearchApplicationMutation object of the builder.
func (_u *ResearchApplicationUpdate) Mutation() *ResearchApplicationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ResearchApplicationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResearchApplicationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ResearchApplicationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResearchApplicationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResearchApplicationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := researchapplication.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResearchApplicationUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := researchapplication.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ResearchApplication.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ResearchApplicationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(researchapplication.Table, researchapplication.Columns, sqlgraph.NewFieldSpec(researchapplication.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(researchapplication.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(researchapplication.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(researchapplication.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(researchapplication.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(researchapplication.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReviewerID(); ok {
		_spec.SetField(researchapplication.FieldReviewerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReviewerID(); ok {
		_spec.AddField(researchapplication.FieldReviewerID, field.TypeInt64, value)
	}
	if _u.mutation.ReviewerIDCleared() {
		_spec.ClearField(researchapplication.FieldReviewerID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ReviewNotes(); ok {
		_spec.SetField(researchapplication.FieldReviewNotes, field.TypeString, value)
	}
	if _u.mutation.ReviewNotesCleared() {
		_spec.ClearField(researchapplication.FieldReviewNotes, field.TypeString)
	}
	if value, ok := _u.mutation.RewardAmount(); ok {
		_spec.SetField(researchapplication.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardAmount(); ok {
		_spec.AddField(researchapplication.FieldRewardAmount, field.TypeFloat64, value)
	}
	if _u.mutation.RewardAmountCleared() {
		_spec.ClearField(researchapplication.FieldRewardAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.IssuedRedeemCodeID(); ok {
		_spec.SetField(researchapplication.FieldIssuedRedeemCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedIssuedRedeemCodeID(); ok {
		_spec.AddField(researchapplication.FieldIssuedRedeemCodeID, field.TypeInt64, value)
	}
	if _u.mutation.IssuedRedeemCodeIDCleared() {
		_spec.ClearField(researchapplication.FieldIssuedRedeemCodeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(researchapplication.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(researchapplication.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Attachments(); ok {
		_spec.SetField(researchapplication.FieldAttachments, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAttachments(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, researchapplication.FieldAttachments, value)
		})
	}
	if _u.mutation.AttachmentsCleared() {
		_spec.ClearField(researchapplication.FieldAttachments, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{researchapplication.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ResearchApplicationUpdateOne is the builder for updating a single ResearchApplication entity.
type ResearchApplicationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ResearchApplicationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResearchApplicationUpdateOne) SetUpdatedAt(v time.Time) *ResearchApplicationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ResearchApplicationUpdateOne) SetUserID(v int64) *ResearchApplicationUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ResearchApplicationUpdateOne) SetNillableUserID(v *int64) *ResearchApplicationUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ResearchApplicationUpdateOne) AddUserID(v int64) *ResearchApplicationUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *ResearchApplicationUpdateOne) SetDescription(v string) *ResearchApplicationUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ResearchApplicationUpdateOne) SetNillableDescription(v *string) *ResearchApplicationUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ResearchApplicationUpdateOne) SetStatus(v string) *ResearchApplicationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ResearchApplicationUpdateOne) SetNillableStatus(v *string) *ResearchApplicationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetReviewerID sets the "reviewer_id" field.
func (_u *ResearchApplicationUpdateOne) SetReviewerID(v int64) *ResearchApplicationUpdateOne {
	_u.mutation.ResetReviewerID()
	_u.mutation.SetReviewerID(v)
	return _u
}

// SetNillableReviewerID sets the "reviewer_id" field if the given value is not nil.
func (_u *ResearchApplicationUpdateOne) SetNillableReviewerID(v *int64) *ResearchApplicationUpdateOne {
	if v != nil {
		_u.SetReviewerID(*v)
	}
	return _u
}

// AddReviewerID adds value to the "reviewer_id" field.
func (_u *ResearchApplicationUpdateOne) AddReviewerID(v int64) *ResearchApplicationUpdateOne {
	_u.mutation.AddReviewerID(v)
	return _u
}

// ClearReviewerID clears the value of the "reviewer_id" field.
func (_u *ResearchApplicationUpdateOne) ClearReviewerID() *ResearchApplicationUpdateOne {
	_u.mutation.ClearReviewerID()
	return _u
}

// SetReviewNotes sets the "review_notes" field.
func (_u *ResearchApplicationUpdateOne) SetReviewNotes(v string) *ResearchApplicationUpdateOne {
	_u.mutation.SetReviewNotes(v)
	return _u
}

// SetNillableReviewNotes sets the "review_notes" field if the given value is not nil.
func (_u *ResearchApplicationUpdateOne) SetNillableReviewNotes(v *string) *ResearchApplicationUpdateOne {
	if v != nil {
		_u.SetReviewNotes(*v)
	}
	return _u
}

// ClearReviewNotes clears the value of the "review_notes" field.
func (_u *ResearchApplicationUpdateOne) ClearReviewNotes() *ResearchApplicationUpdateOne {
	_u.mutation.ClearReviewNotes()
	return _u
}

// SetRewardAmount sets the "reward_amount" field.
func (_u *ResearchApplicationUpdateOne) SetRewardAmount(v float64) *ResearchApplicationUpdateOne {
	_u.mutation.ResetRewardAmount()
	_u.mutation.SetRewardAmount(v)
	return _u
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_u *ResearchApplicationUpdateOne) SetNillableRewardAmount(v *float64) *ResearchApplicationUpdateOne {
	if v != nil {
		_u.SetRewardAmount(*v)
	}
	return _u
}

// AddRewardAmount adds value to the "reward_amount" field.
func (_u *ResearchApplicationUpdateOne) AddRewardAmount(v float64) *ResearchApplicationUpdateOne {
	_u.mutation.AddRewardAmount(v)
	return _u
}

// ClearRewardAmount clears the value of the "reward_amount" field.
func (_u *ResearchApplicationUpdateOne) ClearRewardAmount() *ResearchApplicationUpdateOne {
	_u.mutation.ClearRewardAmount()
	return _u
}

// SetIssuedRedeemCodeID sets the "issued_redeem_code_id" field.
func (_u *ResearchApplicationUpdateOne) SetIssuedRedeemCodeID(v int64) *ResearchApplicationUpdateOne {
	_u.mutation.ResetIssuedRedeemCodeID()
	_u.mutation.SetIssuedRedeemCodeID(v)
	return _u
}

// SetNillableIssuedRedeemCodeID sets the "issued_redeem_code_id" field if the given value is not nil.
func (_u *ResearchApplicationUpdateOne) SetNillableIssuedRedeemCodeID(v *int64) *ResearchApplicationUpdateOne {
	if v != nil {
		_u.SetIssuedRedeemCodeID(*v)
	}
	return _u
}

// AddIssuedRedeemCodeID adds value to the "issued_redeem_code_id" field.
func (_u *ResearchApplicationUpdateOne) AddIssuedRedeemCodeID(v int64) *ResearchApplicationUpdateOne {
	_u.mutation.AddIssuedRedeemCodeID(v)
	return _u
}

// ClearIssuedRedeemCodeID clears the value of the "issued_redeem_code_id" field.
func (_u *ResearchApplicationUpdateOne) ClearIssuedRedeemCodeID() *ResearchApplicationUpdateOne {
	_u.mutation.ClearIssuedRedeemCodeID()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *ResearchApplicationUpdateOne) SetReviewedAt(v time.Time) *ResearchApplicationUpdateOne {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *ResearchApplicationUpdateOne) SetNillableReviewedAt(v *time.Time) *ResearchApplicationUpdateOne {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *ResearchApplicationUpdateOne) ClearReviewedAt() *ResearchApplicationUpdateOne {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetAttachments sets the "attachments" field.
func (_u *ResearchApplicationUpdateOne) SetAttachments(v []domain.ResearchAttachmentMeta) *ResearchApplicationUpdateOne {
	_u.mutation.SetAttachments(v)
	return _u
}

// AppendAttachments appends value to the "attachments" field.
func (_u *ResearchApplicationUpdateOne) AppendAttachments(v []domain.ResearchAttachmentMeta) *ResearchApplicationUpdateOne {
	_u.mutation.AppendAttachments(v)
	return _u
}

// ClearAttachments clears the value of the "attachments" field.
func (_u *ResearchApplicationUpdateOne) ClearAttachments() *ResearchApplicationUpdateOne {
	_u.mutation.ClearAttachments()
	return _u
}

// Mutation returns the ResearchApplicationMutation object of the builder.
func (_u *ResearchApplicationUpdateOne) Mutation() *ResearchApplicationMutation {
	return _u.mutation
}

// Where appends a list predicates to the ResearchApplicationUpdate builder.
func (_u *ResearchApplicationUpdateOne) Where(ps ...predicate.ResearchApplication) *ResearchApplicationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ResearchApplicationUpdateOne) Select(field string, fields ...string) *ResearchApplicationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ResearchApplication entity.
func (_u *ResearchApplicationUpdateOne) Save(ctx context.Context) (*ResearchApplication, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResearchApplicationUpdateOne) SaveX(ctx context.Context) *ResearchApplication {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ResearchApplicationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResearchApplicationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResearchApplicationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := researchapplication.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResearchApplicationUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := researchapplication.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ResearchApplication.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ResearchApplicationUpdateOne) sqlSave(ctx context.Context) (_node *ResearchApplication, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(researchapplication.Table, researchapplication.Columns, sqlgraph.NewFieldSpec(researchapplication.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ResearchApplication.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, researchapplication.FieldID)
		for _, f := range fields {
			if !researchapplication.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != researchapplication.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(researchapplication.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(researchapplication.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(researchapplication.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(researchapplication.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(researchapplication.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReviewerID(); ok {
		_spec.SetField(researchapplication.FieldReviewerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReviewerID(); ok {
		_spec.AddField(researchapplication.FieldReviewerID, field.TypeInt64, value)
	}
	if _u.mutation.ReviewerIDCleared() {
		_spec.ClearField(researchapplication.FieldReviewerID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ReviewNotes(); ok {
		_spec.SetField(researchapplication.FieldReviewNotes, field.TypeString, value)
	}
	if _u.mutation.ReviewNotesCleared() {
		_spec.ClearField(researchapplication.FieldReviewNotes, field.TypeString)
	}
	if value, ok := _u.mutation.RewardAmount(); ok {
		_spec.SetField(researchapplication.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardAmount(); ok {
		_spec.AddField(researchapplication.FieldRewardAmount, field.TypeFloat64, value)
	}
	if _u.mutation.RewardAmountCleared() {
		_spec.ClearField(researchapplication.FieldRewardAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.IssuedRedeemCodeID(); ok {
		_spec.SetField(researchapplication.FieldIssuedRedeemCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedIssuedRedeemCodeID(); ok {
		_spec.AddField(researchapplication.FieldIssuedRedeemCodeID, field.TypeInt64, value)
	}
	if _u.mutation.IssuedRedeemCodeIDCleared() {
		_spec.ClearField(researchapplication.FieldIssuedRedeemCodeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(researchapplication.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(researchapplication.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Attachments(); ok {
		_spec.SetField(researchapplication.FieldAttachments, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAttachments(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, researchapplication.FieldAttachments, value)
		})
	}
	if _u.mutation.AttachmentsCleared() {
		_spec.ClearField(researchapplication.FieldAttachments, field.TypeJSON)
	}
	_node = &ResearchApplication{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{researchapplication.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
