// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionresetcard"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionresetevent"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionResetCardUpdate is the builder for updating SubscriptionResetCard entities.
type SubscriptionResetCardUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionResetCardMutation
}

// Where appends a list predicates to the SubscriptionResetCardUpdate builder.
func (_u *SubscriptionResetCardUpdate) Where(ps ...predicate.SubscriptionResetCard) *SubscriptionResetCardUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionResetCardUpdate) SetUpdatedAt(v time.Time) *SubscriptionResetCardUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SubscriptionResetCardUpdate) SetDeletedAt(v time.Time) *SubscriptionResetCardUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SubscriptionResetCardUpdate) SetNillableDeletedAt(v *time.Time) *SubscriptionResetCardUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SubscriptionResetCardUpdate) ClearDeletedAt() *SubscriptionResetCardUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionResetCardUpdate) SetUserID(v int64) *SubscriptionResetCardUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionResetCardUpdate) SetNillableUserID(v *int64) *SubscriptionResetCardUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionResetCardUpdate) SetStatus(v string) *SubscriptionResetCardUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionResetCardUpdate) SetNillableStatus(v *string) *SubscriptionResetCardUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetScope sets the "scope" field.
func (_u *SubscriptionResetCardUpdate) SetScope(v string) *SubscriptionResetCardUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *SubscriptionResetCardUpdate) SetNillableScope(v *string) *SubscriptionResetCardUpdate {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *SubscriptionResetCardUpdate) SetSourceType(v string) *SubscriptionResetCardUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *SubscriptionResetCardUpdate) SetNillableSourceType(v *string) *SubscriptionResetCardUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetCampaign sets the "campaign" field.
func (_u *SubscriptionResetCardUpdate) SetCampaign(v string) *SubscriptionResetCardUpdate {
	_u.mutation.SetCampaign(v)
	return _u
}

// SetNillableCampaign sets the "campaign" field if the given value is not nil.
func (_u *SubscriptionResetCardUpdate) SetNillableCampaign(v *string) *SubscriptionResetCardUpdate {
	if v != nil {
		_u.SetCampaign(*v)
	}
	return _u
}

// ClearCampaign clears the value of the "campaign" field.
func (_u *SubscriptionResetCardUpdate) ClearCampaign() *SubscriptionResetCardUpdate {
	_u.mutation.ClearCampaign()
	return _u
}

// SetGrantEventID sets the "grant_event_id" field.
func (_u *SubscriptionResetCardUpdate) SetGrantEventID(v int64) *SubscriptionResetCardUpdate {
	_u.mutation.SetGrantEventID(v)
	return _u
}

// SetNillableGrantEventID sets the "grant_event_id" field if the given value is not nil.
func (_u *SubscriptionResetCardUpdate) SetNillableGrantEventID(v *int64) *SubscriptionResetCardUpdate {
	if v != nil {
		_u.SetGrantEventID(*v)
	}
	return _u
}

// ClearGrantEventID clears the value of the "grant_event_id" field.
func (_u *SubscriptionResetCardUpdate) ClearGrantEventID() *SubscriptionResetCardUpdate {
	_u.mutation.ClearGrantEventID()
	return _u
}

// SetGrantIndex sets the "grant_index" field.
func (_u *SubscriptionResetCardUpdate) SetGrantIndex(v int) *SubscriptionResetCardUpdate {
	_u.mutation.ResetGrantIndex()
	_u.mutation.SetGrantIndex(v)
	return _u
}

// SetNillableGrantIndex sets the "grant_index" field if the given value is not nil.
func (_u *SubscriptionResetCardUpdate) SetNillableGrantIndex(v *int) *SubscriptionResetCardUpdate {
	if v != nil {
		_u.SetGrantIndex(*v)
	}
	return _u
}

// AddGrantIndex adds value to the "grant_index" field.
func (_u *SubscriptionResetCardUpdate) AddGrantIndex(v int) *SubscriptionResetCardUpdate {
	_u.mutation.AddGrantIndex(v)
	return _u
}

// SetGrantedAt sets the "granted_at" field.
func (_u *SubscriptionResetCardUpdate) SetGrantedAt(v time.Time) *SubscriptionResetCardUpdate {
	_u.mutation.SetGrantedAt(v)
	return _u
}

// SetNillableGrantedAt sets the "granted_at" field if the given value is not nil.
func (_u *SubscriptionResetCardUpdate) SetNillableGrantedAt(v *time.Time) *SubscriptionResetCardUpdate {
	if v != nil {
		_u.SetGrantedAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SubscriptionResetCardUpdate) SetExpiresAt(v time.Time) *SubscriptionResetCardUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SubscriptionResetCardUpdate) SetNillableExpiresAt(v *time.Time) *SubscriptionResetCardUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *SubscriptionResetCardUpdate) ClearExpiresAt() *SubscriptionResetCardUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *SubscriptionResetCardUpdate) SetUsedAt(v time.Time) *SubscriptionResetCardUpdate {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *SubscriptionResetCardUpdate) SetNillableUsedAt(v *time.Time) *SubscriptionResetCardUpdate {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// ClearUsedAt clears the value of the "used_at" field.
func (_u *SubscriptionResetCardUpdate) ClearUsedAt() *SubscriptionResetCardUpdate {
	_u.mutation.ClearUsedAt()
	return _u
}

// SetUsedSubscriptionID sets the "used_subscription_id" field.
func (_u *SubscriptionResetCardUpdate) SetUsedSubscriptionID(v int64) *SubscriptionResetCardUpdate {
	_u.mutation.SetUsedSubscriptionID(v)
	return _u
}

// SetNillableUsedSubscriptionID sets the "used_subscription_id" field if the given value is not nil.
func (_u *SubscriptionResetCardUpdate) SetNillableUsedSubscriptionID(v *int64) *SubscriptionResetCardUpdate {
	if v != nil {
		_u.SetUsedSubscriptionID(*v)
	}
	return _u
}

// ClearUsedSubscriptionID clears the value of the "used_subscription_id" field.
func (_u *SubscriptionResetCardUpdate) ClearUsedSubscriptionID() *SubscriptionResetCardUpdate {
	_u.mutation.ClearUsedSubscriptionID()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *SubscriptionResetCardUpdate) SetCreatedBy(v int64) *SubscriptionResetCardUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *SubscriptionResetCardUpdate) SetNillableCreatedBy(v *int64) *SubscriptionResetCardUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *SubscriptionResetCardUpdate) ClearCreatedBy() *SubscriptionResetCardUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *SubscriptionResetCardUpdate) SetNotes(v string) *SubscriptionResetCardUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *SubscriptionResetCardUpdate) SetNillableNotes(v *string) *SubscriptionResetCardUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *SubscriptionResetCardUpdate) SetMetadata(v map[string]interface{}) *SubscriptionResetCardUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SubscriptionResetCardUpdate) SetUser(v *User) *SubscriptionResetCardUpdate {
	return _u.SetUserID(v.ID)
}

// SetCreatedByUserID sets the "created_by_user" edge to the User entity by ID.
func (_u *SubscriptionResetCardUpdate) SetCreatedByUserID(id int64) *SubscriptionResetCardUpdate {
	_u.mutation.SetCreatedByUserID(id)
	return _u
}

// SetNillableCreatedByUserID sets the "created_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *SubscriptionResetCardUpdate) SetNillableCreatedByUserID(id *int64) *SubscriptionResetCardUpdate {
	if id != nil {
		_u = _u.SetCreatedByUserID(*id)
	}
	return _u
}

// SetCreatedByUser sets the "created_by_user" edge to the User entity.
func (_u *SubscriptionResetCardUpdate) SetCreatedByUser(v *User) *SubscriptionResetCardUpdate {
	return _u.SetCreatedByUserID(v.ID)
}

// SetUsedSubscription sets the "used_subscription" edge to the UserSubscription entity.
func (_u *SubscriptionResetCardUpdate) SetUsedSubscription(v *UserSubscription) *SubscriptionResetCardUpdate {
	return _u.SetUsedSubscriptionID(v.ID)
}

// SetGrantEvent sets the "grant_event" edge to the SubscriptionResetEvent entity.
func (_u *SubscriptionResetCardUpdate) SetGrantEvent(v *SubscriptionResetEvent) *SubscriptionResetCardUpdate {
	return _u.SetGrantEventID(v.ID)
}

// Mutation returns the SubscriptionResetCardMutation object of the builder.
func (_u *SubscriptionResetCardUpdate) Mutation() *SubscriptionResetCardMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SubscriptionResetCardUpdate) ClearUser() *SubscriptionResetCardUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearCreatedByUser clears the "created_by_user" edge to the User entity.
func (_u *SubscriptionResetCardUpdate) ClearCreatedByUser() *SubscriptionResetCardUpdate {
	_u.mutation.ClearCreatedByUser()
	return _u
}

// ClearUsedSubscription clears the "used_subscription" edge to the UserSubscription entity.
func (_u *SubscriptionResetCardUpdate) ClearUsedSubscription() *SubscriptionResetCardUpdate {
	_u.mutation.ClearUsedSubscription()
	return _u
}

// ClearGrantEvent clears the "grant_event" edge to the SubscriptionResetEvent entity.
func (_u *SubscriptionResetCardUpdate) ClearGrantEvent() *SubscriptionResetCardUpdate {
	_u.mutation.ClearGrantEvent()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionResetCardUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionResetCardUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionResetCardUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionResetCardUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionResetCardUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if subscriptionresetcard.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized subscriptionresetcard.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := subscriptionresetcard.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionResetCardUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := subscriptionresetcard.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetCard.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scope(); ok {
		if err := subscriptionresetcard.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetCard.scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := subscriptionresetcard.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetCard.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Campaign(); ok {
		if err := subscriptionresetcard.CampaignValidator(v); err != nil {
			return &ValidationError{Name: "campaign", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetCard.campaign": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionResetCard.user"`)
	}
	return nil
}

func (_u *SubscriptionResetCardUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionresetcard.Table, subscriptionresetcard.Columns, sqlgraph.NewFieldSpec(subscriptionresetcard.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionresetcard.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(subscriptionresetcard.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(subscriptionresetcard.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionresetcard.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(subscriptionresetcard.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(subscriptionresetcard.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Campaign(); ok {
		_spec.SetField(subscriptionresetcard.FieldCampaign, field.TypeString, value)
	}
	if _u.mutation.CampaignCleared() {
		_spec.ClearField(subscriptionresetcard.FieldCampaign, field.TypeString)
	}
	if value, ok := _u.mutation.GrantIndex(); ok {
		_spec.SetField(subscriptionresetcard.FieldGrantIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGrantIndex(); ok {
		_spec.AddField(subscriptionresetcard.FieldGrantIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GrantedAt(); ok {
		_spec.SetField(subscriptionresetcard.FieldGrantedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(subscriptionresetcard.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(subscriptionresetcard.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(subscriptionresetcard.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.UsedAtCleared() {
		_spec.ClearField(subscriptionresetcard.FieldUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(subscriptionresetcard.FieldNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(subscriptionresetcard.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcard.UserTable,
			Columns: []string{subscriptionresetcard.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcard.UserTable,
			Columns: []string{subscriptionresetcard.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcard.CreatedByUserTable,
			Columns: []string{subscriptionresetcard.CreatedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcard.CreatedByUserTable,
			Columns: []string{subscriptionresetcard.CreatedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsedSubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcard.UsedSubscriptionTable,
			Columns: []string{subscriptionresetcard.UsedSubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsedSubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcard.UsedSubscriptionTable,
			Columns: []string{subscriptionresetcard.UsedSubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GrantEventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcard.GrantEventTable,
			Columns: []string{subscriptionresetcard.GrantEventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionresetevent.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GrantEventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcard.GrantEventTable,
			Columns: []string{subscriptionresetcard.GrantEventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionresetevent.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionresetcard.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionResetCardUpdateOne is the builder for updating a single SubscriptionResetCard entity.
type SubscriptionResetCardUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionResetCardMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionResetCardUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionResetCardUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SubscriptionResetCardUpdateOne) SetDeletedAt(v time.Time) *SubscriptionResetCardUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SubscriptionResetCardUpdateOne) SetNillableDeletedAt(v *time.Time) *SubscriptionResetCardUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SubscriptionResetCardUpdateOne) ClearDeletedAt() *SubscriptionResetCardUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionResetCardUpdateOne) SetUserID(v int64) *SubscriptionResetCardUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionResetCardUpdateOne) SetNillableUserID(v *int64) *SubscriptionResetCardUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionResetCardUpdateOne) SetStatus(v string) *SubscriptionResetCardUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionResetCardUpdateOne) SetNillableStatus(v *string) *SubscriptionResetCardUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetScope sets the "scope" field.
func (_u *SubscriptionResetCardUpdateOne) SetScope(v string) *SubscriptionResetCardUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *SubscriptionResetCardUpdateOne) SetNillableScope(v *string) *SubscriptionResetCardUpdateOne {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *SubscriptionResetCardUpdateOne) SetSourceType(v string) *SubscriptionResetCardUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *SubscriptionResetCardUpdateOne) SetNillableSourceType(v *string) *SubscriptionResetCardUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetCampaign sets the "campaign" field.
func (_u *SubscriptionResetCardUpdateOne) SetCampaign(v string) *SubscriptionResetCardUpdateOne {
	_u.mutation.SetCampaign(v)
	return _u
}

// SetNillableCampaign sets the "campaign" field if the given value is not nil.
func (_u *SubscriptionResetCardUpdateOne) SetNillableCampaign(v *string) *SubscriptionResetCardUpdateOne {
	if v != nil {
		_u.SetCampaign(*v)
	}
	return _u
}

// ClearCampaign clears the value of the "campaign" field.
func (_u *SubscriptionResetCardUpdateOne) ClearCampaign() *SubscriptionResetCardUpdateOne {
	_u.mutation.ClearCampaign()
	return _u
}

// SetGrantEventID sets the "grant_event_id" field.
func (_u *SubscriptionResetCardUpdateOne) SetGrantEventID(v int64) *SubscriptionResetCardUpdateOne {
	_u.mutation.SetGrantEventID(v)
	return _u
}

// SetNillableGrantEventID sets the "grant_event_id" field if the given value is not nil.
func (_u *SubscriptionResetCardUpdateOne) SetNillableGrantEventID(v *int64) *SubscriptionResetCardUpdateOne {
	if v != nil {
		_u.SetGrantEventID(*v)
	}
	return _u
}

// ClearGrantEventID clears the value of the "grant_event_id" field.
func (_u *SubscriptionResetCardUpdateOne) ClearGrantEventID() *SubscriptionResetCardUpdateOne {
	_u.mutation.ClearGrantEventID()
	return _u
}

// SetGrantIndex sets the "grant_index" field.
func (_u *SubscriptionResetCardUpdateOne) SetGrantIndex(v int) *SubscriptionResetCardUpdateOne {
	_u.mutation.ResetGrantIndex()
	_u.mutation.SetGrantIndex(v)
	return _u
}

// SetNillableGrantIndex sets the "grant_index" field if the given value is not nil.
func (_u *SubscriptionResetCardUpdateOne) SetNillableGrantIndex(v *int) *SubscriptionResetCardUpdateOne {
	if v != nil {
		_u.SetGrantIndex(*v)
	}
	return _u
}

// AddGrantIndex adds value to the "grant_index" field.
func (_u *SubscriptionResetCardUpdateOne) AddGrantIndex(v int) *SubscriptionResetCardUpdateOne {
	_u.mutation.AddGrantIndex(v)
	return _u
}

// SetGrantedAt sets the "granted_at" field.
func (_u *SubscriptionResetCardUpdateOne) SetGrantedAt(v time.Time) *SubscriptionResetCardUpdateOne {
	_u.mutation.SetGrantedAt(v)
	return _u
}

// SetNillableGrantedAt sets the "granted_at" field if the given value is not nil.
func (_u *SubscriptionResetCardUpdateOne) SetNillableGrantedAt(v *time.Time) *SubscriptionResetCardUpdateOne {
	if v != nil {
		_u.SetGrantedAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SubscriptionResetCardUpdateOne) SetExpiresAt(v time.Time) *SubscriptionResetCardUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SubscriptionResetCardUpdateOne) SetNillableExpiresAt(v *time.Time) *SubscriptionResetCardUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *SubscriptionResetCardUpdateOne) ClearExpiresAt() *SubscriptionResetCardUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *SubscriptionResetCardUpdateOne) SetUsedAt(v time.Time) *SubscriptionResetCardUpdateOne {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *SubscriptionResetCardUpdateOne) SetNillableUsedAt(v *time.Time) *SubscriptionResetCardUpdateOne {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// ClearUsedAt clears the value of the "used_at" field.
func (_u *SubscriptionResetCardUpdateOne) ClearUsedAt() *SubscriptionResetCardUpdateOne {
	_u.mutation.ClearUsedAt()
	return _u
}

// SetUsedSubscriptionID sets the "used_subscription_id" field.
func (_u *SubscriptionResetCardUpdateOne) SetUsedSubscriptionID(v int64) *SubscriptionResetCardUpdateOne {
	_u.mutation.SetUsedSubscriptionID(v)
	return _u
}

// SetNillableUsedSubscriptionID sets the "used_subscription_id" field if the given value is not nil.
func (_u *SubscriptionResetCardUpdateOne) SetNillableUsedSubscriptionID(v *int64) *SubscriptionResetCardUpdateOne {
	if v != nil {
		_u.SetUsedSubscriptionID(*v)
	}
	return _u
}

// ClearUsedSubscriptionID clears the value of the "used_subscription_id" field.
func (_u *SubscriptionResetCardUpdateOne) ClearUsedSubscriptionID() *SubscriptionResetCardUpdateOne {
	_u.mutation.ClearUsedSubscriptionID()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *SubscriptionResetCardUpdateOne) SetCreatedBy(v int64) *SubscriptionResetCardUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *SubscriptionResetCardUpdateOne) SetNillableCreatedBy(v *int64) *SubscriptionResetCardUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *SubscriptionResetCardUpdateOne) ClearCreatedBy() *SubscriptionResetCardUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *SubscriptionResetCardUpdateOne) SetNotes(v string) *SubscriptionResetCardUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *SubscriptionResetCardUpdateOne) SetNillableNotes(v *string) *SubscriptionResetCardUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *SubscriptionResetCardUpdateOne) SetMetadata(v map[string]interface{}) *SubscriptionResetCardUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SubscriptionResetCardUpdateOne) SetUser(v *User) *SubscriptionResetCardUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetCreatedByUserID sets the "created_by_user" edge to the User entity by ID.
func (_u *SubscriptionResetCardUpdateOne) SetCreatedByUserID(id int64) *SubscriptionResetCardUpdateOne {
	_u.mutation.SetCreatedByUserID(id)
	return _u
}

// SetNillableCreatedByUserID sets the "created_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *SubscriptionResetCardUpdateOne) SetNillableCreatedByUserID(id *int64) *SubscriptionResetCardUpdateOne {
	if id != nil {
		_u = _u.SetCreatedByUserID(*id)
	}
	return _u
}

// SetCreatedByUser sets the "created_by_user" edge to the User entity.
func (_u *SubscriptionResetCardUpdateOne) SetCreatedByUser(v *User) *SubscriptionResetCardUpdateOne {
	return _u.SetCreatedByUserID(v.ID)
}

// SetUsedSubscription sets the "used_subscription" edge to the UserSubscription entity.
func (_u *SubscriptionResetCardUpdateOne) SetUsedSubscription(v *UserSubscription) *SubscriptionResetCardUpdateOne {
	return _u.SetUsedSubscriptionID(v.ID)
}

// SetGrantEvent sets the "grant_event" edge to the SubscriptionResetEvent entity.
func (_u *SubscriptionResetCardUpdateOne) SetGrantEvent(v *SubscriptionResetEvent) *SubscriptionResetCardUpdateOne {
	return _u.SetGrantEventID(v.ID)
}

// Mutation returns the SubscriptionResetCardMutation object of the builder.
func (_u *SubscriptionResetCardUpdateOne) Mutation() *SubscriptionResetCardMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SubscriptionResetCardUpdateOne) ClearUser() *SubscriptionResetCardUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearCreatedByUser clears the "created_by_user" edge to the User entity.
func (_u *SubscriptionResetCardUpdateOne) ClearCreatedByUser() *SubscriptionResetCardUpdateOne {
	_u.mutation.ClearCreatedByUser()
	return _u
}

// ClearUsedSubscription clears the "used_subscription" edge to the UserSubscription entity.
func (_u *SubscriptionResetCardUpdateOne) ClearUsedSubscription() *SubscriptionResetCardUpdateOne {
	_u.mutation.ClearUsedSubscription()
	return _u
}

// ClearGrantEvent clears the "grant_event" edge to the SubscriptionResetEvent entity.
func (_u *SubscriptionResetCardUpdateOne) ClearGrantEvent() *SubscriptionResetCardUpdateOne {
	_u.mutation.ClearGrantEvent()
	return _u
}

// Where appends a list predicates to the SubscriptionResetCardUpdate builder.
func (_u *SubscriptionResetCardUpdateOne) Where(ps ...predicate.SubscriptionResetCard) *SubscriptionResetCardUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionResetCardUpdateOne) Select(field string, fields ...string) *SubscriptionResetCardUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionResetCard entity.
func (_u *SubscriptionResetCardUpdateOne) Save(ctx context.Context) (*SubscriptionResetCard, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionResetCardUpdateOne) SaveX(ctx context.Context) *SubscriptionResetCard {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionResetCardUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionResetCardUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionResetCardUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if subscriptionresetcard.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized subscriptionresetcard.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := subscriptionresetcard.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionResetCardUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := subscriptionresetcard.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetCard.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scope(); ok {
		if err := subscriptionresetcard.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetCard.scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := subscriptionresetcard.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetCard.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Campaign(); ok {
		if err := subscriptionresetcard.CampaignValidator(v); err != nil {
			return &ValidationError{Name: "campaign", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetCard.campaign": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionResetCard.user"`)
	}
	return nil
}

func (_u *SubscriptionResetCardUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionResetCard, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionresetcard.Table, subscriptionresetcard.Columns, sqlgraph.NewFieldSpec(subscriptionresetcard.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionResetCard.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionresetcard.FieldID)
		for _, f := range fields {
			if !subscriptionresetcard.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionresetcard.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionresetcard.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(subscriptionresetcard.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(subscriptionresetcard.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionresetcard.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(subscriptionresetcard.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(subscriptionresetcard.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Campaign(); ok {
		_spec.SetField(subscriptionresetcard.FieldCampaign, field.TypeString, value)
	}
	if _u.mutation.CampaignCleared() {
		_spec.ClearField(subscriptionresetcard.FieldCampaign, field.TypeString)
	}
	if value, ok := _u.mutation.GrantIndex(); ok {
		_spec.SetField(subscriptionresetcard.FieldGrantIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGrantIndex(); ok {
		_spec.AddField(subscriptionresetcard.FieldGrantIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GrantedAt(); ok {
		_spec.SetField(subscriptionresetcard.FieldGrantedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(subscriptionresetcard.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(subscriptionresetcard.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(subscriptionresetcard.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.UsedAtCleared() {
		_spec.ClearField(subscriptionresetcard.FieldUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(subscriptionresetcard.FieldNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(subscriptionresetcard.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcard.UserTable,
			Columns: []string{subscriptionresetcard.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcard.UserTable,
			Columns: []string{subscriptionresetcard.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcard.CreatedByUserTable,
			Columns: []string{subscriptionresetcard.CreatedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcard.CreatedByUserTable,
			Columns: []string{subscriptionresetcard.CreatedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsedSubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcard.UsedSubscriptionTable,
			Columns: []string{subscriptionresetcard.UsedSubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsedSubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcard.UsedSubscriptionTable,
			Columns: []string{subscriptionresetcard.UsedSubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GrantEventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcard.GrantEventTable,
			Columns: []string{subscriptionresetcard.GrantEventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionresetevent.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GrantEventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetcard.GrantEventTable,
			Columns: []string{subscriptionresetcard.GrantEventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionresetevent.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubscriptionResetCard{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionresetcard.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
