// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplanchange"
)

// SubscriptionPlanChange is the model entity for the SubscriptionPlanChange schema.
type SubscriptionPlanChange struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// SubscriptionID holds the value of the "subscription_id" field.
	SubscriptionID int64 `json:"subscription_id,omitempty"`
	// ChangeType holds the value of the "change_type" field.
	ChangeType string `json:"change_type,omitempty"`
	// FromPlanID holds the value of the "from_plan_id" field.
	FromPlanID *int64 `json:"from_plan_id,omitempty"`
	// ToPlanID holds the value of the "to_plan_id" field.
	ToPlanID int64 `json:"to_plan_id,omitempty"`
	// FromGroupID holds the value of the "from_group_id" field.
	FromGroupID *int64 `json:"from_group_id,omitempty"`
	// ToGroupID holds the value of the "to_group_id" field.
	ToGroupID int64 `json:"to_group_id,omitempty"`
	// FromTier holds the value of the "from_tier" field.
	FromTier int `json:"from_tier,omitempty"`
	// ToTier holds the value of the "to_tier" field.
	ToTier int `json:"to_tier,omitempty"`
	// OldPriceSnapshot holds the value of the "old_price_snapshot" field.
	OldPriceSnapshot *float64 `json:"old_price_snapshot,omitempty"`
	// NewPriceSnapshot holds the value of the "new_price_snapshot" field.
	NewPriceSnapshot float64 `json:"new_price_snapshot,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// TermStart holds the value of the "term_start" field.
	TermStart *time.Time `json:"term_start,omitempty"`
	// TermEnd holds the value of the "term_end" field.
	TermEnd *time.Time `json:"term_end,omitempty"`
	// RemainingSeconds holds the value of the "remaining_seconds" field.
	RemainingSeconds int64 `json:"remaining_seconds,omitempty"`
	// UnusedCredit holds the value of the "unused_credit" field.
	UnusedCredit float64 `json:"unused_credit,omitempty"`
	// ProratedCharge holds the value of the "prorated_charge" field.
	ProratedCharge float64 `json:"prorated_charge,omitempty"`
	// AmountDue holds the value of the "amount_due" field.
	AmountDue float64 `json:"amount_due,omitempty"`
	// QuoteCreatedAt holds the value of the "quote_created_at" field.
	QuoteCreatedAt *time.Time `json:"quote_created_at,omitempty"`
	// QuoteExpiresAt holds the value of the "quote_expires_at" field.
	QuoteExpiresAt *time.Time `json:"quote_expires_at,omitempty"`
	// EffectiveAt holds the value of the "effective_at" field.
	EffectiveAt *time.Time `json:"effective_at,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CancelReason holds the value of the "cancel_reason" field.
	CancelReason *string `json:"cancel_reason,omitempty"`
	// OrderID holds the value of the "order_id" field.
	OrderID *int64 `json:"order_id,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// PaidAt holds the value of the "paid_at" field.
	PaidAt *time.Time `json:"paid_at,omitempty"`
	// FulfilledAt holds the value of the "fulfilled_at" field.
	FulfilledAt *time.Time `json:"fulfilled_at,omitempty"`
	// CancelledAt holds the value of the "cancelled_at" field.
	CancelledAt  *time.Time `json:"cancelled_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubscriptionPlanChange) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscriptionplanchange.FieldMetadata:
			values[i] = new([]byte)
		case subscriptionplanchange.FieldOldPriceSnapshot, subscriptionplanchange.FieldNewPriceSnapshot, subscriptionplanchange.FieldUnusedCredit, subscriptionplanchange.FieldProratedCharge, subscriptionplanchange.FieldAmountDue:
			values[i] = new(sql.NullFloat64)
		case subscriptionplanchange.FieldID, subscriptionplanchange.FieldUserID, subscriptionplanchange.FieldSubscriptionID, subscriptionplanchange.FieldFromPlanID, subscriptionplanchange.FieldToPlanID, subscriptionplanchange.FieldFromGroupID, subscriptionplanchange.FieldToGroupID, subscriptionplanchange.FieldFromTier, subscriptionplanchange.FieldToTier, subscriptionplanchange.FieldRemainingSeconds, subscriptionplanchange.FieldOrderID:
			values[i] = new(sql.NullInt64)
		case subscriptionplanchange.FieldChangeType, subscriptionplanchange.FieldCurrency, subscriptionplanchange.FieldStatus, subscriptionplanchange.FieldCancelReason, subscriptionplanchange.FieldIdempotencyKey:
			values[i] = new(sql.NullString)
		case subscriptionplanchange.FieldCreatedAt, subscriptionplanchange.FieldUpdatedAt, subscriptionplanchange.FieldDeletedAt, subscriptionplanchange.FieldTermStart, subscriptionplanchange.FieldTermEnd, subscriptionplanchange.FieldQuoteCreatedAt, subscriptionplanchange.FieldQuoteExpiresAt, subscriptionplanchange.FieldEffectiveAt, subscriptionplanchange.FieldPaidAt, subscriptionplanchange.FieldFulfilledAt, subscriptionplanchange.FieldCancelledAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubscriptionPlanChange fields.
func (_m *SubscriptionPlanChange) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscriptionplanchange.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case subscriptionplanchange.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case subscriptionplanchange.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case subscriptionplanchange.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case subscriptionplanchange.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case subscriptionplanchange.FieldSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_id", values[i])
			} else if value.Valid {
				_m.SubscriptionID = value.Int64
			}
		case subscriptionplanchange.FieldChangeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field change_type", values[i])
			} else if value.Valid {
				_m.ChangeType = value.String
			}
		case subscriptionplanchange.FieldFromPlanID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field from_plan_id", values[i])
			} else if value.Valid {
				_m.FromPlanID = new(int64)
				*_m.FromPlanID = value.Int64
			}
		case subscriptionplanchange.FieldToPlanID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field to_plan_id", values[i])
			} else if value.Valid {
				_m.ToPlanID = value.Int64
			}
		case subscriptionplanchange.FieldFromGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field from_group_id", values[i])
			} else if value.Valid {
				_m.FromGroupID = new(int64)
				*_m.FromGroupID = value.Int64
			}
		case subscriptionplanchange.FieldToGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field to_group_id", values[i])
			} else if value.Valid {
				_m.ToGroupID = value.Int64
			}
		case subscriptionplanchange.FieldFromTier:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field from_tier", values[i])
			} else if value.Valid {
				_m.FromTier = int(value.Int64)
			}
		case subscriptionplanchange.FieldToTier:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field to_tier", values[i])
			} else if value.Valid {
				_m.ToTier = int(value.Int64)
			}
		case subscriptionplanchange.FieldOldPriceSnapshot:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field old_price_snapshot", values[i])
			} else if value.Valid {
				_m.OldPriceSnapshot = new(float64)
				*_m.OldPriceSnapshot = value.Float64
			}
		case subscriptionplanchange.FieldNewPriceSnapshot:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field new_price_snapshot", values[i])
			} else if value.Valid {
				_m.NewPriceSnapshot = value.Float64
			}
		case subscriptionplanchange.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case subscriptionplanchange.FieldTermStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field term_start", values[i])
			} else if value.Valid {
				_m.TermStart = new(time.Time)
				*_m.TermStart = value.Time
			}
		case subscriptionplanchange.FieldTermEnd:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field term_end", values[i])
			} else if value.Valid {
				_m.TermEnd = new(time.Time)
				*_m.TermEnd = value.Time
			}
		case subscriptionplanchange.FieldRemainingSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field remaining_seconds", values[i])
			} else if value.Valid {
				_m.RemainingSeconds = value.Int64
			}
		case subscriptionplanchange.FieldUnusedCredit:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field unused_credit", values[i])
			} else if value.Valid {
				_m.UnusedCredit = value.Float64
			}
		case subscriptionplanchange.FieldProratedCharge:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field prorated_charge", values[i])
			} else if value.Valid {
				_m.ProratedCharge = value.Float64
			}
		case subscriptionplanchange.FieldAmountDue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_due", values[i])
			} else if value.Valid {
				_m.AmountDue = value.Float64
			}
		case subscriptionplanchange.FieldQuoteCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field quote_created_at", values[i])
			} else if value.Valid {
				_m.QuoteCreatedAt = new(time.Time)
				*_m.QuoteCreatedAt = value.Time
			}
		case subscriptionplanchange.FieldQuoteExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field quote_expires_at", values[i])
			} else if value.Valid {
				_m.QuoteExpiresAt = new(time.Time)
				*_m.QuoteExpiresAt = value.Time
			}
		case subscriptionplanchange.FieldEffectiveAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field effective_at", values[i])
			} else if value.Valid {
				_m.EffectiveAt = new(time.Time)
				*_m.EffectiveAt = value.Time
			}
		case subscriptionplanchange.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case subscriptionplanchange.FieldCancelReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cancel_reason", values[i])
			} else if value.Valid {
				_m.CancelReason = new(string)
				*_m.CancelReason = value.String
			}
		case subscriptionplanchange.FieldOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_id", values[i])
			} else if value.Valid {
				_m.OrderID = new(int64)
				*_m.OrderID = value.Int64
			}
		case subscriptionplanchange.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				_m.IdempotencyKey = new(string)
				*_m.IdempotencyKey = value.String
			}
		case subscriptionplanchange.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case subscriptionplanchange.FieldPaidAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field paid_at", values[i])
			} else if value.Valid {
				_m.PaidAt = new(time.Time)
				*_m.PaidAt = value.Time
			}
		case subscriptionplanchange.FieldFulfilledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field fulfilled_at", values[i])
			} else if value.Valid {
				_m.FulfilledAt = new(time.Time)
				*_m.FulfilledAt = value.Time
			}
		case subscriptionplanchange.FieldCancelledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field cancelled_at", values[i])
			} else if value.Valid {
				_m.CancelledAt = new(time.Time)
				*_m.CancelledAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubscriptionPlanChange.
// This includes values selected through modifiers, order, etc.
func (_m *SubscriptionPlanChange) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SubscriptionPlanChange.
// Note that you need to call SubscriptionPlanChange.Unwrap() before calling this method if this SubscriptionPlanChange
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SubscriptionPlanChange) Update() *SubscriptionPlanChangeUpdateOne {
	return NewSubscriptionPlanChangeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SubscriptionPlanChange entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SubscriptionPlanChange) Unwrap() *SubscriptionPlanChange {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubscriptionPlanChange is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SubscriptionPlanChange) String() string {
	var builder strings.Builder
	builder.WriteString("SubscriptionPlanChange(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("subscription_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubscriptionID))
	builder.WriteString(", ")
	builder.WriteString("change_type=")
	builder.WriteString(_m.ChangeType)
	builder.WriteString(", ")
	if v := _m.FromPlanID; v != nil {
		builder.WriteString("from_plan_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("to_plan_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ToPlanID))
	builder.WriteString(", ")
	if v := _m.FromGroupID; v != nil {
		builder.WriteString("from_group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("to_group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ToGroupID))
	builder.WriteString(", ")
	builder.WriteString("from_tier=")
	builder.WriteString(fmt.Sprintf("%v", _m.FromTier))
	builder.WriteString(", ")
	builder.WriteString("to_tier=")
	builder.WriteString(fmt.Sprintf("%v", _m.ToTier))
	builder.WriteString(", ")
	if v := _m.OldPriceSnapshot; v != nil {
		builder.WriteString("old_price_snapshot=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("new_price_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.NewPriceSnapshot))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	if v := _m.TermStart; v != nil {
		builder.WriteString("term_start=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.TermEnd; v != nil {
		builder.WriteString("term_end=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("remaining_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.RemainingSeconds))
	builder.WriteString(", ")
	builder.WriteString("unused_credit=")
	builder.WriteString(fmt.Sprintf("%v", _m.UnusedCredit))
	builder.WriteString(", ")
	builder.WriteString("prorated_charge=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProratedCharge))
	builder.WriteString(", ")
	builder.WriteString("amount_due=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountDue))
	builder.WriteString(", ")
	if v := _m.QuoteCreatedAt; v != nil {
		builder.WriteString("quote_created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.QuoteExpiresAt; v != nil {
		builder.WriteString("quote_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.EffectiveAt; v != nil {
		builder.WriteString("effective_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.CancelReason; v != nil {
		builder.WriteString("cancel_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OrderID; v != nil {
		builder.WriteString("order_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.IdempotencyKey; v != nil {
		builder.WriteString("idempotency_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	if v := _m.PaidAt; v != nil {
		builder.WriteString("paid_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FulfilledAt; v != nil {
		builder.WriteString("fulfilled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CancelledAt; v != nil {
		builder.WriteString("cancelled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// SubscriptionPlanChanges is a parsable slice of SubscriptionPlanChange.
type SubscriptionPlanChanges []*SubscriptionPlanChange
