// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionresetcard"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionresetevent"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionResetCard is the model entity for the SubscriptionResetCard schema.
type SubscriptionResetCard struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Scope holds the value of the "scope" field.
	Scope string `json:"scope,omitempty"`
	// SourceType holds the value of the "source_type" field.
	SourceType string `json:"source_type,omitempty"`
	// Campaign holds the value of the "campaign" field.
	Campaign *string `json:"campaign,omitempty"`
	// GrantEventID holds the value of the "grant_event_id" field.
	GrantEventID *int64 `json:"grant_event_id,omitempty"`
	// GrantIndex holds the value of the "grant_index" field.
	GrantIndex int `json:"grant_index,omitempty"`
	// GrantedAt holds the value of the "granted_at" field.
	GrantedAt time.Time `json:"granted_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// UsedAt holds the value of the "used_at" field.
	UsedAt *time.Time `json:"used_at,omitempty"`
	// UsedSubscriptionID holds the value of the "used_subscription_id" field.
	UsedSubscriptionID *int64 `json:"used_subscription_id,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy *int64 `json:"created_by,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes string `json:"notes,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubscriptionResetCardQuery when eager-loading is set.
	Edges        SubscriptionResetCardEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SubscriptionResetCardEdges holds the relations/edges for other nodes in the graph.
type SubscriptionResetCardEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// CreatedByUser holds the value of the created_by_user edge.
	CreatedByUser *User `json:"created_by_user,omitempty"`
	// UsedSubscription holds the value of the used_subscription edge.
	UsedSubscription *UserSubscription `json:"used_subscription,omitempty"`
	// GrantEvent holds the value of the grant_event edge.
	GrantEvent *SubscriptionResetEvent `json:"grant_event,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionResetCardEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// CreatedByUserOrErr returns the CreatedByUser value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionResetCardEdges) CreatedByUserOrErr() (*User, error) {
	if e.CreatedByUser != nil {
		return e.CreatedByUser, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "created_by_user"}
}

// UsedSubscriptionOrErr returns the UsedSubscription value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionResetCardEdges) UsedSubscriptionOrErr() (*UserSubscription, error) {
	if e.UsedSubscription != nil {
		return e.UsedSubscription, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: usersubscription.Label}
	}
	return nil, &NotLoadedError{edge: "used_subscription"}
}

// GrantEventOrErr returns the GrantEvent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionResetCardEdges) GrantEventOrErr() (*SubscriptionResetEvent, error) {
	if e.GrantEvent != nil {
		return e.GrantEvent, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: subscriptionresetevent.Label}
	}
	return nil, &NotLoadedError{edge: "grant_event"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubscriptionResetCard) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscriptionresetcard.FieldMetadata:
			values[i] = new([]byte)
		case subscriptionresetcard.FieldID, subscriptionresetcard.FieldUserID, subscriptionresetcard.FieldGrantEventID, subscriptionresetcard.FieldGrantIndex, subscriptionresetcard.FieldUsedSubscriptionID, subscriptionresetcard.FieldCreatedBy:
			values[i] = new(sql.NullInt64)
		case subscriptionresetcard.FieldStatus, subscriptionresetcard.FieldScope, subscriptionresetcard.FieldSourceType, subscriptionresetcard.FieldCampaign, subscriptionresetcard.FieldNotes:
			values[i] = new(sql.NullString)
		case subscriptionresetcard.FieldCreatedAt, subscriptionresetcard.FieldUpdatedAt, subscriptionresetcard.FieldDeletedAt, subscriptionresetcard.FieldGrantedAt, subscriptionresetcard.FieldExpiresAt, subscriptionresetcard.FieldUsedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubscriptionResetCard fields.
func (_m *SubscriptionResetCard) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscriptionresetcard.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case subscriptionresetcard.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case subscriptionresetcard.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case subscriptionresetcard.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case subscriptionresetcard.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case subscriptionresetcard.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case subscriptionresetcard.FieldScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope", values[i])
			} else if value.Valid {
				_m.Scope = value.String
			}
		case subscriptionresetcard.FieldSourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_type", values[i])
			} else if value.Valid {
				_m.SourceType = value.String
			}
		case subscriptionresetcard.FieldCampaign:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field campaign", values[i])
			} else if value.Valid {
				_m.Campaign = new(string)
				*_m.Campaign = value.String
			}
		case subscriptionresetcard.FieldGrantEventID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field grant_event_id", values[i])
			} else if value.Valid {
				_m.GrantEventID = new(int64)
				*_m.GrantEventID = value.Int64
			}
		case subscriptionresetcard.FieldGrantIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field grant_index", values[i])
			} else if value.Valid {
				_m.GrantIndex = int(value.Int64)
			}
		case subscriptionresetcard.FieldGrantedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field granted_at", values[i])
			} else if value.Valid {
				_m.GrantedAt = value.Time
			}
		case subscriptionresetcard.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case subscriptionresetcard.FieldUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field used_at", values[i])
			} else if value.Valid {
				_m.UsedAt = new(time.Time)
				*_m.UsedAt = value.Time
			}
		case subscriptionresetcard.FieldUsedSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field used_subscription_id", values[i])
			} else if value.Valid {
				_m.UsedSubscriptionID = new(int64)
				*_m.UsedSubscriptionID = value.Int64
			}
		case subscriptionresetcard.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(int64)
				*_m.CreatedBy = value.Int64
			}
		case subscriptionresetcard.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case subscriptionresetcard.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubscriptionResetCard.
// This includes values selected through modifiers, order, etc.
func (_m *SubscriptionResetCard) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the SubscriptionResetCard entity.
func (_m *SubscriptionResetCard) QueryUser() *UserQuery {
	return NewSubscriptionResetCardClient(_m.config).QueryUser(_m)
}

// QueryCreatedByUser queries the "created_by_user" edge of the SubscriptionResetCard entity.
func (_m *SubscriptionResetCard) QueryCreatedByUser() *UserQuery {
	return NewSubscriptionResetCardClient(_m.config).QueryCreatedByUser(_m)
}

// QueryUsedSubscription queries the "used_subscription" edge of the SubscriptionResetCard entity.
func (_m *SubscriptionResetCard) QueryUsedSubscription() *UserSubscriptionQuery {
	return NewSubscriptionResetCardClient(_m.config).QueryUsedSubscription(_m)
}

// QueryGrantEvent queries the "grant_event" edge of the SubscriptionResetCard entity.
func (_m *SubscriptionResetCard) QueryGrantEvent() *SubscriptionResetEventQuery {
	return NewSubscriptionResetCardClient(_m.config).QueryGrantEvent(_m)
}

// Update returns a builder for updating this SubscriptionResetCard.
// Note that you need to call SubscriptionResetCard.Unwrap() before calling this method if this SubscriptionResetCard
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SubscriptionResetCard) Update() *SubscriptionResetCardUpdateOne {
	return NewSubscriptionResetCardClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SubscriptionResetCard entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SubscriptionResetCard) Unwrap() *SubscriptionResetCard {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubscriptionResetCard is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SubscriptionResetCard) String() string {
	var builder strings.Builder
	builder.WriteString("SubscriptionResetCard(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("scope=")
	builder.WriteString(_m.Scope)
	builder.WriteString(", ")
	builder.WriteString("source_type=")
	builder.WriteString(_m.SourceType)
	builder.WriteString(", ")
	if v := _m.Campaign; v != nil {
		builder.WriteString("campaign=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.GrantEventID; v != nil {
		builder.WriteString("grant_event_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("grant_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.GrantIndex))
	builder.WriteString(", ")
	builder.WriteString("granted_at=")
	builder.WriteString(_m.GrantedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UsedAt; v != nil {
		builder.WriteString("used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UsedSubscriptionID; v != nil {
		builder.WriteString("used_subscription_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteByte(')')
	return builder.String()
}

// SubscriptionResetCards is a parsable slice of SubscriptionResetCard.
type SubscriptionResetCards []*SubscriptionResetCard
