// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionresetcard"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionresetevent"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionResetCardQuery is the builder for querying SubscriptionResetCard entities.
type SubscriptionResetCardQuery struct {
	config
	ctx                  *QueryContext
	order                []subscriptionresetcard.OrderOption
	inters               []Interceptor
	predicates           []predicate.SubscriptionResetCard
	withUser             *UserQuery
	withCreatedByUser    *UserQuery
	withUsedSubscription *UserSubscriptionQuery
	withGrantEvent       *SubscriptionResetEventQuery
	modifiers            []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SubscriptionResetCardQuery builder.
func (_q *SubscriptionResetCardQuery) Where(ps ...predicate.SubscriptionResetCard) *SubscriptionResetCardQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SubscriptionResetCardQuery) Limit(limit int) *SubscriptionResetCardQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SubscriptionResetCardQuery) Offset(offset int) *SubscriptionResetCardQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SubscriptionResetCardQuery) Unique(unique bool) *SubscriptionResetCardQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SubscriptionResetCardQuery) Order(o ...subscriptionresetcard.OrderOption) *SubscriptionResetCardQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUser chains the current query on the "user" edge.
func (_q *SubscriptionResetCardQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subscriptionresetcard.Table, subscriptionresetcard.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, subscriptionresetcard.UserTable, subscriptionresetcard.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCreatedByUser chains the current query on the "created_by_user" edge.
func (_q *SubscriptionResetCardQuery) QueryCreatedByUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subscriptionresetcard.Table, subscriptionresetcard.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, subscriptionresetcard.CreatedByUserTable, subscriptionresetcard.CreatedByUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUsedSubscription chains the current query on the "used_subscription" edge.
func (_q *SubscriptionResetCardQuery) QueryUsedSubscription() *UserSubscriptionQuery {
	query := (&UserSubscriptionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subscriptionresetcard.Table, subscriptionresetcard.FieldID, selector),
			sqlgraph.To(usersubscription.Table, usersubscription.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, subscriptionresetcard.UsedSubscriptionTable, subscriptionresetcard.UsedSubscriptionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGrantEvent chains the current query on the "grant_event" edge.
func (_q *SubscriptionResetCardQuery) QueryGrantEvent() *SubscriptionResetEventQuery {
	query := (&SubscriptionResetEventClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subscriptionresetcard.Table, subscriptionresetcard.FieldID, selector),
			sqlgraph.To(subscriptionresetevent.Table, subscriptionresetevent.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, subscriptionresetcard.GrantEventTable, subscriptionresetcard.GrantEventColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SubscriptionResetCard entity from the query.
// Returns a *NotFoundError when no SubscriptionResetCard was found.
func (_q *SubscriptionResetCardQuery) First(ctx context.Context) (*SubscriptionResetCard, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{subscriptionresetcard.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SubscriptionResetCardQuery) FirstX(ctx context.Context) *SubscriptionResetCard {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SubscriptionResetCard ID from the query.
// Returns a *NotFoundError when no SubscriptionResetCard ID was found.
func (_q *SubscriptionResetCardQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{subscriptionresetcard.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SubscriptionResetCardQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SubscriptionResetCard entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SubscriptionResetCard entity is found.
// Returns a *NotFoundError when no SubscriptionResetCard entities are found.
func (_q *SubscriptionResetCardQuery) Only(ctx context.Context) (*SubscriptionResetCard, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{subscriptionresetcard.Label}
	default:
		return nil, &NotSingularError{subscriptionresetcard.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SubscriptionResetCardQuery) OnlyX(ctx context.Context) *SubscriptionResetCard {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SubscriptionResetCard ID in the query.
// Returns a *NotSingularError when more than one SubscriptionResetCard ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SubscriptionResetCardQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{subscriptionresetcard.Label}
	default:
		err = &NotSingularError{subscriptionresetcard.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SubscriptionResetCardQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SubscriptionResetCards.
func (_q *SubscriptionResetCardQuery) All(ctx context.Context) ([]*SubscriptionResetCard, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SubscriptionResetCard, *SubscriptionResetCardQuery]()
	return withInterceptors[[]*SubscriptionResetCard](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SubscriptionResetCardQuery) AllX(ctx context.Context) []*SubscriptionResetCard {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SubscriptionResetCard IDs.
func (_q *SubscriptionResetCardQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(subscriptionresetcard.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SubscriptionResetCardQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SubscriptionResetCardQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SubscriptionResetCardQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SubscriptionResetCardQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SubscriptionResetCardQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SubscriptionResetCardQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SubscriptionResetCardQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SubscriptionResetCardQuery) Clone() *SubscriptionResetCardQuery {
	if _q == nil {
		return nil
	}
	return &SubscriptionResetCardQuery{
		config:               _q.config,
		ctx:                  _q.ctx.Clone(),
		order:                append([]subscriptionresetcard.OrderOption{}, _q.order...),
		inters:               append([]Interceptor{}, _q.inters...),
		predicates:           append([]predicate.SubscriptionResetCard{}, _q.predicates...),
		withUser:             _q.withUser.Clone(),
		withCreatedByUser:    _q.withCreatedByUser.Clone(),
		withUsedSubscription: _q.withUsedSubscription.Clone(),
		withGrantEvent:       _q.withGrantEvent.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubscriptionResetCardQuery) WithUser(opts ...func(*UserQuery)) *SubscriptionResetCardQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithCreatedByUser tells the query-builder to eager-load the nodes that are connected to
// the "created_by_user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubscriptionResetCardQuery) WithCreatedByUser(opts ...func(*UserQuery)) *SubscriptionResetCardQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCreatedByUser = query
	return _q
}

// WithUsedSubscription tells the query-builder to eager-load the nodes that are connected to
// the "used_subscription" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubscriptionResetCardQuery) WithUsedSubscription(opts ...func(*UserSubscriptionQuery)) *SubscriptionResetCardQuery {
	query := (&UserSubscriptionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUsedSubscription = query
	return _q
}

// WithGrantEvent tells the query-builder to eager-load the nodes that are connected to
// the "grant_event" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubscriptionResetCardQuery) WithGrantEvent(opts ...func(*SubscriptionResetEventQuery)) *SubscriptionResetCardQuery {
	query := (&SubscriptionResetEventClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGrantEvent = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SubscriptionResetCard.Query().
//		GroupBy(subscriptionresetcard.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SubscriptionResetCardQuery) GroupBy(field string, fields ...string) *SubscriptionResetCardGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SubscriptionResetCardGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = subscriptionresetcard.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.SubscriptionResetCard.Query().
//		Select(subscriptionresetcard.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *SubscriptionResetCardQuery) Select(fields ...string) *SubscriptionResetCardSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SubscriptionResetCardSelect{SubscriptionResetCardQuery: _q}
	sbuild.label = subscriptionresetcard.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SubscriptionResetCardSelect configured with the given aggregations.
func (_q *SubscriptionResetCardQuery) Aggregate(fns ...AggregateFunc) *SubscriptionResetCardSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SubscriptionResetCardQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !subscriptionresetcard.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SubscriptionResetCardQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SubscriptionResetCard, error) {
	var (
		nodes       = []*SubscriptionResetCard{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withUser != nil,
			_q.withCreatedByUser != nil,
			_q.withUsedSubscription != nil,
			_q.withGrantEvent != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SubscriptionResetCard).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SubscriptionResetCard{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *SubscriptionResetCard, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCreatedByUser; query != nil {
		if err := _q.loadCreatedByUser(ctx, query, nodes, nil,
			func(n *SubscriptionResetCard, e *User) { n.Edges.CreatedByUser = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUsedSubscription; query != nil {
		if err := _q.loadUsedSubscription(ctx, query, nodes, nil,
			func(n *SubscriptionResetCard, e *UserSubscription) { n.Edges.UsedSubscription = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGrantEvent; query != nil {
		if err := _q.loadGrantEvent(ctx, query, nodes, nil,
			func(n *SubscriptionResetCard, e *SubscriptionResetEvent) { n.Edges.GrantEvent = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *SubscriptionResetCardQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*SubscriptionResetCard, init func(*SubscriptionResetCard), assign func(*SubscriptionResetCard, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*SubscriptionResetCard)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *SubscriptionResetCardQuery) loadCreatedByUser(ctx context.Context, query *UserQuery, nodes []*SubscriptionResetCard, init func(*SubscriptionResetCard), assign func(*SubscriptionResetCard, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*SubscriptionResetCard)
	for i := range nodes {
		if nodes[i].CreatedBy == nil {
			continue
		}
		fk := *nodes[i].CreatedBy
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "created_by" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *SubscriptionResetCardQuery) loadUsedSubscription(ctx context.Context, query *UserSubscriptionQuery, nodes []*SubscriptionResetCard, init func(*SubscriptionResetCard), assign func(*SubscriptionResetCard, *UserSubscription)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*SubscriptionResetCard)
	for i := range nodes {
		if nodes[i].UsedSubscriptionID == nil {
			continue
		}
		fk := *nodes[i].UsedSubscriptionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(usersubscription.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "used_subscription_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *SubscriptionResetCardQuery) loadGrantEvent(ctx context.Context, query *SubscriptionResetEventQuery, nodes []*SubscriptionResetCard, init func(*SubscriptionResetCard), assign func(*SubscriptionResetCard, *SubscriptionResetEvent)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*SubscriptionResetCard)
	for i := range nodes {
		if nodes[i].GrantEventID == nil {
			continue
		}
		fk := *nodes[i].GrantEventID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(subscriptionresetevent.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "grant_event_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *SubscriptionResetCardQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SubscriptionResetCardQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(subscriptionresetcard.Table, subscriptionresetcard.Columns, sqlgraph.NewFieldSpec(subscriptionresetcard.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionresetcard.FieldID)
		for i := range fields {
			if fields[i] != subscriptionresetcard.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(subscriptionresetcard.FieldUserID)
		}
		if _q.withCreatedByUser != nil {
			_spec.Node.AddColumnOnce(subscriptionresetcard.FieldCreatedBy)
		}
		if _q.withUsedSubscription != nil {
			_spec.Node.AddColumnOnce(subscriptionresetcard.FieldUsedSubscriptionID)
		}
		if _q.withGrantEvent != nil {
			_spec.Node.AddColumnOnce(subscriptionresetcard.FieldGrantEventID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SubscriptionResetCardQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(subscriptionresetcard.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = subscriptionresetcard.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *SubscriptionResetCardQuery) ForUpdate(opts ...sql.LockOption) *SubscriptionResetCardQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *SubscriptionResetCardQuery) ForShare(opts ...sql.LockOption) *SubscriptionResetCardQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// SubscriptionResetCardGroupBy is the group-by builder for SubscriptionResetCard entities.
type SubscriptionResetCardGroupBy struct {
	selector
	build *SubscriptionResetCardQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SubscriptionResetCardGroupBy) Aggregate(fns ...AggregateFunc) *SubscriptionResetCardGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SubscriptionResetCardGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubscriptionResetCardQuery, *SubscriptionResetCardGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SubscriptionResetCardGroupBy) sqlScan(ctx context.Context, root *SubscriptionResetCardQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SubscriptionResetCardSelect is the builder for selecting fields of SubscriptionResetCard entities.
type SubscriptionResetCardSelect struct {
	*SubscriptionResetCardQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SubscriptionResetCardSelect) Aggregate(fns ...AggregateFunc) *SubscriptionResetCardSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SubscriptionResetCardSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubscriptionResetCardQuery, *SubscriptionResetCardSelect](ctx, _s.SubscriptionResetCardQuery, _s, _s.inters, v)
}

func (_s *SubscriptionResetCardSelect) sqlScan(ctx context.Context, root *SubscriptionResetCardQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
