// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionresetapplication"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionresetcard"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionresetevent"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SubscriptionResetEventCreate is the builder for creating a SubscriptionResetEvent entity.
type SubscriptionResetEventCreate struct {
	config
	mutation *SubscriptionResetEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubscriptionResetEventCreate) SetCreatedAt(v time.Time) *SubscriptionResetEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubscriptionResetEventCreate) SetNillableCreatedAt(v *time.Time) *SubscriptionResetEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SubscriptionResetEventCreate) SetUpdatedAt(v time.Time) *SubscriptionResetEventCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SubscriptionResetEventCreate) SetNillableUpdatedAt(v *time.Time) *SubscriptionResetEventCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *SubscriptionResetEventCreate) SetEventType(v string) *SubscriptionResetEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *SubscriptionResetEventCreate) SetStatus(v string) *SubscriptionResetEventCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SubscriptionResetEventCreate) SetNillableStatus(v *string) *SubscriptionResetEventCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetEffectiveAt sets the "effective_at" field.
func (_c *SubscriptionResetEventCreate) SetEffectiveAt(v time.Time) *SubscriptionResetEventCreate {
	_c.mutation.SetEffectiveAt(v)
	return _c
}

// SetScopeType sets the "scope_type" field.
func (_c *SubscriptionResetEventCreate) SetScopeType(v string) *SubscriptionResetEventCreate {
	_c.mutation.SetScopeType(v)
	return _c
}

// SetScope sets the "scope" field.
func (_c *SubscriptionResetEventCreate) SetScope(v map[string]interface{}) *SubscriptionResetEventCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetReason sets the "reason" field.
func (_c *SubscriptionResetEventCreate) SetReason(v string) *SubscriptionResetEventCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *SubscriptionResetEventCreate) SetNillableReason(v *string) *SubscriptionResetEventCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetCampaign sets the "campaign" field.
func (_c *SubscriptionResetEventCreate) SetCampaign(v string) *SubscriptionResetEventCreate {
	_c.mutation.SetCampaign(v)
	return _c
}

// SetNillableCampaign sets the "campaign" field if the given value is not nil.
func (_c *SubscriptionResetEventCreate) SetNillableCampaign(v *string) *SubscriptionResetEventCreate {
	if v != nil {
		_c.SetCampaign(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *SubscriptionResetEventCreate) SetCreatedBy(v int64) *SubscriptionResetEventCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *SubscriptionResetEventCreate) SetNillableCreatedBy(v *int64) *SubscriptionResetEventCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *SubscriptionResetEventCreate) SetStartedAt(v time.Time) *SubscriptionResetEventCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *SubscriptionResetEventCreate) SetNillableStartedAt(v *time.Time) *SubscriptionResetEventCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *SubscriptionResetEventCreate) SetCompletedAt(v time.Time) *SubscriptionResetEventCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *SubscriptionResetEventCreate) SetNillableCompletedAt(v *time.Time) *SubscriptionResetEventCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *SubscriptionResetEventCreate) SetMetadata(v map[string]interface{}) *SubscriptionResetEventCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedByUserID sets the "created_by_user" edge to the User entity by ID.
func (_c *SubscriptionResetEventCreate) SetCreatedByUserID(id int64) *SubscriptionResetEventCreate {
	_c.mutation.SetCreatedByUserID(id)
	return _c
}

// SetNillableCreatedByUserID sets the "created_by_user" edge to the User entity by ID if the given value is not nil.
func (_c *SubscriptionResetEventCreate) SetNillableCreatedByUserID(id *int64) *SubscriptionResetEventCreate {
	if id != nil {
		_c = _c.SetCreatedByUserID(*id)
	}
	return _c
}

// SetCreatedByUser sets the "created_by_user" edge to the User entity.
func (_c *SubscriptionResetEventCreate) SetCreatedByUser(v *User) *SubscriptionResetEventCreate {
	return _c.SetCreatedByUserID(v.ID)
}

// AddApplicationIDs adds the "applications" edge to the SubscriptionResetApplication entity by IDs.
func (_c *SubscriptionResetEventCreate) AddApplicationIDs(ids ...int64) *SubscriptionResetEventCreate {
	_c.mutation.AddApplicationIDs(ids...)
	return _c
}

// AddApplications adds the "applications" edges to the SubscriptionResetApplication entity.
func (_c *SubscriptionResetEventCreate) AddApplications(v ...*SubscriptionResetApplication) *SubscriptionResetEventCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddApplicationIDs(ids...)
}

// AddGrantedCardIDs adds the "granted_cards" edge to the SubscriptionResetCard entity by IDs.
func (_c *SubscriptionResetEventCreate) AddGrantedCardIDs(ids ...int64) *SubscriptionResetEventCreate {
	_c.mutation.AddGrantedCardIDs(ids...)
	return _c
}

// AddGrantedCards adds the "granted_cards" edges to the SubscriptionResetCard entity.
func (_c *SubscriptionResetEventCreate) AddGrantedCards(v ...*SubscriptionResetCard) *SubscriptionResetEventCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddGrantedCardIDs(ids...)
}

// Mutation returns the SubscriptionResetEventMutation object of the builder.
func (_c *SubscriptionResetEventCreate) Mutation() *SubscriptionResetEventMutation {
	return _c.mutation
}

// Save creates the SubscriptionResetEvent in the database.
func (_c *SubscriptionResetEventCreate) Save(ctx context.Context) (*SubscriptionResetEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionResetEventCreate) SaveX(ctx context.Context) *SubscriptionResetEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionResetEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionResetEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionResetEventCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := subscriptionresetevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := subscriptionresetevent.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := subscriptionresetevent.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Reason(); !ok {
		v := subscriptionresetevent.DefaultReason
		_c.mutation.SetReason(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionResetEventCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SubscriptionResetEvent.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SubscriptionResetEvent.updated_at"`)}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "SubscriptionResetEvent.event_type"`)}
	}
	if v, ok := _c.mutation.EventType(); ok {
		if err := subscriptionresetevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetEvent.event_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SubscriptionResetEvent.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := subscriptionresetevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetEvent.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EffectiveAt(); !ok {
		return &ValidationError{Name: "effective_at", err: errors.New(`ent: missing required field "SubscriptionResetEvent.effective_at"`)}
	}
	if _, ok := _c.mutation.ScopeType(); !ok {
		return &ValidationError{Name: "scope_type", err: errors.New(`ent: missing required field "SubscriptionResetEvent.scope_type"`)}
	}
	if v, ok := _c.mutation.ScopeType(); ok {
		if err := subscriptionresetevent.ScopeTypeValidator(v); err != nil {
			return &ValidationError{Name: "scope_type", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetEvent.scope_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "SubscriptionResetEvent.scope"`)}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "SubscriptionResetEvent.reason"`)}
	}
	if v, ok := _c.mutation.Campaign(); ok {
		if err := subscriptionresetevent.CampaignValidator(v); err != nil {
			return &ValidationError{Name: "campaign", err: fmt.Errorf(`ent: validator failed for field "SubscriptionResetEvent.campaign": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "SubscriptionResetEvent.metadata"`)}
	}
	return nil
}

func (_c *SubscriptionResetEventCreate) sqlSave(ctx context.Context) (*SubscriptionResetEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionResetEventCreate) createSpec() (*SubscriptionResetEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &SubscriptionResetEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscriptionresetevent.Table, sqlgraph.NewFieldSpec(subscriptionresetevent.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subscriptionresetevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionresetevent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(subscriptionresetevent.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(subscriptionresetevent.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.EffectiveAt(); ok {
		_spec.SetField(subscriptionresetevent.FieldEffectiveAt, field.TypeTime, value)
		_node.EffectiveAt = value
	}
	if value, ok := _c.mutation.ScopeType(); ok {
		_spec.SetField(subscriptionresetevent.FieldScopeType, field.TypeString, value)
		_node.ScopeType = value
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(subscriptionresetevent.FieldScope, field.TypeJSON, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(subscriptionresetevent.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.Campaign(); ok {
		_spec.SetField(subscriptionresetevent.FieldCampaign, field.TypeString, value)
		_node.Campaign = &value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(subscriptionresetevent.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(subscriptionresetevent.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(subscriptionresetevent.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if nodes := _c.mutation.CreatedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionresetevent.CreatedByUserTable,
			Columns: []string{subscriptionresetevent.CreatedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatedBy = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ApplicationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionresetevent.ApplicationsTable,
			Columns: []string{subscriptionresetevent.ApplicationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionresetapplication.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GrantedCardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionresetevent.GrantedCardsTable,
			Columns: []string{subscriptionresetevent.GrantedCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionresetcard.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionResetEvent.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionResetEventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionResetEventCreate) OnConflict(opts ...sql.ConflictOption) *SubscriptionResetEventUpsertOne {
	_c.conflict = opts
	return &SubscriptionResetEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionResetEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionResetEventCreate) OnConflictColumns(columns ...string) *SubscriptionResetEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionResetEventUpsertOne{
		create: _c,
	}
}

type (
	// SubscriptionResetEventUpsertOne is the builder for "upsert"-ing
	//  one SubscriptionResetEvent node.
	SubscriptionResetEventUpsertOne struct {
		create *SubscriptionResetEventCreate
	}

	// SubscriptionResetEventUpsert is the "OnConflict" setter.
	SubscriptionResetEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionResetEventUpsert) SetUpdatedAt(v time.Time) *SubscriptionResetEventUpsert {
	u.Set(subscriptionresetevent.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsert) UpdateUpdatedAt() *SubscriptionResetEventUpsert {
	u.SetExcluded(subscriptionresetevent.FieldUpdatedAt)
	return u
}

// SetEventType sets the "event_type" field.
func (u *SubscriptionResetEventUpsert) SetEventType(v string) *SubscriptionResetEventUpsert {
	u.Set(subscriptionresetevent.FieldEventType, v)
	return u
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsert) UpdateEventType() *SubscriptionResetEventUpsert {
	u.SetExcluded(subscriptionresetevent.FieldEventType)
	return u
}

// SetStatus sets the "status" field.
func (u *SubscriptionResetEventUpsert) SetStatus(v string) *SubscriptionResetEventUpsert {
	u.Set(subscriptionresetevent.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsert) UpdateStatus() *SubscriptionResetEventUpsert {
	u.SetExcluded(subscriptionresetevent.FieldStatus)
	return u
}

// SetEffectiveAt sets the "effective_at" field.
func (u *SubscriptionResetEventUpsert) SetEffectiveAt(v time.Time) *SubscriptionResetEventUpsert {
	u.Set(subscriptionresetevent.FieldEffectiveAt, v)
	return u
}

// UpdateEffectiveAt sets the "effective_at" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsert) UpdateEffectiveAt() *SubscriptionResetEventUpsert {
	u.SetExcluded(subscriptionresetevent.FieldEffectiveAt)
	return u
}

// SetScopeType sets the "scope_type" field.
func (u *SubscriptionResetEventUpsert) SetScopeType(v string) *SubscriptionResetEventUpsert {
	u.Set(subscriptionresetevent.FieldScopeType, v)
	return u
}

// UpdateScopeType sets the "scope_type" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsert) UpdateScopeType() *SubscriptionResetEventUpsert {
	u.SetExcluded(subscriptionresetevent.FieldScopeType)
	return u
}

// SetScope sets the "scope" field.
func (u *SubscriptionResetEventUpsert) SetScope(v map[string]interface{}) *SubscriptionResetEventUpsert {
	u.Set(subscriptionresetevent.FieldScope, v)
	return u
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsert) UpdateScope() *SubscriptionResetEventUpsert {
	u.SetExcluded(subscriptionresetevent.FieldScope)
	return u
}

// SetReason sets the "reason" field.
func (u *SubscriptionResetEventUpsert) SetReason(v string) *SubscriptionResetEventUpsert {
	u.Set(subscriptionresetevent.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsert) UpdateReason() *SubscriptionResetEventUpsert {
	u.SetExcluded(subscriptionresetevent.FieldReason)
	return u
}

// SetCampaign sets the "campaign" field.
func (u *SubscriptionResetEventUpsert) SetCampaign(v string) *SubscriptionResetEventUpsert {
	u.Set(subscriptionresetevent.FieldCampaign, v)
	return u
}

// UpdateCampaign sets the "campaign" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsert) UpdateCampaign() *SubscriptionResetEventUpsert {
	u.SetExcluded(subscriptionresetevent.FieldCampaign)
	return u
}

// ClearCampaign clears the value of the "campaign" field.
func (u *SubscriptionResetEventUpsert) ClearCampaign() *SubscriptionResetEventUpsert {
	u.SetNull(subscriptionresetevent.FieldCampaign)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *SubscriptionResetEventUpsert) SetCreatedBy(v int64) *SubscriptionResetEventUpsert {
	u.Set(subscriptionresetevent.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsert) UpdateCreatedBy() *SubscriptionResetEventUpsert {
	u.SetExcluded(subscriptionresetevent.FieldCreatedBy)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *SubscriptionResetEventUpsert) ClearCreatedBy() *SubscriptionResetEventUpsert {
	u.SetNull(subscriptionresetevent.FieldCreatedBy)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *SubscriptionResetEventUpsert) SetStartedAt(v time.Time) *SubscriptionResetEventUpsert {
	u.Set(subscriptionresetevent.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsert) UpdateStartedAt() *SubscriptionResetEventUpsert {
	u.SetExcluded(subscriptionresetevent.FieldStartedAt)
	return u
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *SubscriptionResetEventUpsert) ClearStartedAt() *SubscriptionResetEventUpsert {
	u.SetNull(subscriptionresetevent.FieldStartedAt)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *SubscriptionResetEventUpsert) SetCompletedAt(v time.Time) *SubscriptionResetEventUpsert {
	u.Set(subscriptionresetevent.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsert) UpdateCompletedAt() *SubscriptionResetEventUpsert {
	u.SetExcluded(subscriptionresetevent.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *SubscriptionResetEventUpsert) ClearCompletedAt() *SubscriptionResetEventUpsert {
	u.SetNull(subscriptionresetevent.FieldCompletedAt)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *SubscriptionResetEventUpsert) SetMetadata(v map[string]interface{}) *SubscriptionResetEventUpsert {
	u.Set(subscriptionresetevent.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsert) UpdateMetadata() *SubscriptionResetEventUpsert {
	u.SetExcluded(subscriptionresetevent.FieldMetadata)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SubscriptionResetEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionResetEventUpsertOne) UpdateNewValues() *SubscriptionResetEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(subscriptionresetevent.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionResetEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubscriptionResetEventUpsertOne) Ignore() *SubscriptionResetEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionResetEventUpsertOne) DoNothing() *SubscriptionResetEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionResetEventCreate.OnConflict
// documentation for more info.
func (u *SubscriptionResetEventUpsertOne) Update(set func(*SubscriptionResetEventUpsert)) *SubscriptionResetEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionResetEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionResetEventUpsertOne) SetUpdatedAt(v time.Time) *SubscriptionResetEventUpsertOne {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsertOne) UpdateUpdatedAt() *SubscriptionResetEventUpsertOne {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetEventType sets the "event_type" field.
func (u *SubscriptionResetEventUpsertOne) SetEventType(v string) *SubscriptionResetEventUpsertOne {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsertOne) UpdateEventType() *SubscriptionResetEventUpsertOne {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.UpdateEventType()
	})
}

// SetStatus sets the "status" field.
func (u *SubscriptionResetEventUpsertOne) SetStatus(v string) *SubscriptionResetEventUpsertOne {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsertOne) UpdateStatus() *SubscriptionResetEventUpsertOne {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.UpdateStatus()
	})
}

// SetEffectiveAt sets the "effective_at" field.
func (u *SubscriptionResetEventUpsertOne) SetEffectiveAt(v time.Time) *SubscriptionResetEventUpsertOne {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.SetEffectiveAt(v)
	})
}

// UpdateEffectiveAt sets the "effective_at" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsertOne) UpdateEffectiveAt() *SubscriptionResetEventUpsertOne {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.UpdateEffectiveAt()
	})
}

// SetScopeType sets the "scope_type" field.
func (u *SubscriptionResetEventUpsertOne) SetScopeType(v string) *SubscriptionResetEventUpsertOne {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.SetScopeType(v)
	})
}

// UpdateScopeType sets the "scope_type" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsertOne) UpdateScopeType() *SubscriptionResetEventUpsertOne {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.UpdateScopeType()
	})
}

// SetScope sets the "scope" field.
func (u *SubscriptionResetEventUpsertOne) SetScope(v map[string]interface{}) *SubscriptionResetEventUpsertOne {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsertOne) UpdateScope() *SubscriptionResetEventUpsertOne {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.UpdateScope()
	})
}

// SetReason sets the "reason" field.
func (u *SubscriptionResetEventUpsertOne) SetReason(v string) *SubscriptionResetEventUpsertOne {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsertOne) UpdateReason() *SubscriptionResetEventUpsertOne {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.UpdateReason()
	})
}

// SetCampaign sets the "campaign" field.
func (u *SubscriptionResetEventUpsertOne) SetCampaign(v string) *SubscriptionResetEventUpsertOne {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.SetCampaign(v)
	})
}

// UpdateCampaign sets the "campaign" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsertOne) UpdateCampaign() *SubscriptionResetEventUpsertOne {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.UpdateCampaign()
	})
}

// ClearCampaign clears the value of the "campaign" field.
func (u *SubscriptionResetEventUpsertOne) ClearCampaign() *SubscriptionResetEventUpsertOne {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.ClearCampaign()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *SubscriptionResetEventUpsertOne) SetCreatedBy(v int64) *SubscriptionResetEventUpsertOne {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsertOne) UpdateCreatedBy() *SubscriptionResetEventUpsertOne {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *SubscriptionResetEventUpsertOne) ClearCreatedBy() *SubscriptionResetEventUpsertOne {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.ClearCreatedBy()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *SubscriptionResetEventUpsertOne) SetStartedAt(v time.Time) *SubscriptionResetEventUpsertOne {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsertOne) UpdateStartedAt() *SubscriptionResetEventUpsertOne {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *SubscriptionResetEventUpsertOne) ClearStartedAt() *SubscriptionResetEventUpsertOne {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.ClearStartedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *SubscriptionResetEventUpsertOne) SetCompletedAt(v time.Time) *SubscriptionResetEventUpsertOne {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsertOne) UpdateCompletedAt() *SubscriptionResetEventUpsertOne {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *SubscriptionResetEventUpsertOne) ClearCompletedAt() *SubscriptionResetEventUpsertOne {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.ClearCompletedAt()
	})
}

// SetMetadata sets the "metadata" field.
func (u *SubscriptionResetEventUpsertOne) SetMetadata(v map[string]interface{}) *SubscriptionResetEventUpsertOne {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsertOne) UpdateMetadata() *SubscriptionResetEventUpsertOne {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.UpdateMetadata()
	})
}

// Exec executes the query.
func (u *SubscriptionResetEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionResetEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionResetEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubscriptionResetEventUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubscriptionResetEventUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubscriptionResetEventCreateBulk is the builder for creating many SubscriptionResetEvent entities in bulk.
type SubscriptionResetEventCreateBulk struct {
	config
	err      error
	builders []*SubscriptionResetEventCreate
	conflict []sql.ConflictOption
}

// Save creates the SubscriptionResetEvent entities in the database.
func (_c *SubscriptionResetEventCreateBulk) Save(ctx context.Context) ([]*SubscriptionResetEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubscriptionResetEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionResetEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionResetEventCreateBulk) SaveX(ctx context.Context) []*SubscriptionResetEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionResetEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionResetEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionResetEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionResetEventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionResetEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubscriptionResetEventUpsertBulk {
	_c.conflict = opts
	return &SubscriptionResetEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionResetEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionResetEventCreateBulk) OnConflictColumns(columns ...string) *SubscriptionResetEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionResetEventUpsertBulk{
		create: _c,
	}
}

// SubscriptionResetEventUpsertBulk is the builder for "upsert"-ing
// a bulk of SubscriptionResetEvent nodes.
type SubscriptionResetEventUpsertBulk struct {
	create *SubscriptionResetEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubscriptionResetEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionResetEventUpsertBulk) UpdateNewValues() *SubscriptionResetEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(subscriptionresetevent.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionResetEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubscriptionResetEventUpsertBulk) Ignore() *SubscriptionResetEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionResetEventUpsertBulk) DoNothing() *SubscriptionResetEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionResetEventCreateBulk.OnConflict
// documentation for more info.
func (u *SubscriptionResetEventUpsertBulk) Update(set func(*SubscriptionResetEventUpsert)) *SubscriptionResetEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionResetEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionResetEventUpsertBulk) SetUpdatedAt(v time.Time) *SubscriptionResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsertBulk) UpdateUpdatedAt() *SubscriptionResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetEventType sets the "event_type" field.
func (u *SubscriptionResetEventUpsertBulk) SetEventType(v string) *SubscriptionResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsertBulk) UpdateEventType() *SubscriptionResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.UpdateEventType()
	})
}

// SetStatus sets the "status" field.
func (u *SubscriptionResetEventUpsertBulk) SetStatus(v string) *SubscriptionResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsertBulk) UpdateStatus() *SubscriptionResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.UpdateStatus()
	})
}

// SetEffectiveAt sets the "effective_at" field.
func (u *SubscriptionResetEventUpsertBulk) SetEffectiveAt(v time.Time) *SubscriptionResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.SetEffectiveAt(v)
	})
}

// UpdateEffectiveAt sets the "effective_at" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsertBulk) UpdateEffectiveAt() *SubscriptionResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.UpdateEffectiveAt()
	})
}

// SetScopeType sets the "scope_type" field.
func (u *SubscriptionResetEventUpsertBulk) SetScopeType(v string) *SubscriptionResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.SetScopeType(v)
	})
}

// UpdateScopeType sets the "scope_type" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsertBulk) UpdateScopeType() *SubscriptionResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.UpdateScopeType()
	})
}

// SetScope sets the "scope" field.
func (u *SubscriptionResetEventUpsertBulk) SetScope(v map[string]interface{}) *SubscriptionResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsertBulk) UpdateScope() *SubscriptionResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.UpdateScope()
	})
}

// SetReason sets the "reason" field.
func (u *SubscriptionResetEventUpsertBulk) SetReason(v string) *SubscriptionResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsertBulk) UpdateReason() *SubscriptionResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.UpdateReason()
	})
}

// SetCampaign sets the "campaign" field.
func (u *SubscriptionResetEventUpsertBulk) SetCampaign(v string) *SubscriptionResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.SetCampaign(v)
	})
}

// UpdateCampaign sets the "campaign" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsertBulk) UpdateCampaign() *SubscriptionResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.UpdateCampaign()
	})
}

// ClearCampaign clears the value of the "campaign" field.
func (u *SubscriptionResetEventUpsertBulk) ClearCampaign() *SubscriptionResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.ClearCampaign()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *SubscriptionResetEventUpsertBulk) SetCreatedBy(v int64) *SubscriptionResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsertBulk) UpdateCreatedBy() *SubscriptionResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *SubscriptionResetEventUpsertBulk) ClearCreatedBy() *SubscriptionResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.ClearCreatedBy()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *SubscriptionResetEventUpsertBulk) SetStartedAt(v time.Time) *SubscriptionResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsertBulk) UpdateStartedAt() *SubscriptionResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *SubscriptionResetEventUpsertBulk) ClearStartedAt() *SubscriptionResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.ClearStartedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *SubscriptionResetEventUpsertBulk) SetCompletedAt(v time.Time) *SubscriptionResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsertBulk) UpdateCompletedAt() *SubscriptionResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *SubscriptionResetEventUpsertBulk) ClearCompletedAt() *SubscriptionResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.ClearCompletedAt()
	})
}

// SetMetadata sets the "metadata" field.
func (u *SubscriptionResetEventUpsertBulk) SetMetadata(v map[string]interface{}) *SubscriptionResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *SubscriptionResetEventUpsertBulk) UpdateMetadata() *SubscriptionResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionResetEventUpsert) {
		s.UpdateMetadata()
	})
}

// Exec executes the query.
func (u *SubscriptionResetEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubscriptionResetEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionResetEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionResetEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
