// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionterm"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionTermCreate is the builder for creating a SubscriptionTerm entity.
type SubscriptionTermCreate struct {
	config
	mutation *SubscriptionTermMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSubscriptionID sets the "subscription_id" field.
func (_c *SubscriptionTermCreate) SetSubscriptionID(v int64) *SubscriptionTermCreate {
	_c.mutation.SetSubscriptionID(v)
	return _c
}

// SetOrderID sets the "order_id" field.
func (_c *SubscriptionTermCreate) SetOrderID(v int64) *SubscriptionTermCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_c *SubscriptionTermCreate) SetNillableOrderID(v *int64) *SubscriptionTermCreate {
	if v != nil {
		_c.SetOrderID(*v)
	}
	return _c
}

// SetPlanID sets the "plan_id" field.
func (_c *SubscriptionTermCreate) SetPlanID(v int64) *SubscriptionTermCreate {
	_c.mutation.SetPlanID(v)
	return _c
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_c *SubscriptionTermCreate) SetNillablePlanID(v *int64) *SubscriptionTermCreate {
	if v != nil {
		_c.SetPlanID(*v)
	}
	return _c
}

// SetPricePaid sets the "price_paid" field.
func (_c *SubscriptionTermCreate) SetPricePaid(v float64) *SubscriptionTermCreate {
	_c.mutation.SetPricePaid(v)
	return _c
}

// SetNillablePricePaid sets the "price_paid" field if the given value is not nil.
func (_c *SubscriptionTermCreate) SetNillablePricePaid(v *float64) *SubscriptionTermCreate {
	if v != nil {
		_c.SetPricePaid(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *SubscriptionTermCreate) SetCurrency(v string) *SubscriptionTermCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *SubscriptionTermCreate) SetNillableCurrency(v *string) *SubscriptionTermCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetDays sets the "days" field.
func (_c *SubscriptionTermCreate) SetDays(v int) *SubscriptionTermCreate {
	_c.mutation.SetDays(v)
	return _c
}

// SetNillableDays sets the "days" field if the given value is not nil.
func (_c *SubscriptionTermCreate) SetNillableDays(v *int) *SubscriptionTermCreate {
	if v != nil {
		_c.SetDays(*v)
	}
	return _c
}

// SetTermStart sets the "term_start" field.
func (_c *SubscriptionTermCreate) SetTermStart(v time.Time) *SubscriptionTermCreate {
	_c.mutation.SetTermStart(v)
	return _c
}

// SetTermEnd sets the "term_end" field.
func (_c *SubscriptionTermCreate) SetTermEnd(v time.Time) *SubscriptionTermCreate {
	_c.mutation.SetTermEnd(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *SubscriptionTermCreate) SetSource(v string) *SubscriptionTermCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *SubscriptionTermCreate) SetNillableSource(v *string) *SubscriptionTermCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubscriptionTermCreate) SetCreatedAt(v time.Time) *SubscriptionTermCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubscriptionTermCreate) SetNillableCreatedAt(v *time.Time) *SubscriptionTermCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetSubscription sets the "subscription" edge to the UserSubscription entity.
func (_c *SubscriptionTermCreate) SetSubscription(v *UserSubscription) *SubscriptionTermCreate {
	return _c.SetSubscriptionID(v.ID)
}

// Mutation returns the SubscriptionTermMutation object of the builder.
func (_c *SubscriptionTermCreate) Mutation() *SubscriptionTermMutation {
	return _c.mutation
}

// Save creates the SubscriptionTerm in the database.
func (_c *SubscriptionTermCreate) Save(ctx context.Context) (*SubscriptionTerm, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionTermCreate) SaveX(ctx context.Context) *SubscriptionTerm {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionTermCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionTermCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionTermCreate) defaults() {
	if _, ok := _c.mutation.PricePaid(); !ok {
		v := subscriptionterm.DefaultPricePaid
		_c.mutation.SetPricePaid(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := subscriptionterm.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.Days(); !ok {
		v := subscriptionterm.DefaultDays
		_c.mutation.SetDays(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := subscriptionterm.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := subscriptionterm.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionTermCreate) check() error {
	if _, ok := _c.mutation.SubscriptionID(); !ok {
		return &ValidationError{Name: "subscription_id", err: errors.New(`ent: missing required field "SubscriptionTerm.subscription_id"`)}
	}
	if _, ok := _c.mutation.PricePaid(); !ok {
		return &ValidationError{Name: "price_paid", err: errors.New(`ent: missing required field "SubscriptionTerm.price_paid"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "SubscriptionTerm.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := subscriptionterm.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "SubscriptionTerm.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Days(); !ok {
		return &ValidationError{Name: "days", err: errors.New(`ent: missing required field "SubscriptionTerm.days"`)}
	}
	if _, ok := _c.mutation.TermStart(); !ok {
		return &ValidationError{Name: "term_start", err: errors.New(`ent: missing required field "SubscriptionTerm.term_start"`)}
	}
	if _, ok := _c.mutation.TermEnd(); !ok {
		return &ValidationError{Name: "term_end", err: errors.New(`ent: missing required field "SubscriptionTerm.term_end"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "SubscriptionTerm.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := subscriptionterm.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "SubscriptionTerm.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SubscriptionTerm.created_at"`)}
	}
	if len(_c.mutation.SubscriptionIDs()) == 0 {
		return &ValidationError{Name: "subscription", err: errors.New(`ent: missing required edge "SubscriptionTerm.subscription"`)}
	}
	return nil
}

func (_c *SubscriptionTermCreate) sqlSave(ctx context.Context) (*SubscriptionTerm, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionTermCreate) createSpec() (*SubscriptionTerm, *sqlgraph.CreateSpec) {
	var (
		_node = &SubscriptionTerm{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscriptionterm.Table, sqlgraph.NewFieldSpec(subscriptionterm.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.OrderID(); ok {
		_spec.SetField(subscriptionterm.FieldOrderID, field.TypeInt64, value)
		_node.OrderID = &value
	}
	if value, ok := _c.mutation.PlanID(); ok {
		_spec.SetField(subscriptionterm.FieldPlanID, field.TypeInt64, value)
		_node.PlanID = &value
	}
	if value, ok := _c.mutation.PricePaid(); ok {
		_spec.SetField(subscriptionterm.FieldPricePaid, field.TypeFloat64, value)
		_node.PricePaid = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(subscriptionterm.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.Days(); ok {
		_spec.SetField(subscriptionterm.FieldDays, field.TypeInt, value)
		_node.Days = value
	}
	if value, ok := _c.mutation.TermStart(); ok {
		_spec.SetField(subscriptionterm.FieldTermStart, field.TypeTime, value)
		_node.TermStart = value
	}
	if value, ok := _c.mutation.TermEnd(); ok {
		_spec.SetField(subscriptionterm.FieldTermEnd, field.TypeTime, value)
		_node.TermEnd = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(subscriptionterm.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subscriptionterm.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionterm.SubscriptionTable,
			Columns: []string{subscriptionterm.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SubscriptionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionTerm.Create().
//		SetSubscriptionID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionTermUpsert) {
//			SetSubscriptionID(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionTermCreate) OnConflict(opts ...sql.ConflictOption) *SubscriptionTermUpsertOne {
	_c.conflict = opts
	return &SubscriptionTermUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionTerm.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionTermCreate) OnConflictColumns(columns ...string) *SubscriptionTermUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionTermUpsertOne{
		create: _c,
	}
}

type (
	// SubscriptionTermUpsertOne is the builder for "upsert"-ing
	//  one SubscriptionTerm node.
	SubscriptionTermUpsertOne struct {
		create *SubscriptionTermCreate
	}

	// SubscriptionTermUpsert is the "OnConflict" setter.
	SubscriptionTermUpsert struct {
		*sql.UpdateSet
	}
)

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionTermUpsert) SetSubscriptionID(v int64) *SubscriptionTermUpsert {
	u.Set(subscriptionterm.FieldSubscriptionID, v)
	return u
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionTermUpsert) UpdateSubscriptionID() *SubscriptionTermUpsert {
	u.SetExcluded(subscriptionterm.FieldSubscriptionID)
	return u
}

// SetOrderID sets the "order_id" field.
func (u *SubscriptionTermUpsert) SetOrderID(v int64) *SubscriptionTermUpsert {
	u.Set(subscriptionterm.FieldOrderID, v)
	return u
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *SubscriptionTermUpsert) UpdateOrderID() *SubscriptionTermUpsert {
	u.SetExcluded(subscriptionterm.FieldOrderID)
	return u
}

// AddOrderID adds v to the "order_id" field.
func (u *SubscriptionTermUpsert) AddOrderID(v int64) *SubscriptionTermUpsert {
	u.Add(subscriptionterm.FieldOrderID, v)
	return u
}

// ClearOrderID clears the value of the "order_id" field.
func (u *SubscriptionTermUpsert) ClearOrderID() *SubscriptionTermUpsert {
	u.SetNull(subscriptionterm.FieldOrderID)
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *SubscriptionTermUpsert) SetPlanID(v int64) *SubscriptionTermUpsert {
	u.Set(subscriptionterm.FieldPlanID, v)
	return u
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *SubscriptionTermUpsert) UpdatePlanID() *SubscriptionTermUpsert {
	u.SetExcluded(subscriptionterm.FieldPlanID)
	return u
}

// AddPlanID adds v to the "plan_id" field.
func (u *SubscriptionTermUpsert) AddPlanID(v int64) *SubscriptionTermUpsert {
	u.Add(subscriptionterm.FieldPlanID, v)
	return u
}

// ClearPlanID clears the value of the "plan_id" field.
func (u *SubscriptionTermUpsert) ClearPlanID() *SubscriptionTermUpsert {
	u.SetNull(subscriptionterm.FieldPlanID)
	return u
}

// SetPricePaid sets the "price_paid" field.
func (u *SubscriptionTermUpsert) SetPricePaid(v float64) *SubscriptionTermUpsert {
	u.Set(subscriptionterm.FieldPricePaid, v)
	return u
}

// UpdatePricePaid sets the "price_paid" field to the value that was provided on create.
func (u *SubscriptionTermUpsert) UpdatePricePaid() *SubscriptionTermUpsert {
	u.SetExcluded(subscriptionterm.FieldPricePaid)
	return u
}

// AddPricePaid adds v to the "price_paid" field.
func (u *SubscriptionTermUpsert) AddPricePaid(v float64) *SubscriptionTermUpsert {
	u.Add(subscriptionterm.FieldPricePaid, v)
	return u
}

// SetCurrency sets the "currency" field.
func (u *SubscriptionTermUpsert) SetCurrency(v string) *SubscriptionTermUpsert {
	u.Set(subscriptionterm.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *SubscriptionTermUpsert) UpdateCurrency() *SubscriptionTermUpsert {
	u.SetExcluded(subscriptionterm.FieldCurrency)
	return u
}

// SetDays sets the "days" field.
func (u *SubscriptionTermUpsert) SetDays(v int) *SubscriptionTermUpsert {
	u.Set(subscriptionterm.FieldDays, v)
	return u
}

// UpdateDays sets the "days" field to the value that was provided on create.
func (u *SubscriptionTermUpsert) UpdateDays() *SubscriptionTermUpsert {
	u.SetExcluded(subscriptionterm.FieldDays)
	return u
}

// AddDays adds v to the "days" field.
func (u *SubscriptionTermUpsert) AddDays(v int) *SubscriptionTermUpsert {
	u.Add(subscriptionterm.FieldDays, v)
	return u
}

// SetTermStart sets the "term_start" field.
func (u *SubscriptionTermUpsert) SetTermStart(v time.Time) *SubscriptionTermUpsert {
	u.Set(subscriptionterm.FieldTermStart, v)
	return u
}

// UpdateTermStart sets the "term_start" field to the value that was provided on create.
func (u *SubscriptionTermUpsert) UpdateTermStart() *SubscriptionTermUpsert {
	u.SetExcluded(subscriptionterm.FieldTermStart)
	return u
}

// SetTermEnd sets the "term_end" field.
func (u *SubscriptionTermUpsert) SetTermEnd(v time.Time) *SubscriptionTermUpsert {
	u.Set(subscriptionterm.FieldTermEnd, v)
	return u
}

// UpdateTermEnd sets the "term_end" field to the value that was provided on create.
func (u *SubscriptionTermUpsert) UpdateTermEnd() *SubscriptionTermUpsert {
	u.SetExcluded(subscriptionterm.FieldTermEnd)
	return u
}

// SetSource sets the "source" field.
func (u *SubscriptionTermUpsert) SetSource(v string) *SubscriptionTermUpsert {
	u.Set(subscriptionterm.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *SubscriptionTermUpsert) UpdateSource() *SubscriptionTermUpsert {
	u.SetExcluded(subscriptionterm.FieldSource)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SubscriptionTerm.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionTermUpsertOne) UpdateNewValues() *SubscriptionTermUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(subscriptionterm.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionTerm.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubscriptionTermUpsertOne) Ignore() *SubscriptionTermUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionTermUpsertOne) DoNothing() *SubscriptionTermUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionTermCreate.OnConflict
// documentation for more info.
func (u *SubscriptionTermUpsertOne) Update(set func(*SubscriptionTermUpsert)) *SubscriptionTermUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionTermUpsert{UpdateSet: update})
	}))
	return u
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionTermUpsertOne) SetSubscriptionID(v int64) *SubscriptionTermUpsertOne {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.SetSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionTermUpsertOne) UpdateSubscriptionID() *SubscriptionTermUpsertOne {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.UpdateSubscriptionID()
	})
}

// SetOrderID sets the "order_id" field.
func (u *SubscriptionTermUpsertOne) SetOrderID(v int64) *SubscriptionTermUpsertOne {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.SetOrderID(v)
	})
}

// AddOrderID adds v to the "order_id" field.
func (u *SubscriptionTermUpsertOne) AddOrderID(v int64) *SubscriptionTermUpsertOne {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.AddOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *SubscriptionTermUpsertOne) UpdateOrderID() *SubscriptionTermUpsertOne {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.UpdateOrderID()
	})
}

// ClearOrderID clears the value of the "order_id" field.
func (u *SubscriptionTermUpsertOne) ClearOrderID() *SubscriptionTermUpsertOne {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.ClearOrderID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *SubscriptionTermUpsertOne) SetPlanID(v int64) *SubscriptionTermUpsertOne {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.SetPlanID(v)
	})
}

// AddPlanID adds v to the "plan_id" field.
func (u *SubscriptionTermUpsertOne) AddPlanID(v int64) *SubscriptionTermUpsertOne {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.AddPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *SubscriptionTermUpsertOne) UpdatePlanID() *SubscriptionTermUpsertOne {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.UpdatePlanID()
	})
}

// ClearPlanID clears the value of the "plan_id" field.
func (u *SubscriptionTermUpsertOne) ClearPlanID() *SubscriptionTermUpsertOne {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.ClearPlanID()
	})
}

// SetPricePaid sets the "price_paid" field.
func (u *SubscriptionTermUpsertOne) SetPricePaid(v float64) *SubscriptionTermUpsertOne {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.SetPricePaid(v)
	})
}

// AddPricePaid adds v to the "price_paid" field.
func (u *SubscriptionTermUpsertOne) AddPricePaid(v float64) *SubscriptionTermUpsertOne {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.AddPricePaid(v)
	})
}

// UpdatePricePaid sets the "price_paid" field to the value that was provided on create.
func (u *SubscriptionTermUpsertOne) UpdatePricePaid() *SubscriptionTermUpsertOne {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.UpdatePricePaid()
	})
}

// SetCurrency sets the "currency" field.
func (u *SubscriptionTermUpsertOne) SetCurrency(v string) *SubscriptionTermUpsertOne {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *SubscriptionTermUpsertOne) UpdateCurrency() *SubscriptionTermUpsertOne {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.UpdateCurrency()
	})
}

// SetDays sets the "days" field.
func (u *SubscriptionTermUpsertOne) SetDays(v int) *SubscriptionTermUpsertOne {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.SetDays(v)
	})
}

// AddDays adds v to the "days" field.
func (u *SubscriptionTermUpsertOne) AddDays(v int) *SubscriptionTermUpsertOne {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.AddDays(v)
	})
}

// UpdateDays sets the "days" field to the value that was provided on create.
func (u *SubscriptionTermUpsertOne) UpdateDays() *SubscriptionTermUpsertOne {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.UpdateDays()
	})
}

// SetTermStart sets the "term_start" field.
func (u *SubscriptionTermUpsertOne) SetTermStart(v time.Time) *SubscriptionTermUpsertOne {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.SetTermStart(v)
	})
}

// UpdateTermStart sets the "term_start" field to the value that was provided on create.
func (u *SubscriptionTermUpsertOne) UpdateTermStart() *SubscriptionTermUpsertOne {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.UpdateTermStart()
	})
}

// SetTermEnd sets the "term_end" field.
func (u *SubscriptionTermUpsertOne) SetTermEnd(v time.Time) *SubscriptionTermUpsertOne {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.SetTermEnd(v)
	})
}

// UpdateTermEnd sets the "term_end" field to the value that was provided on create.
func (u *SubscriptionTermUpsertOne) UpdateTermEnd() *SubscriptionTermUpsertOne {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.UpdateTermEnd()
	})
}

// SetSource sets the "source" field.
func (u *SubscriptionTermUpsertOne) SetSource(v string) *SubscriptionTermUpsertOne {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *SubscriptionTermUpsertOne) UpdateSource() *SubscriptionTermUpsertOne {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.UpdateSource()
	})
}

// Exec executes the query.
func (u *SubscriptionTermUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionTermCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionTermUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubscriptionTermUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubscriptionTermUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubscriptionTermCreateBulk is the builder for creating many SubscriptionTerm entities in bulk.
type SubscriptionTermCreateBulk struct {
	config
	err      error
	builders []*SubscriptionTermCreate
	conflict []sql.ConflictOption
}

// Save creates the SubscriptionTerm entities in the database.
func (_c *SubscriptionTermCreateBulk) Save(ctx context.Context) ([]*SubscriptionTerm, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubscriptionTerm, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionTermMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionTermCreateBulk) SaveX(ctx context.Context) []*SubscriptionTerm {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionTermCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionTermCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionTerm.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionTermUpsert) {
//			SetSubscriptionID(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionTermCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubscriptionTermUpsertBulk {
	_c.conflict = opts
	return &SubscriptionTermUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionTerm.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionTermCreateBulk) OnConflictColumns(columns ...string) *SubscriptionTermUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionTermUpsertBulk{
		create: _c,
	}
}

// SubscriptionTermUpsertBulk is the builder for "upsert"-ing
// a bulk of SubscriptionTerm nodes.
type SubscriptionTermUpsertBulk struct {
	create *SubscriptionTermCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubscriptionTerm.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionTermUpsertBulk) UpdateNewValues() *SubscriptionTermUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(subscriptionterm.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionTerm.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubscriptionTermUpsertBulk) Ignore() *SubscriptionTermUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionTermUpsertBulk) DoNothing() *SubscriptionTermUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionTermCreateBulk.OnConflict
// documentation for more info.
func (u *SubscriptionTermUpsertBulk) Update(set func(*SubscriptionTermUpsert)) *SubscriptionTermUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionTermUpsert{UpdateSet: update})
	}))
	return u
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionTermUpsertBulk) SetSubscriptionID(v int64) *SubscriptionTermUpsertBulk {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.SetSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionTermUpsertBulk) UpdateSubscriptionID() *SubscriptionTermUpsertBulk {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.UpdateSubscriptionID()
	})
}

// SetOrderID sets the "order_id" field.
func (u *SubscriptionTermUpsertBulk) SetOrderID(v int64) *SubscriptionTermUpsertBulk {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.SetOrderID(v)
	})
}

// AddOrderID adds v to the "order_id" field.
func (u *SubscriptionTermUpsertBulk) AddOrderID(v int64) *SubscriptionTermUpsertBulk {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.AddOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *SubscriptionTermUpsertBulk) UpdateOrderID() *SubscriptionTermUpsertBulk {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.UpdateOrderID()
	})
}

// ClearOrderID clears the value of the "order_id" field.
func (u *SubscriptionTermUpsertBulk) ClearOrderID() *SubscriptionTermUpsertBulk {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.ClearOrderID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *SubscriptionTermUpsertBulk) SetPlanID(v int64) *SubscriptionTermUpsertBulk {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.SetPlanID(v)
	})
}

// AddPlanID adds v to the "plan_id" field.
func (u *SubscriptionTermUpsertBulk) AddPlanID(v int64) *SubscriptionTermUpsertBulk {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.AddPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *SubscriptionTermUpsertBulk) UpdatePlanID() *SubscriptionTermUpsertBulk {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.UpdatePlanID()
	})
}

// ClearPlanID clears the value of the "plan_id" field.
func (u *SubscriptionTermUpsertBulk) ClearPlanID() *SubscriptionTermUpsertBulk {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.ClearPlanID()
	})
}

// SetPricePaid sets the "price_paid" field.
func (u *SubscriptionTermUpsertBulk) SetPricePaid(v float64) *SubscriptionTermUpsertBulk {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.SetPricePaid(v)
	})
}

// AddPricePaid adds v to the "price_paid" field.
func (u *SubscriptionTermUpsertBulk) AddPricePaid(v float64) *SubscriptionTermUpsertBulk {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.AddPricePaid(v)
	})
}

// UpdatePricePaid sets the "price_paid" field to the value that was provided on create.
func (u *SubscriptionTermUpsertBulk) UpdatePricePaid() *SubscriptionTermUpsertBulk {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.UpdatePricePaid()
	})
}

// SetCurrency sets the "currency" field.
func (u *SubscriptionTermUpsertBulk) SetCurrency(v string) *SubscriptionTermUpsertBulk {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *SubscriptionTermUpsertBulk) UpdateCurrency() *SubscriptionTermUpsertBulk {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.UpdateCurrency()
	})
}

// SetDays sets the "days" field.
func (u *SubscriptionTermUpsertBulk) SetDays(v int) *SubscriptionTermUpsertBulk {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.SetDays(v)
	})
}

// AddDays adds v to the "days" field.
func (u *SubscriptionTermUpsertBulk) AddDays(v int) *SubscriptionTermUpsertBulk {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.AddDays(v)
	})
}

// UpdateDays sets the "days" field to the value that was provided on create.
func (u *SubscriptionTermUpsertBulk) UpdateDays() *SubscriptionTermUpsertBulk {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.UpdateDays()
	})
}

// SetTermStart sets the "term_start" field.
func (u *SubscriptionTermUpsertBulk) SetTermStart(v time.Time) *SubscriptionTermUpsertBulk {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.SetTermStart(v)
	})
}

// UpdateTermStart sets the "term_start" field to the value that was provided on create.
func (u *SubscriptionTermUpsertBulk) UpdateTermStart() *SubscriptionTermUpsertBulk {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.UpdateTermStart()
	})
}

// SetTermEnd sets the "term_end" field.
func (u *SubscriptionTermUpsertBulk) SetTermEnd(v time.Time) *SubscriptionTermUpsertBulk {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.SetTermEnd(v)
	})
}

// UpdateTermEnd sets the "term_end" field to the value that was provided on create.
func (u *SubscriptionTermUpsertBulk) UpdateTermEnd() *SubscriptionTermUpsertBulk {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.UpdateTermEnd()
	})
}

// SetSource sets the "source" field.
func (u *SubscriptionTermUpsertBulk) SetSource(v string) *SubscriptionTermUpsertBulk {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *SubscriptionTermUpsertBulk) UpdateSource() *SubscriptionTermUpsertBulk {
	return u.Update(func(s *SubscriptionTermUpsert) {
		s.UpdateSource()
	})
}

// Exec executes the query.
func (u *SubscriptionTermUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubscriptionTermCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionTermCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionTermUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
