// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionterm"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionTerm is the model entity for the SubscriptionTerm schema.
type SubscriptionTerm struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// SubscriptionID holds the value of the "subscription_id" field.
	SubscriptionID int64 `json:"subscription_id,omitempty"`
	// OrderID holds the value of the "order_id" field.
	OrderID *int64 `json:"order_id,omitempty"`
	// PlanID holds the value of the "plan_id" field.
	PlanID *int64 `json:"plan_id,omitempty"`
	// PricePaid holds the value of the "price_paid" field.
	PricePaid float64 `json:"price_paid,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// Days holds the value of the "days" field.
	Days int `json:"days,omitempty"`
	// TermStart holds the value of the "term_start" field.
	TermStart time.Time `json:"term_start,omitempty"`
	// TermEnd holds the value of the "term_end" field.
	TermEnd time.Time `json:"term_end,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubscriptionTermQuery when eager-loading is set.
	Edges        SubscriptionTermEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SubscriptionTermEdges holds the relations/edges for other nodes in the graph.
type SubscriptionTermEdges struct {
	// Subscription holds the value of the subscription edge.
	Subscription *UserSubscription `json:"subscription,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SubscriptionOrErr returns the Subscription value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionTermEdges) SubscriptionOrErr() (*UserSubscription, error) {
	if e.Subscription != nil {
		return e.Subscription, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: usersubscription.Label}
	}
	return nil, &NotLoadedError{edge: "subscription"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubscriptionTerm) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscriptionterm.FieldPricePaid:
			values[i] = new(sql.NullFloat64)
		case subscriptionterm.FieldID, subscriptionterm.FieldSubscriptionID, subscriptionterm.FieldOrderID, subscriptionterm.FieldPlanID, subscriptionterm.FieldDays:
			values[i] = new(sql.NullInt64)
		case subscriptionterm.FieldCurrency, subscriptionterm.FieldSource:
			values[i] = new(sql.NullString)
		case subscriptionterm.FieldTermStart, subscriptionterm.FieldTermEnd, subscriptionterm.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubscriptionTerm fields.
func (_m *SubscriptionTerm) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscriptionterm.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case subscriptionterm.FieldSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_id", values[i])
			} else if value.Valid {
				_m.SubscriptionID = value.Int64
			}
		case subscriptionterm.FieldOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_id", values[i])
			} else if value.Valid {
				_m.OrderID = new(int64)
				*_m.OrderID = value.Int64
			}
		case subscriptionterm.FieldPlanID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field plan_id", values[i])
			} else if value.Valid {
				_m.PlanID = new(int64)
				*_m.PlanID = value.Int64
			}
		case subscriptionterm.FieldPricePaid:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price_paid", values[i])
			} else if value.Valid {
				_m.PricePaid = value.Float64
			}
		case subscriptionterm.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case subscriptionterm.FieldDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field days", values[i])
			} else if value.Valid {
				_m.Days = int(value.Int64)
			}
		case subscriptionterm.FieldTermStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field term_start", values[i])
			} else if value.Valid {
				_m.TermStart = value.Time
			}
		case subscriptionterm.FieldTermEnd:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field term_end", values[i])
			} else if value.Valid {
				_m.TermEnd = value.Time
			}
		case subscriptionterm.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case subscriptionterm.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubscriptionTerm.
// This includes values selected through modifiers, order, etc.
func (_m *SubscriptionTerm) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySubscription queries the "subscription" edge of the SubscriptionTerm entity.
func (_m *SubscriptionTerm) QuerySubscription() *UserSubscriptionQuery {
	return NewSubscriptionTermClient(_m.config).QuerySubscription(_m)
}

// Update returns a builder for updating this SubscriptionTerm.
// Note that you need to call SubscriptionTerm.Unwrap() before calling this method if this SubscriptionTerm
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SubscriptionTerm) Update() *SubscriptionTermUpdateOne {
	return NewSubscriptionTermClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SubscriptionTerm entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SubscriptionTerm) Unwrap() *SubscriptionTerm {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubscriptionTerm is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SubscriptionTerm) String() string {
	var builder strings.Builder
	builder.WriteString("SubscriptionTerm(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("subscription_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubscriptionID))
	builder.WriteString(", ")
	if v := _m.OrderID; v != nil {
		builder.WriteString("order_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PlanID; v != nil {
		builder.WriteString("plan_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("price_paid=")
	builder.WriteString(fmt.Sprintf("%v", _m.PricePaid))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("days=")
	builder.WriteString(fmt.Sprintf("%v", _m.Days))
	builder.WriteString(", ")
	builder.WriteString("term_start=")
	builder.WriteString(_m.TermStart.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("term_end=")
	builder.WriteString(_m.TermEnd.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SubscriptionTerms is a parsable slice of SubscriptionTerm.
type SubscriptionTerms []*SubscriptionTerm
