// Code generated by ent, DO NOT EDIT.

package subscriptionresetapplication

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the subscriptionresetapplication type in the database.
	Label = "subscription_reset_application"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldResetEventID holds the string denoting the reset_event_id field in the database.
	FieldResetEventID = "reset_event_id"
	// FieldUserSubscriptionID holds the string denoting the user_subscription_id field in the database.
	FieldUserSubscriptionID = "user_subscription_id"
	// FieldEffectiveAt holds the string denoting the effective_at field in the database.
	FieldEffectiveAt = "effective_at"
	// FieldPreviousWeeklyWindowStart holds the string denoting the previous_weekly_window_start field in the database.
	FieldPreviousWeeklyWindowStart = "previous_weekly_window_start"
	// FieldPreviousWeeklyUsageUsd holds the string denoting the previous_weekly_usage_usd field in the database.
	FieldPreviousWeeklyUsageUsd = "previous_weekly_usage_usd"
	// FieldAppliedAt holds the string denoting the applied_at field in the database.
	FieldAppliedAt = "applied_at"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// EdgeResetEvent holds the string denoting the reset_event edge name in mutations.
	EdgeResetEvent = "reset_event"
	// EdgeUserSubscription holds the string denoting the user_subscription edge name in mutations.
	EdgeUserSubscription = "user_subscription"
	// Table holds the table name of the subscriptionresetapplication in the database.
	Table = "subscription_reset_applications"
	// ResetEventTable is the table that holds the reset_event relation/edge.
	ResetEventTable = "subscription_reset_applications"
	// ResetEventInverseTable is the table name for the SubscriptionResetEvent entity.
	// It exists in this package in order to avoid circular dependency with the "subscriptionresetevent" package.
	ResetEventInverseTable = "subscription_reset_events"
	// ResetEventColumn is the table column denoting the reset_event relation/edge.
	ResetEventColumn = "reset_event_id"
	// UserSubscriptionTable is the table that holds the user_subscription relation/edge.
	UserSubscriptionTable = "subscription_reset_applications"
	// UserSubscriptionInverseTable is the table name for the UserSubscription entity.
	// It exists in this package in order to avoid circular dependency with the "usersubscription" package.
	UserSubscriptionInverseTable = "user_subscriptions"
	// UserSubscriptionColumn is the table column denoting the user_subscription relation/edge.
	UserSubscriptionColumn = "user_subscription_id"
)

// Columns holds all SQL columns for subscriptionresetapplication fields.
var Columns = []string{
	FieldID,
	FieldResetEventID,
	FieldUserSubscriptionID,
	FieldEffectiveAt,
	FieldPreviousWeeklyWindowStart,
	FieldPreviousWeeklyUsageUsd,
	FieldAppliedAt,
	FieldStatus,
	FieldMetadata,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultAppliedAt holds the default value on creation for the "applied_at" field.
	DefaultAppliedAt func() time.Time
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
)

// OrderOption defines the ordering options for the SubscriptionResetApplication queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByResetEventID orders the results by the reset_event_id field.
func ByResetEventID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResetEventID, opts...).ToFunc()
}

// ByUserSubscriptionID orders the results by the user_subscription_id field.
func ByUserSubscriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserSubscriptionID, opts...).ToFunc()
}

// ByEffectiveAt orders the results by the effective_at field.
func ByEffectiveAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffectiveAt, opts...).ToFunc()
}

// ByPreviousWeeklyWindowStart orders the results by the previous_weekly_window_start field.
func ByPreviousWeeklyWindowStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPreviousWeeklyWindowStart, opts...).ToFunc()
}

// ByPreviousWeeklyUsageUsd orders the results by the previous_weekly_usage_usd field.
func ByPreviousWeeklyUsageUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPreviousWeeklyUsageUsd, opts...).ToFunc()
}

// ByAppliedAt orders the results by the applied_at field.
func ByAppliedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppliedAt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByResetEventField orders the results by reset_event field.
func ByResetEventField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newResetEventStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserSubscriptionField orders the results by user_subscription field.
func ByUserSubscriptionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserSubscriptionStep(), sql.OrderByField(field, opts...))
	}
}
func newResetEventStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ResetEventInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ResetEventTable, ResetEventColumn),
	)
}
func newUserSubscriptionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserSubscriptionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserSubscriptionTable, UserSubscriptionColumn),
	)
}
