// Code generated by ent, DO NOT EDIT.

package subscriptionplanchange

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldDeletedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldUserID, v))
}

// SubscriptionID applies equality check predicate on the "subscription_id" field. It's identical to SubscriptionIDEQ.
func SubscriptionID(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldSubscriptionID, v))
}

// ChangeType applies equality check predicate on the "change_type" field. It's identical to ChangeTypeEQ.
func ChangeType(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldChangeType, v))
}

// FromPlanID applies equality check predicate on the "from_plan_id" field. It's identical to FromPlanIDEQ.
func FromPlanID(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldFromPlanID, v))
}

// ToPlanID applies equality check predicate on the "to_plan_id" field. It's identical to ToPlanIDEQ.
func ToPlanID(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldToPlanID, v))
}

// FromGroupID applies equality check predicate on the "from_group_id" field. It's identical to FromGroupIDEQ.
func FromGroupID(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldFromGroupID, v))
}

// ToGroupID applies equality check predicate on the "to_group_id" field. It's identical to ToGroupIDEQ.
func ToGroupID(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldToGroupID, v))
}

// FromTier applies equality check predicate on the "from_tier" field. It's identical to FromTierEQ.
func FromTier(v int) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldFromTier, v))
}

// ToTier applies equality check predicate on the "to_tier" field. It's identical to ToTierEQ.
func ToTier(v int) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldToTier, v))
}

// OldPriceSnapshot applies equality check predicate on the "old_price_snapshot" field. It's identical to OldPriceSnapshotEQ.
func OldPriceSnapshot(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldOldPriceSnapshot, v))
}

// NewPriceSnapshot applies equality check predicate on the "new_price_snapshot" field. It's identical to NewPriceSnapshotEQ.
func NewPriceSnapshot(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldNewPriceSnapshot, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldCurrency, v))
}

// TermStart applies equality check predicate on the "term_start" field. It's identical to TermStartEQ.
func TermStart(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldTermStart, v))
}

// TermEnd applies equality check predicate on the "term_end" field. It's identical to TermEndEQ.
func TermEnd(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldTermEnd, v))
}

// RemainingSeconds applies equality check predicate on the "remaining_seconds" field. It's identical to RemainingSecondsEQ.
func RemainingSeconds(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldRemainingSeconds, v))
}

// UnusedCredit applies equality check predicate on the "unused_credit" field. It's identical to UnusedCreditEQ.
func UnusedCredit(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldUnusedCredit, v))
}

// ProratedCharge applies equality check predicate on the "prorated_charge" field. It's identical to ProratedChargeEQ.
func ProratedCharge(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldProratedCharge, v))
}

// AmountDue applies equality check predicate on the "amount_due" field. It's identical to AmountDueEQ.
func AmountDue(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldAmountDue, v))
}

// QuoteCreatedAt applies equality check predicate on the "quote_created_at" field. It's identical to QuoteCreatedAtEQ.
func QuoteCreatedAt(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldQuoteCreatedAt, v))
}

// QuoteExpiresAt applies equality check predicate on the "quote_expires_at" field. It's identical to QuoteExpiresAtEQ.
func QuoteExpiresAt(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldQuoteExpiresAt, v))
}

// EffectiveAt applies equality check predicate on the "effective_at" field. It's identical to EffectiveAtEQ.
func EffectiveAt(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldEffectiveAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldStatus, v))
}

// CancelReason applies equality check predicate on the "cancel_reason" field. It's identical to CancelReasonEQ.
func CancelReason(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldCancelReason, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldOrderID, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldIdempotencyKey, v))
}

// PaidAt applies equality check predicate on the "paid_at" field. It's identical to PaidAtEQ.
func PaidAt(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldPaidAt, v))
}

// FulfilledAt applies equality check predicate on the "fulfilled_at" field. It's identical to FulfilledAtEQ.
func FulfilledAt(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldFulfilledAt, v))
}

// CancelledAt applies equality check predicate on the "cancelled_at" field. It's identical to CancelledAtEQ.
func CancelledAt(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldCancelledAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotNull(FieldDeletedAt))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldUserID, v))
}

// SubscriptionIDEQ applies the EQ predicate on the "subscription_id" field.
func SubscriptionIDEQ(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldSubscriptionID, v))
}

// SubscriptionIDNEQ applies the NEQ predicate on the "subscription_id" field.
func SubscriptionIDNEQ(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldSubscriptionID, v))
}

// SubscriptionIDIn applies the In predicate on the "subscription_id" field.
func SubscriptionIDIn(vs ...int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDNotIn applies the NotIn predicate on the "subscription_id" field.
func SubscriptionIDNotIn(vs ...int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDGT applies the GT predicate on the "subscription_id" field.
func SubscriptionIDGT(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldSubscriptionID, v))
}

// SubscriptionIDGTE applies the GTE predicate on the "subscription_id" field.
func SubscriptionIDGTE(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldSubscriptionID, v))
}

// SubscriptionIDLT applies the LT predicate on the "subscription_id" field.
func SubscriptionIDLT(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldSubscriptionID, v))
}

// SubscriptionIDLTE applies the LTE predicate on the "subscription_id" field.
func SubscriptionIDLTE(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldSubscriptionID, v))
}

// ChangeTypeEQ applies the EQ predicate on the "change_type" field.
func ChangeTypeEQ(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldChangeType, v))
}

// ChangeTypeNEQ applies the NEQ predicate on the "change_type" field.
func ChangeTypeNEQ(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldChangeType, v))
}

// ChangeTypeIn applies the In predicate on the "change_type" field.
func ChangeTypeIn(vs ...string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldChangeType, vs...))
}

// ChangeTypeNotIn applies the NotIn predicate on the "change_type" field.
func ChangeTypeNotIn(vs ...string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldChangeType, vs...))
}

// ChangeTypeGT applies the GT predicate on the "change_type" field.
func ChangeTypeGT(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldChangeType, v))
}

// ChangeTypeGTE applies the GTE predicate on the "change_type" field.
func ChangeTypeGTE(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldChangeType, v))
}

// ChangeTypeLT applies the LT predicate on the "change_type" field.
func ChangeTypeLT(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldChangeType, v))
}

// ChangeTypeLTE applies the LTE predicate on the "change_type" field.
func ChangeTypeLTE(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldChangeType, v))
}

// ChangeTypeContains applies the Contains predicate on the "change_type" field.
func ChangeTypeContains(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldContains(FieldChangeType, v))
}

// ChangeTypeHasPrefix applies the HasPrefix predicate on the "change_type" field.
func ChangeTypeHasPrefix(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldHasPrefix(FieldChangeType, v))
}

// ChangeTypeHasSuffix applies the HasSuffix predicate on the "change_type" field.
func ChangeTypeHasSuffix(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldHasSuffix(FieldChangeType, v))
}

// ChangeTypeEqualFold applies the EqualFold predicate on the "change_type" field.
func ChangeTypeEqualFold(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEqualFold(FieldChangeType, v))
}

// ChangeTypeContainsFold applies the ContainsFold predicate on the "change_type" field.
func ChangeTypeContainsFold(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldContainsFold(FieldChangeType, v))
}

// FromPlanIDEQ applies the EQ predicate on the "from_plan_id" field.
func FromPlanIDEQ(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldFromPlanID, v))
}

// FromPlanIDNEQ applies the NEQ predicate on the "from_plan_id" field.
func FromPlanIDNEQ(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldFromPlanID, v))
}

// FromPlanIDIn applies the In predicate on the "from_plan_id" field.
func FromPlanIDIn(vs ...int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldFromPlanID, vs...))
}

// FromPlanIDNotIn applies the NotIn predicate on the "from_plan_id" field.
func FromPlanIDNotIn(vs ...int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldFromPlanID, vs...))
}

// FromPlanIDGT applies the GT predicate on the "from_plan_id" field.
func FromPlanIDGT(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldFromPlanID, v))
}

// FromPlanIDGTE applies the GTE predicate on the "from_plan_id" field.
func FromPlanIDGTE(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldFromPlanID, v))
}

// FromPlanIDLT applies the LT predicate on the "from_plan_id" field.
func FromPlanIDLT(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldFromPlanID, v))
}

// FromPlanIDLTE applies the LTE predicate on the "from_plan_id" field.
func FromPlanIDLTE(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldFromPlanID, v))
}

// FromPlanIDIsNil applies the IsNil predicate on the "from_plan_id" field.
func FromPlanIDIsNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIsNull(FieldFromPlanID))
}

// FromPlanIDNotNil applies the NotNil predicate on the "from_plan_id" field.
func FromPlanIDNotNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotNull(FieldFromPlanID))
}

// ToPlanIDEQ applies the EQ predicate on the "to_plan_id" field.
func ToPlanIDEQ(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldToPlanID, v))
}

// ToPlanIDNEQ applies the NEQ predicate on the "to_plan_id" field.
func ToPlanIDNEQ(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldToPlanID, v))
}

// ToPlanIDIn applies the In predicate on the "to_plan_id" field.
func ToPlanIDIn(vs ...int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldToPlanID, vs...))
}

// ToPlanIDNotIn applies the NotIn predicate on the "to_plan_id" field.
func ToPlanIDNotIn(vs ...int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldToPlanID, vs...))
}

// ToPlanIDGT applies the GT predicate on the "to_plan_id" field.
func ToPlanIDGT(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldToPlanID, v))
}

// ToPlanIDGTE applies the GTE predicate on the "to_plan_id" field.
func ToPlanIDGTE(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldToPlanID, v))
}

// ToPlanIDLT applies the LT predicate on the "to_plan_id" field.
func ToPlanIDLT(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldToPlanID, v))
}

// ToPlanIDLTE applies the LTE predicate on the "to_plan_id" field.
func ToPlanIDLTE(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldToPlanID, v))
}

// FromGroupIDEQ applies the EQ predicate on the "from_group_id" field.
func FromGroupIDEQ(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldFromGroupID, v))
}

// FromGroupIDNEQ applies the NEQ predicate on the "from_group_id" field.
func FromGroupIDNEQ(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldFromGroupID, v))
}

// FromGroupIDIn applies the In predicate on the "from_group_id" field.
func FromGroupIDIn(vs ...int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldFromGroupID, vs...))
}

// FromGroupIDNotIn applies the NotIn predicate on the "from_group_id" field.
func FromGroupIDNotIn(vs ...int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldFromGroupID, vs...))
}

// FromGroupIDGT applies the GT predicate on the "from_group_id" field.
func FromGroupIDGT(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldFromGroupID, v))
}

// FromGroupIDGTE applies the GTE predicate on the "from_group_id" field.
func FromGroupIDGTE(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldFromGroupID, v))
}

// FromGroupIDLT applies the LT predicate on the "from_group_id" field.
func FromGroupIDLT(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldFromGroupID, v))
}

// FromGroupIDLTE applies the LTE predicate on the "from_group_id" field.
func FromGroupIDLTE(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldFromGroupID, v))
}

// FromGroupIDIsNil applies the IsNil predicate on the "from_group_id" field.
func FromGroupIDIsNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIsNull(FieldFromGroupID))
}

// FromGroupIDNotNil applies the NotNil predicate on the "from_group_id" field.
func FromGroupIDNotNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotNull(FieldFromGroupID))
}

// ToGroupIDEQ applies the EQ predicate on the "to_group_id" field.
func ToGroupIDEQ(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldToGroupID, v))
}

// ToGroupIDNEQ applies the NEQ predicate on the "to_group_id" field.
func ToGroupIDNEQ(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldToGroupID, v))
}

// ToGroupIDIn applies the In predicate on the "to_group_id" field.
func ToGroupIDIn(vs ...int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldToGroupID, vs...))
}

// ToGroupIDNotIn applies the NotIn predicate on the "to_group_id" field.
func ToGroupIDNotIn(vs ...int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldToGroupID, vs...))
}

// ToGroupIDGT applies the GT predicate on the "to_group_id" field.
func ToGroupIDGT(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldToGroupID, v))
}

// ToGroupIDGTE applies the GTE predicate on the "to_group_id" field.
func ToGroupIDGTE(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldToGroupID, v))
}

// ToGroupIDLT applies the LT predicate on the "to_group_id" field.
func ToGroupIDLT(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldToGroupID, v))
}

// ToGroupIDLTE applies the LTE predicate on the "to_group_id" field.
func ToGroupIDLTE(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldToGroupID, v))
}

// FromTierEQ applies the EQ predicate on the "from_tier" field.
func FromTierEQ(v int) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldFromTier, v))
}

// FromTierNEQ applies the NEQ predicate on the "from_tier" field.
func FromTierNEQ(v int) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldFromTier, v))
}

// FromTierIn applies the In predicate on the "from_tier" field.
func FromTierIn(vs ...int) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldFromTier, vs...))
}

// FromTierNotIn applies the NotIn predicate on the "from_tier" field.
func FromTierNotIn(vs ...int) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldFromTier, vs...))
}

// FromTierGT applies the GT predicate on the "from_tier" field.
func FromTierGT(v int) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldFromTier, v))
}

// FromTierGTE applies the GTE predicate on the "from_tier" field.
func FromTierGTE(v int) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldFromTier, v))
}

// FromTierLT applies the LT predicate on the "from_tier" field.
func FromTierLT(v int) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldFromTier, v))
}

// FromTierLTE applies the LTE predicate on the "from_tier" field.
func FromTierLTE(v int) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldFromTier, v))
}

// ToTierEQ applies the EQ predicate on the "to_tier" field.
func ToTierEQ(v int) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldToTier, v))
}

// ToTierNEQ applies the NEQ predicate on the "to_tier" field.
func ToTierNEQ(v int) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldToTier, v))
}

// ToTierIn applies the In predicate on the "to_tier" field.
func ToTierIn(vs ...int) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldToTier, vs...))
}

// ToTierNotIn applies the NotIn predicate on the "to_tier" field.
func ToTierNotIn(vs ...int) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldToTier, vs...))
}

// ToTierGT applies the GT predicate on the "to_tier" field.
func ToTierGT(v int) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldToTier, v))
}

// ToTierGTE applies the GTE predicate on the "to_tier" field.
func ToTierGTE(v int) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldToTier, v))
}

// ToTierLT applies the LT predicate on the "to_tier" field.
func ToTierLT(v int) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldToTier, v))
}

// ToTierLTE applies the LTE predicate on the "to_tier" field.
func ToTierLTE(v int) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldToTier, v))
}

// OldPriceSnapshotEQ applies the EQ predicate on the "old_price_snapshot" field.
func OldPriceSnapshotEQ(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldOldPriceSnapshot, v))
}

// OldPriceSnapshotNEQ applies the NEQ predicate on the "old_price_snapshot" field.
func OldPriceSnapshotNEQ(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldOldPriceSnapshot, v))
}

// OldPriceSnapshotIn applies the In predicate on the "old_price_snapshot" field.
func OldPriceSnapshotIn(vs ...float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldOldPriceSnapshot, vs...))
}

// OldPriceSnapshotNotIn applies the NotIn predicate on the "old_price_snapshot" field.
func OldPriceSnapshotNotIn(vs ...float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldOldPriceSnapshot, vs...))
}

// OldPriceSnapshotGT applies the GT predicate on the "old_price_snapshot" field.
func OldPriceSnapshotGT(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldOldPriceSnapshot, v))
}

// OldPriceSnapshotGTE applies the GTE predicate on the "old_price_snapshot" field.
func OldPriceSnapshotGTE(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldOldPriceSnapshot, v))
}

// OldPriceSnapshotLT applies the LT predicate on the "old_price_snapshot" field.
func OldPriceSnapshotLT(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldOldPriceSnapshot, v))
}

// OldPriceSnapshotLTE applies the LTE predicate on the "old_price_snapshot" field.
func OldPriceSnapshotLTE(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldOldPriceSnapshot, v))
}

// OldPriceSnapshotIsNil applies the IsNil predicate on the "old_price_snapshot" field.
func OldPriceSnapshotIsNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIsNull(FieldOldPriceSnapshot))
}

// OldPriceSnapshotNotNil applies the NotNil predicate on the "old_price_snapshot" field.
func OldPriceSnapshotNotNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotNull(FieldOldPriceSnapshot))
}

// NewPriceSnapshotEQ applies the EQ predicate on the "new_price_snapshot" field.
func NewPriceSnapshotEQ(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldNewPriceSnapshot, v))
}

// NewPriceSnapshotNEQ applies the NEQ predicate on the "new_price_snapshot" field.
func NewPriceSnapshotNEQ(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldNewPriceSnapshot, v))
}

// NewPriceSnapshotIn applies the In predicate on the "new_price_snapshot" field.
func NewPriceSnapshotIn(vs ...float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldNewPriceSnapshot, vs...))
}

// NewPriceSnapshotNotIn applies the NotIn predicate on the "new_price_snapshot" field.
func NewPriceSnapshotNotIn(vs ...float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldNewPriceSnapshot, vs...))
}

// NewPriceSnapshotGT applies the GT predicate on the "new_price_snapshot" field.
func NewPriceSnapshotGT(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldNewPriceSnapshot, v))
}

// NewPriceSnapshotGTE applies the GTE predicate on the "new_price_snapshot" field.
func NewPriceSnapshotGTE(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldNewPriceSnapshot, v))
}

// NewPriceSnapshotLT applies the LT predicate on the "new_price_snapshot" field.
func NewPriceSnapshotLT(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldNewPriceSnapshot, v))
}

// NewPriceSnapshotLTE applies the LTE predicate on the "new_price_snapshot" field.
func NewPriceSnapshotLTE(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldNewPriceSnapshot, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldContainsFold(FieldCurrency, v))
}

// TermStartEQ applies the EQ predicate on the "term_start" field.
func TermStartEQ(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldTermStart, v))
}

// TermStartNEQ applies the NEQ predicate on the "term_start" field.
func TermStartNEQ(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldTermStart, v))
}

// TermStartIn applies the In predicate on the "term_start" field.
func TermStartIn(vs ...time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldTermStart, vs...))
}

// TermStartNotIn applies the NotIn predicate on the "term_start" field.
func TermStartNotIn(vs ...time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldTermStart, vs...))
}

// TermStartGT applies the GT predicate on the "term_start" field.
func TermStartGT(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldTermStart, v))
}

// TermStartGTE applies the GTE predicate on the "term_start" field.
func TermStartGTE(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldTermStart, v))
}

// TermStartLT applies the LT predicate on the "term_start" field.
func TermStartLT(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldTermStart, v))
}

// TermStartLTE applies the LTE predicate on the "term_start" field.
func TermStartLTE(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldTermStart, v))
}

// TermStartIsNil applies the IsNil predicate on the "term_start" field.
func TermStartIsNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIsNull(FieldTermStart))
}

// TermStartNotNil applies the NotNil predicate on the "term_start" field.
func TermStartNotNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotNull(FieldTermStart))
}

// TermEndEQ applies the EQ predicate on the "term_end" field.
func TermEndEQ(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldTermEnd, v))
}

// TermEndNEQ applies the NEQ predicate on the "term_end" field.
func TermEndNEQ(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldTermEnd, v))
}

// TermEndIn applies the In predicate on the "term_end" field.
func TermEndIn(vs ...time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldTermEnd, vs...))
}

// TermEndNotIn applies the NotIn predicate on the "term_end" field.
func TermEndNotIn(vs ...time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldTermEnd, vs...))
}

// TermEndGT applies the GT predicate on the "term_end" field.
func TermEndGT(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldTermEnd, v))
}

// TermEndGTE applies the GTE predicate on the "term_end" field.
func TermEndGTE(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldTermEnd, v))
}

// TermEndLT applies the LT predicate on the "term_end" field.
func TermEndLT(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldTermEnd, v))
}

// TermEndLTE applies the LTE predicate on the "term_end" field.
func TermEndLTE(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldTermEnd, v))
}

// TermEndIsNil applies the IsNil predicate on the "term_end" field.
func TermEndIsNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIsNull(FieldTermEnd))
}

// TermEndNotNil applies the NotNil predicate on the "term_end" field.
func TermEndNotNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotNull(FieldTermEnd))
}

// RemainingSecondsEQ applies the EQ predicate on the "remaining_seconds" field.
func RemainingSecondsEQ(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldRemainingSeconds, v))
}

// RemainingSecondsNEQ applies the NEQ predicate on the "remaining_seconds" field.
func RemainingSecondsNEQ(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldRemainingSeconds, v))
}

// RemainingSecondsIn applies the In predicate on the "remaining_seconds" field.
func RemainingSecondsIn(vs ...int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldRemainingSeconds, vs...))
}

// RemainingSecondsNotIn applies the NotIn predicate on the "remaining_seconds" field.
func RemainingSecondsNotIn(vs ...int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldRemainingSeconds, vs...))
}

// RemainingSecondsGT applies the GT predicate on the "remaining_seconds" field.
func RemainingSecondsGT(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldRemainingSeconds, v))
}

// RemainingSecondsGTE applies the GTE predicate on the "remaining_seconds" field.
func RemainingSecondsGTE(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldRemainingSeconds, v))
}

// RemainingSecondsLT applies the LT predicate on the "remaining_seconds" field.
func RemainingSecondsLT(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldRemainingSeconds, v))
}

// RemainingSecondsLTE applies the LTE predicate on the "remaining_seconds" field.
func RemainingSecondsLTE(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldRemainingSeconds, v))
}

// UnusedCreditEQ applies the EQ predicate on the "unused_credit" field.
func UnusedCreditEQ(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldUnusedCredit, v))
}

// UnusedCreditNEQ applies the NEQ predicate on the "unused_credit" field.
func UnusedCreditNEQ(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldUnusedCredit, v))
}

// UnusedCreditIn applies the In predicate on the "unused_credit" field.
func UnusedCreditIn(vs ...float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldUnusedCredit, vs...))
}

// UnusedCreditNotIn applies the NotIn predicate on the "unused_credit" field.
func UnusedCreditNotIn(vs ...float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldUnusedCredit, vs...))
}

// UnusedCreditGT applies the GT predicate on the "unused_credit" field.
func UnusedCreditGT(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldUnusedCredit, v))
}

// UnusedCreditGTE applies the GTE predicate on the "unused_credit" field.
func UnusedCreditGTE(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldUnusedCredit, v))
}

// UnusedCreditLT applies the LT predicate on the "unused_credit" field.
func UnusedCreditLT(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldUnusedCredit, v))
}

// UnusedCreditLTE applies the LTE predicate on the "unused_credit" field.
func UnusedCreditLTE(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldUnusedCredit, v))
}

// ProratedChargeEQ applies the EQ predicate on the "prorated_charge" field.
func ProratedChargeEQ(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldProratedCharge, v))
}

// ProratedChargeNEQ applies the NEQ predicate on the "prorated_charge" field.
func ProratedChargeNEQ(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldProratedCharge, v))
}

// ProratedChargeIn applies the In predicate on the "prorated_charge" field.
func ProratedChargeIn(vs ...float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldProratedCharge, vs...))
}

// ProratedChargeNotIn applies the NotIn predicate on the "prorated_charge" field.
func ProratedChargeNotIn(vs ...float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldProratedCharge, vs...))
}

// ProratedChargeGT applies the GT predicate on the "prorated_charge" field.
func ProratedChargeGT(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldProratedCharge, v))
}

// ProratedChargeGTE applies the GTE predicate on the "prorated_charge" field.
func ProratedChargeGTE(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldProratedCharge, v))
}

// ProratedChargeLT applies the LT predicate on the "prorated_charge" field.
func ProratedChargeLT(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldProratedCharge, v))
}

// ProratedChargeLTE applies the LTE predicate on the "prorated_charge" field.
func ProratedChargeLTE(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldProratedCharge, v))
}

// AmountDueEQ applies the EQ predicate on the "amount_due" field.
func AmountDueEQ(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldAmountDue, v))
}

// AmountDueNEQ applies the NEQ predicate on the "amount_due" field.
func AmountDueNEQ(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldAmountDue, v))
}

// AmountDueIn applies the In predicate on the "amount_due" field.
func AmountDueIn(vs ...float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldAmountDue, vs...))
}

// AmountDueNotIn applies the NotIn predicate on the "amount_due" field.
func AmountDueNotIn(vs ...float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldAmountDue, vs...))
}

// AmountDueGT applies the GT predicate on the "amount_due" field.
func AmountDueGT(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldAmountDue, v))
}

// AmountDueGTE applies the GTE predicate on the "amount_due" field.
func AmountDueGTE(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldAmountDue, v))
}

// AmountDueLT applies the LT predicate on the "amount_due" field.
func AmountDueLT(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldAmountDue, v))
}

// AmountDueLTE applies the LTE predicate on the "amount_due" field.
func AmountDueLTE(v float64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldAmountDue, v))
}

// QuoteCreatedAtEQ applies the EQ predicate on the "quote_created_at" field.
func QuoteCreatedAtEQ(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldQuoteCreatedAt, v))
}

// QuoteCreatedAtNEQ applies the NEQ predicate on the "quote_created_at" field.
func QuoteCreatedAtNEQ(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldQuoteCreatedAt, v))
}

// QuoteCreatedAtIn applies the In predicate on the "quote_created_at" field.
func QuoteCreatedAtIn(vs ...time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldQuoteCreatedAt, vs...))
}

// QuoteCreatedAtNotIn applies the NotIn predicate on the "quote_created_at" field.
func QuoteCreatedAtNotIn(vs ...time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldQuoteCreatedAt, vs...))
}

// QuoteCreatedAtGT applies the GT predicate on the "quote_created_at" field.
func QuoteCreatedAtGT(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldQuoteCreatedAt, v))
}

// QuoteCreatedAtGTE applies the GTE predicate on the "quote_created_at" field.
func QuoteCreatedAtGTE(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldQuoteCreatedAt, v))
}

// QuoteCreatedAtLT applies the LT predicate on the "quote_created_at" field.
func QuoteCreatedAtLT(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldQuoteCreatedAt, v))
}

// QuoteCreatedAtLTE applies the LTE predicate on the "quote_created_at" field.
func QuoteCreatedAtLTE(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldQuoteCreatedAt, v))
}

// QuoteCreatedAtIsNil applies the IsNil predicate on the "quote_created_at" field.
func QuoteCreatedAtIsNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIsNull(FieldQuoteCreatedAt))
}

// QuoteCreatedAtNotNil applies the NotNil predicate on the "quote_created_at" field.
func QuoteCreatedAtNotNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotNull(FieldQuoteCreatedAt))
}

// QuoteExpiresAtEQ applies the EQ predicate on the "quote_expires_at" field.
func QuoteExpiresAtEQ(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldQuoteExpiresAt, v))
}

// QuoteExpiresAtNEQ applies the NEQ predicate on the "quote_expires_at" field.
func QuoteExpiresAtNEQ(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldQuoteExpiresAt, v))
}

// QuoteExpiresAtIn applies the In predicate on the "quote_expires_at" field.
func QuoteExpiresAtIn(vs ...time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldQuoteExpiresAt, vs...))
}

// QuoteExpiresAtNotIn applies the NotIn predicate on the "quote_expires_at" field.
func QuoteExpiresAtNotIn(vs ...time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldQuoteExpiresAt, vs...))
}

// QuoteExpiresAtGT applies the GT predicate on the "quote_expires_at" field.
func QuoteExpiresAtGT(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldQuoteExpiresAt, v))
}

// QuoteExpiresAtGTE applies the GTE predicate on the "quote_expires_at" field.
func QuoteExpiresAtGTE(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldQuoteExpiresAt, v))
}

// QuoteExpiresAtLT applies the LT predicate on the "quote_expires_at" field.
func QuoteExpiresAtLT(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldQuoteExpiresAt, v))
}

// QuoteExpiresAtLTE applies the LTE predicate on the "quote_expires_at" field.
func QuoteExpiresAtLTE(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldQuoteExpiresAt, v))
}

// QuoteExpiresAtIsNil applies the IsNil predicate on the "quote_expires_at" field.
func QuoteExpiresAtIsNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIsNull(FieldQuoteExpiresAt))
}

// QuoteExpiresAtNotNil applies the NotNil predicate on the "quote_expires_at" field.
func QuoteExpiresAtNotNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotNull(FieldQuoteExpiresAt))
}

// EffectiveAtEQ applies the EQ predicate on the "effective_at" field.
func EffectiveAtEQ(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldEffectiveAt, v))
}

// EffectiveAtNEQ applies the NEQ predicate on the "effective_at" field.
func EffectiveAtNEQ(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldEffectiveAt, v))
}

// EffectiveAtIn applies the In predicate on the "effective_at" field.
func EffectiveAtIn(vs ...time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldEffectiveAt, vs...))
}

// EffectiveAtNotIn applies the NotIn predicate on the "effective_at" field.
func EffectiveAtNotIn(vs ...time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldEffectiveAt, vs...))
}

// EffectiveAtGT applies the GT predicate on the "effective_at" field.
func EffectiveAtGT(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldEffectiveAt, v))
}

// EffectiveAtGTE applies the GTE predicate on the "effective_at" field.
func EffectiveAtGTE(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldEffectiveAt, v))
}

// EffectiveAtLT applies the LT predicate on the "effective_at" field.
func EffectiveAtLT(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldEffectiveAt, v))
}

// EffectiveAtLTE applies the LTE predicate on the "effective_at" field.
func EffectiveAtLTE(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldEffectiveAt, v))
}

// EffectiveAtIsNil applies the IsNil predicate on the "effective_at" field.
func EffectiveAtIsNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIsNull(FieldEffectiveAt))
}

// EffectiveAtNotNil applies the NotNil predicate on the "effective_at" field.
func EffectiveAtNotNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotNull(FieldEffectiveAt))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldContainsFold(FieldStatus, v))
}

// CancelReasonEQ applies the EQ predicate on the "cancel_reason" field.
func CancelReasonEQ(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldCancelReason, v))
}

// CancelReasonNEQ applies the NEQ predicate on the "cancel_reason" field.
func CancelReasonNEQ(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldCancelReason, v))
}

// CancelReasonIn applies the In predicate on the "cancel_reason" field.
func CancelReasonIn(vs ...string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldCancelReason, vs...))
}

// CancelReasonNotIn applies the NotIn predicate on the "cancel_reason" field.
func CancelReasonNotIn(vs ...string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldCancelReason, vs...))
}

// CancelReasonGT applies the GT predicate on the "cancel_reason" field.
func CancelReasonGT(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldCancelReason, v))
}

// CancelReasonGTE applies the GTE predicate on the "cancel_reason" field.
func CancelReasonGTE(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldCancelReason, v))
}

// CancelReasonLT applies the LT predicate on the "cancel_reason" field.
func CancelReasonLT(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldCancelReason, v))
}

// CancelReasonLTE applies the LTE predicate on the "cancel_reason" field.
func CancelReasonLTE(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldCancelReason, v))
}

// CancelReasonContains applies the Contains predicate on the "cancel_reason" field.
func CancelReasonContains(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldContains(FieldCancelReason, v))
}

// CancelReasonHasPrefix applies the HasPrefix predicate on the "cancel_reason" field.
func CancelReasonHasPrefix(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldHasPrefix(FieldCancelReason, v))
}

// CancelReasonHasSuffix applies the HasSuffix predicate on the "cancel_reason" field.
func CancelReasonHasSuffix(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldHasSuffix(FieldCancelReason, v))
}

// CancelReasonIsNil applies the IsNil predicate on the "cancel_reason" field.
func CancelReasonIsNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIsNull(FieldCancelReason))
}

// CancelReasonNotNil applies the NotNil predicate on the "cancel_reason" field.
func CancelReasonNotNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotNull(FieldCancelReason))
}

// CancelReasonEqualFold applies the EqualFold predicate on the "cancel_reason" field.
func CancelReasonEqualFold(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEqualFold(FieldCancelReason, v))
}

// CancelReasonContainsFold applies the ContainsFold predicate on the "cancel_reason" field.
func CancelReasonContainsFold(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldContainsFold(FieldCancelReason, v))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDGT applies the GT predicate on the "order_id" field.
func OrderIDGT(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldOrderID, v))
}

// OrderIDGTE applies the GTE predicate on the "order_id" field.
func OrderIDGTE(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldOrderID, v))
}

// OrderIDLT applies the LT predicate on the "order_id" field.
func OrderIDLT(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldOrderID, v))
}

// OrderIDLTE applies the LTE predicate on the "order_id" field.
func OrderIDLTE(v int64) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldOrderID, v))
}

// OrderIDIsNil applies the IsNil predicate on the "order_id" field.
func OrderIDIsNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIsNull(FieldOrderID))
}

// OrderIDNotNil applies the NotNil predicate on the "order_id" field.
func OrderIDNotNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotNull(FieldOrderID))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyIsNil applies the IsNil predicate on the "idempotency_key" field.
func IdempotencyKeyIsNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIsNull(FieldIdempotencyKey))
}

// IdempotencyKeyNotNil applies the NotNil predicate on the "idempotency_key" field.
func IdempotencyKeyNotNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotNull(FieldIdempotencyKey))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// PaidAtEQ applies the EQ predicate on the "paid_at" field.
func PaidAtEQ(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldPaidAt, v))
}

// PaidAtNEQ applies the NEQ predicate on the "paid_at" field.
func PaidAtNEQ(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldPaidAt, v))
}

// PaidAtIn applies the In predicate on the "paid_at" field.
func PaidAtIn(vs ...time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldPaidAt, vs...))
}

// PaidAtNotIn applies the NotIn predicate on the "paid_at" field.
func PaidAtNotIn(vs ...time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldPaidAt, vs...))
}

// PaidAtGT applies the GT predicate on the "paid_at" field.
func PaidAtGT(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldPaidAt, v))
}

// PaidAtGTE applies the GTE predicate on the "paid_at" field.
func PaidAtGTE(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldPaidAt, v))
}

// PaidAtLT applies the LT predicate on the "paid_at" field.
func PaidAtLT(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldPaidAt, v))
}

// PaidAtLTE applies the LTE predicate on the "paid_at" field.
func PaidAtLTE(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldPaidAt, v))
}

// PaidAtIsNil applies the IsNil predicate on the "paid_at" field.
func PaidAtIsNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIsNull(FieldPaidAt))
}

// PaidAtNotNil applies the NotNil predicate on the "paid_at" field.
func PaidAtNotNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotNull(FieldPaidAt))
}

// FulfilledAtEQ applies the EQ predicate on the "fulfilled_at" field.
func FulfilledAtEQ(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldFulfilledAt, v))
}

// FulfilledAtNEQ applies the NEQ predicate on the "fulfilled_at" field.
func FulfilledAtNEQ(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldFulfilledAt, v))
}

// FulfilledAtIn applies the In predicate on the "fulfilled_at" field.
func FulfilledAtIn(vs ...time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldFulfilledAt, vs...))
}

// FulfilledAtNotIn applies the NotIn predicate on the "fulfilled_at" field.
func FulfilledAtNotIn(vs ...time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldFulfilledAt, vs...))
}

// FulfilledAtGT applies the GT predicate on the "fulfilled_at" field.
func FulfilledAtGT(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldFulfilledAt, v))
}

// FulfilledAtGTE applies the GTE predicate on the "fulfilled_at" field.
func FulfilledAtGTE(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldFulfilledAt, v))
}

// FulfilledAtLT applies the LT predicate on the "fulfilled_at" field.
func FulfilledAtLT(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldFulfilledAt, v))
}

// FulfilledAtLTE applies the LTE predicate on the "fulfilled_at" field.
func FulfilledAtLTE(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldFulfilledAt, v))
}

// FulfilledAtIsNil applies the IsNil predicate on the "fulfilled_at" field.
func FulfilledAtIsNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIsNull(FieldFulfilledAt))
}

// FulfilledAtNotNil applies the NotNil predicate on the "fulfilled_at" field.
func FulfilledAtNotNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotNull(FieldFulfilledAt))
}

// CancelledAtEQ applies the EQ predicate on the "cancelled_at" field.
func CancelledAtEQ(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldEQ(FieldCancelledAt, v))
}

// CancelledAtNEQ applies the NEQ predicate on the "cancelled_at" field.
func CancelledAtNEQ(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNEQ(FieldCancelledAt, v))
}

// CancelledAtIn applies the In predicate on the "cancelled_at" field.
func CancelledAtIn(vs ...time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIn(FieldCancelledAt, vs...))
}

// CancelledAtNotIn applies the NotIn predicate on the "cancelled_at" field.
func CancelledAtNotIn(vs ...time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotIn(FieldCancelledAt, vs...))
}

// CancelledAtGT applies the GT predicate on the "cancelled_at" field.
func CancelledAtGT(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGT(FieldCancelledAt, v))
}

// CancelledAtGTE applies the GTE predicate on the "cancelled_at" field.
func CancelledAtGTE(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldGTE(FieldCancelledAt, v))
}

// CancelledAtLT applies the LT predicate on the "cancelled_at" field.
func CancelledAtLT(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLT(FieldCancelledAt, v))
}

// CancelledAtLTE applies the LTE predicate on the "cancelled_at" field.
func CancelledAtLTE(v time.Time) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldLTE(FieldCancelledAt, v))
}

// CancelledAtIsNil applies the IsNil predicate on the "cancelled_at" field.
func CancelledAtIsNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldIsNull(FieldCancelledAt))
}

// CancelledAtNotNil applies the NotNil predicate on the "cancelled_at" field.
func CancelledAtNotNil() predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.FieldNotNull(FieldCancelledAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubscriptionPlanChange) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubscriptionPlanChange) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubscriptionPlanChange) predicate.SubscriptionPlanChange {
	return predicate.SubscriptionPlanChange(sql.NotPredicates(p))
}
