// Code generated by ent, DO NOT EDIT.

package presentationmodelpricing

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the presentationmodelpricing type in the database.
	Label = "presentation_model_pricing"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldModelName holds the string denoting the model_name field in the database.
	FieldModelName = "model_name"
	// FieldBillingMode holds the string denoting the billing_mode field in the database.
	FieldBillingMode = "billing_mode"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldInputPrice holds the string denoting the input_price field in the database.
	FieldInputPrice = "input_price"
	// FieldOutputPrice holds the string denoting the output_price field in the database.
	FieldOutputPrice = "output_price"
	// FieldCacheWritePrice holds the string denoting the cache_write_price field in the database.
	FieldCacheWritePrice = "cache_write_price"
	// FieldCacheWrite1hPrice holds the string denoting the cache_write_1h_price field in the database.
	FieldCacheWrite1hPrice = "cache_write_1h_price"
	// FieldCacheReadPrice holds the string denoting the cache_read_price field in the database.
	FieldCacheReadPrice = "cache_read_price"
	// FieldPerRequestPrice holds the string denoting the per_request_price field in the database.
	FieldPerRequestPrice = "per_request_price"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the presentationmodelpricing in the database.
	Table = "presentation_model_pricing"
)

// Columns holds all SQL columns for presentationmodelpricing fields.
var Columns = []string{
	FieldID,
	FieldModelName,
	FieldBillingMode,
	FieldCurrency,
	FieldInputPrice,
	FieldOutputPrice,
	FieldCacheWritePrice,
	FieldCacheWrite1hPrice,
	FieldCacheReadPrice,
	FieldPerRequestPrice,
	FieldEnabled,
	FieldRemark,
	FieldUpdatedBy,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ModelNameValidator is a validator for the "model_name" field. It is called by the builders before save.
	ModelNameValidator func(string) error
	// DefaultBillingMode holds the default value on creation for the "billing_mode" field.
	DefaultBillingMode string
	// BillingModeValidator is a validator for the "billing_mode" field. It is called by the builders before save.
	BillingModeValidator func(string) error
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the PresentationModelPricing queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByModelName orders the results by the model_name field.
func ByModelName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelName, opts...).ToFunc()
}

// ByBillingMode orders the results by the billing_mode field.
func ByBillingMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingMode, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByInputPrice orders the results by the input_price field.
func ByInputPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputPrice, opts...).ToFunc()
}

// ByOutputPrice orders the results by the output_price field.
func ByOutputPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputPrice, opts...).ToFunc()
}

// ByCacheWritePrice orders the results by the cache_write_price field.
func ByCacheWritePrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheWritePrice, opts...).ToFunc()
}

// ByCacheWrite1hPrice orders the results by the cache_write_1h_price field.
func ByCacheWrite1hPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheWrite1hPrice, opts...).ToFunc()
}

// ByCacheReadPrice orders the results by the cache_read_price field.
func ByCacheReadPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheReadPrice, opts...).ToFunc()
}

// ByPerRequestPrice orders the results by the per_request_price field.
func ByPerRequestPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPerRequestPrice, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
